//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Tools.Reporting {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Tools.Reporting.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 主要图像 的本地化字符串。
        /// </summary>
        internal static string DefaultKeyObjectSelectionSeriesDescription {
            get {
                return ResourceManager.GetString("DefaultKeyObjectSelectionSeriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建关键图像（检查追加）的权限被拒绝。 的本地化字符串。
        /// </summary>
        internal static string ExceptionCreateKeyImagePermissionDenied {
            get {
                return ResourceManager.GetString("ExceptionCreateKeyImagePermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看关键图像 (检查视图) 的权限被拒绝。 的本地化字符串。
        /// </summary>
        internal static string ExceptionViewKeyImagePermissionDenied {
            get {
                return ResourceManager.GetString("ExceptionViewKeyImagePermissionDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1} [{2}] 的本地化字符串。
        /// </summary>
        internal static string FormatOriginalKeyImageSelection {
            get {
                return ResourceManager.GetString("FormatOriginalKeyImageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键图像 (当前) 的本地化字符串。
        /// </summary>
        internal static string LabelKeyImageCurrentDisplaySet {
            get {
                return ResourceManager.GetString("LabelKeyImageCurrentDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （新的关键图像选择） 的本地化字符串。
        /// </summary>
        internal static string LabelNewKeyImageSelection {
            get {
                return ResourceManager.GetString("LabelNewKeyImageSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建关键图像 的本地化字符串。
        /// </summary>
        internal static string MenuCreateKeyImage {
            get {
                return ResourceManager.GetString("MenuCreateKeyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除关键图像 的本地化字符串。
        /// </summary>
        internal static string MenuDeleteKeyImage {
            get {
                return ResourceManager.GetString("MenuDeleteKeyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复关键图像 的本地化字符串。
        /// </summary>
        internal static string MenuRevertKeyImage {
            get {
                return ResourceManager.GetString("MenuRevertKeyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示关键图像 的本地化字符串。
        /// </summary>
        internal static string MenuShowKeyImages {
            get {
                return ResourceManager.GetString("MenuShowKeyImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法发布关键图像，因为本地服务未运行。请启动该服务，然后单击“确定”继续发布。要放弃关键图像，请单击“取消”。 的本地化字符串。
        /// </summary>
        internal static string MessageCannotPublishKeyImagesServersNotRunning {
            get {
                return ResourceManager.GetString("MessageCannotPublishKeyImagesServersNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法从当前选择创建关键图像。 的本地化字符串。
        /// </summary>
        internal static string MessageCreateKeyImageFailed {
            get {
                return ResourceManager.GetString("MessageCreateKeyImageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列说明必须介于1到64个字符之间。 的本地化字符串。
        /// </summary>
        internal static string MessageInvalidSeriesDescription {
            get {
                return ResourceManager.GetString("MessageInvalidSeriesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列号必须是正整数。 的本地化字符串。
        /// </summary>
        internal static string MessageInvalidSeriesNumber {
            get {
                return ResourceManager.GetString("MessageInvalidSeriesNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发布的关键图像失败。 有关详细信息, 请参阅日志。 的本地化字符串。
        /// </summary>
        internal static string MessageKeyImagePublishingFailed {
            get {
                return ResourceManager.GetString("MessageKeyImagePublishingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个或多个密钥图像无法还原, 因为它们以前从未保存过。请考虑删除它们。 的本地化字符串。
        /// </summary>
        internal static string MessageUnableToRevertSomeKeyImages {
            get {
                return ResourceManager.GetString("MessageUnableToRevertSomeKeyImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建关键对象选择 的本地化字符串。
        /// </summary>
        internal static string TitleCreateKeyObjectSelection {
            get {
                return ResourceManager.GetString("TitleCreateKeyObjectSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑关键图像信息 的本地化字符串。
        /// </summary>
        internal static string TitleEditKeyImageInformation {
            get {
                return ResourceManager.GetString("TitleEditKeyImageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键图像 的本地化字符串。
        /// </summary>
        internal static string TitleKeyImages {
            get {
                return ResourceManager.GetString("TitleKeyImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建关键图像 的本地化字符串。
        /// </summary>
        internal static string ToolbarCreateKeyImage {
            get {
                return ResourceManager.GetString("ToolbarCreateKeyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除关键图像 的本地化字符串。
        /// </summary>
        internal static string ToolbarDeleteKeyImage {
            get {
                return ResourceManager.GetString("ToolbarDeleteKeyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        internal static string ToolbarEditKeyImageInformation {
            get {
                return ResourceManager.GetString("ToolbarEditKeyImageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还原所有图像 的本地化字符串。
        /// </summary>
        internal static string ToolbarRevertAllKeyImages {
            get {
                return ResourceManager.GetString("ToolbarRevertAllKeyImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还原关键图像 的本地化字符串。
        /// </summary>
        internal static string ToolbarRevertKeyImage {
            get {
                return ResourceManager.GetString("ToolbarRevertKeyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示关键图像 的本地化字符串。
        /// </summary>
        internal static string ToolbarShowKeyImages {
            get {
                return ResourceManager.GetString("ToolbarShowKeyImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建关键图像 的本地化字符串。
        /// </summary>
        internal static string TooltipCreateKeyImage {
            get {
                return ResourceManager.GetString("TooltipCreateKeyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除关键图像 的本地化字符串。
        /// </summary>
        internal static string TooltipDeleteKeyImage {
            get {
                return ResourceManager.GetString("TooltipDeleteKeyImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑关键图像信息 的本地化字符串。
        /// </summary>
        internal static string TooltipEditKeyImageInformation {
            get {
                return ResourceManager.GetString("TooltipEditKeyImageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示关键图像 的本地化字符串。
        /// </summary>
        internal static string TooltipShowKeyImages {
            get {
                return ResourceManager.GetString("TooltipShowKeyImages", resourceCulture);
            }
        }
    }
}
