<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Devart.Data" Version="5.0.2070" />
    <PackageReference Include="Devart.Data.Linq" Version="4.8.1615" />
    <PackageReference Include="Devart.Data.MySql" Version="8.12.1278" />
    <PackageReference Include="Devart.Data.MySql.Linq" Version="4.8.1615" />
  </ItemGroup>

</Project>
