//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9035
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Layout.Basic {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Layout.Basic.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 拓扑 的本地化字符串。
        /// </summary>
        public static string CommandExplodeTile {
            get {
                return ResourceManager.GetString("CommandExplodeTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局图像框 的本地化字符串。
        /// </summary>
        public static string CommandLayoutImageBoxes {
            get {
                return ResourceManager.GetString("CommandLayoutImageBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局磁贴 的本地化字符串。
        /// </summary>
        public static string CommandLayoutTiles {
            get {
                return ResourceManager.GetString("CommandLayoutTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量/分解 的本地化字符串。
        /// </summary>
        public static string CommandSurveyExplode {
            get {
                return ResourceManager.GetString("CommandSurveyExplode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (显示集列表) 的本地化字符串。
        /// </summary>
        public static string DisplaySets {
            get {
                return ResourceManager.GetString("DisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前未加载指定的图像（SopInstanceUID = {0}）。 的本地化字符串。
        /// </summary>
        public static string ExceptionImageNotLoaded {
            get {
                return ResourceManager.GetString("ExceptionImageNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前未加载指定的序列（SeriesInstanceUID = {0}）。 的本地化字符串。
        /// </summary>
        public static string ExceptionSeriesNotLoaded {
            get {
                return ResourceManager.GetString("ExceptionSeriesNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前未加载指定的检查（StudyInstanceUID = {0}）。 的本地化字符串。
        /// </summary>
        public static string ExceptionStudyNotLoaded {
            get {
                return ResourceManager.GetString("ExceptionStudyNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在使用中 的本地化字符串。
        /// </summary>
        public static string InUse {
            get {
                return ResourceManager.GetString("InUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建单个图像显示集 的本地化字符串。
        /// </summary>
        public static string LabelCreateSingleImageDisplaySets {
            get {
                return ResourceManager.GetString("LabelCreateSingleImageDisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (默认值) 的本地化字符串。
        /// </summary>
        public static string LabelDefault {
            get {
                return ResourceManager.GetString("LabelDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该检查是{0}。 的本地化字符串。
        /// </summary>
        public static string LabelFormatStudyUnavailable {
            get {
                return ResourceManager.GetString("LabelFormatStudyUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在优先加载... 的本地化字符串。
        /// </summary>
        public static string LabelLoadingPriors {
            get {
                return ResourceManager.GetString("LabelLoadingPriors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拆分多回波系列 的本地化字符串。
        /// </summary>
        public static string LabelSplitEchos {
            get {
                return ResourceManager.GetString("LabelSplitEchos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 拆分混合多框架系列 的本地化字符串。
        /// </summary>
        public static string LabelSplitMultiframes {
            get {
                return ResourceManager.GetString("LabelSplitMultiframes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该检查无法加载。 的本地化字符串。
        /// </summary>
        public static string LabelStudyCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("LabelStudyCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量/分解 的本地化字符串。
        /// </summary>
        public static string MenuExplodeImageBox {
            get {
                return ResourceManager.GetString("MenuExplodeImageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局管理器 的本地化字符串。
        /// </summary>
        public static string MenuLayoutManager {
            get {
                return ResourceManager.GetString("MenuLayoutManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一个显示集 的本地化字符串。
        /// </summary>
        public static string MenuNextDisplaySet {
            get {
                return ResourceManager.GetString("MenuNextDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一个显示集 的本地化字符串。
        /// </summary>
        public static string MenuPreviousDisplaySet {
            get {
                return ResourceManager.GetString("MenuPreviousDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏 &amp;C色彩栏 的本地化字符串。
        /// </summary>
        public static string MenuShowHideColorBar {
            get {
                return ResourceManager.GetString("MenuShowHideColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏 DICOM 覆盖(s) 的本地化字符串。
        /// </summary>
        public static string MenuShowHideDicomOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏 比例覆盖 的本地化字符串。
        /// </summary>
        public static string MenuShowHideScaleOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏 快门覆盖 的本地化字符串。
        /// </summary>
        public static string MenuShowHideShutterOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏 文本覆盖 的本地化字符串。
        /// </summary>
        public static string MenuShowHideTextOverlay {
            get {
                return ResourceManager.GetString("MenuShowHideTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准 的本地化字符串。
        /// </summary>
        public static string MenuStandard {
            get {
                return ResourceManager.GetString("MenuStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载之前的检查时发生以下错误： 的本地化字符串。
        /// </summary>
        public static string MessageLoadPriorsErrorPrefix {
            get {
                return ResourceManager.GetString("MessageLoadPriorsErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对以前检查的搜索未成功完成, 因为至少有一个默认服务器无法访问。
        ///虽然可能有一些预先内容, 但请注意, 你可能正在处理一个不完整的病人病史。
        ///请注意, 只要这个问题仍然存在, 您将不会再次收到此问题的通知。 的本地化字符串。
        /// </summary>
        public static string MessagePriorsIncomplete {
            get {
                return ResourceManager.GetString("MessagePriorsIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对先前检查的搜索失败。 尝试重新打开检查报告或选择其他默认服务器。
        ///
        ///请注意, 只要这个问题仍然存在, 您将不会再次收到此问题的通知。 的本地化字符串。
        /// </summary>
        public static string MessageSearchForPriorsFailed {
            get {
                return ResourceManager.GetString("MessageSearchForPriorsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色彩栏 的本地化字符串。
        /// </summary>
        public static string NameColourBarOverlay {
            get {
                return ResourceManager.GetString("NameColourBarOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM 的本地化字符串。
        /// </summary>
        public static string NameDicomOverlay {
            get {
                return ResourceManager.GetString("NameDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比例 的本地化字符串。
        /// </summary>
        public static string NameScaleOverlay {
            get {
                return ResourceManager.GetString("NameScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快门 的本地化字符串。
        /// </summary>
        public static string NameShutterOverlay {
            get {
                return ResourceManager.GetString("NameShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本 的本地化字符串。
        /// </summary>
        public static string NameTextOverlay {
            get {
                return ResourceManager.GetString("NameTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 近线 的本地化字符串。
        /// </summary>
        public static string Nearline {
            get {
                return ResourceManager.GetString("Nearline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离线 的本地化字符串。
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示集 的本地化字符串。
        /// </summary>
        public static string TitleDisplaySetCreationConfiguration {
            get {
                return ResourceManager.GetString("TitleDisplaySetCreationConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局 的本地化字符串。
        /// </summary>
        public static string TitleLayoutConfiguration {
            get {
                return ResourceManager.GetString("TitleLayoutConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 布局管理器 的本地化字符串。
        /// </summary>
        public static string TitleLayoutManager {
            get {
                return ResourceManager.GetString("TitleLayoutManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改布局 的本地化字符串。
        /// </summary>
        public static string ToolbarChangeLayout {
            get {
                return ResourceManager.GetString("ToolbarChangeLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色彩栏 的本地化字符串。
        /// </summary>
        public static string ToolbarColorBar {
            get {
                return ResourceManager.GetString("ToolbarColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM 覆盖(s) 的本地化字符串。
        /// </summary>
        public static string ToolbarDicomOverlay {
            get {
                return ResourceManager.GetString("ToolbarDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量/分解 的本地化字符串。
        /// </summary>
        public static string ToolbarExplodeImageBox {
            get {
                return ResourceManager.GetString("ToolbarExplodeImageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像框布局 的本地化字符串。
        /// </summary>
        public static string ToolbarLayoutBoxesChooser {
            get {
                return ResourceManager.GetString("ToolbarLayoutBoxesChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁贴布局 的本地化字符串。
        /// </summary>
        public static string ToolbarLayoutTilesChooser {
            get {
                return ResourceManager.GetString("ToolbarLayoutTilesChooser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一个显示集 的本地化字符串。
        /// </summary>
        public static string ToolbarNextDisplaySet {
            get {
                return ResourceManager.GetString("ToolbarNextDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一个显示集 的本地化字符串。
        /// </summary>
        public static string ToolbarPreviousDisplaySet {
            get {
                return ResourceManager.GetString("ToolbarPreviousDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比例叠加 的本地化字符串。
        /// </summary>
        public static string ToolbarScaleOverlay {
            get {
                return ResourceManager.GetString("ToolbarScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏 覆盖 的本地化字符串。
        /// </summary>
        public static string ToolbarShowHideOverlays {
            get {
                return ResourceManager.GetString("ToolbarShowHideOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快门覆盖 的本地化字符串。
        /// </summary>
        public static string ToolbarShutterOverlay {
            get {
                return ResourceManager.GetString("ToolbarShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本覆盖 的本地化字符串。
        /// </summary>
        public static string ToolbarTextOverlay {
            get {
                return ResourceManager.GetString("ToolbarTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改布局 的本地化字符串。
        /// </summary>
        public static string TooltipChangeLayout {
            get {
                return ResourceManager.GetString("TooltipChangeLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 测量/分解 的本地化字符串。
        /// </summary>
        public static string TooltipExplodeImageBox {
            get {
                return ResourceManager.GetString("TooltipExplodeImageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏所有叠加 的本地化字符串。
        /// </summary>
        public static string TooltipHideOverlays {
            get {
                return ResourceManager.GetString("TooltipHideOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一个显示集 的本地化字符串。
        /// </summary>
        public static string TooltipNextDisplaySet {
            get {
                return ResourceManager.GetString("TooltipNextDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一个显示集 的本地化字符串。
        /// </summary>
        public static string TooltipPreviousDisplaySet {
            get {
                return ResourceManager.GetString("TooltipPreviousDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 比例叠加 的本地化字符串。
        /// </summary>
        public static string TooltipScaleOverlay {
            get {
                return ResourceManager.GetString("TooltipScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏 色彩栏 的本地化字符串。
        /// </summary>
        public static string TooltipShowHideColorBar {
            get {
                return ResourceManager.GetString("TooltipShowHideColorBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏 DICOM 覆盖(s) 的本地化字符串。
        /// </summary>
        public static string TooltipShowHideDicomOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideDicomOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏 覆盖 的本地化字符串。
        /// </summary>
        public static string TooltipShowHideOverlays {
            get {
                return ResourceManager.GetString("TooltipShowHideOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏 比例覆盖 的本地化字符串。
        /// </summary>
        public static string TooltipShowHideScaleOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideScaleOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏 快门覆盖 的本地化字符串。
        /// </summary>
        public static string TooltipShowHideShutterOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideShutterOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示/隐藏 文本覆盖 的本地化字符串。
        /// </summary>
        public static string TooltipShowHideTextOverlay {
            get {
                return ResourceManager.GetString("TooltipShowHideTextOverlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示所选叠加 的本地化字符串。
        /// </summary>
        public static string TooltipShowOverlays {
            get {
                return ResourceManager.GetString("TooltipShowOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法 的本地化字符串。
        /// </summary>
        public static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
    }
}
