//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using LinqConnect template.
// Code is generated on: 2019/1/3 20:13:02
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using Devart.Data.Linq;
using Devart.Data.Linq.Mapping;
using System;
using System.ComponentModel;

namespace ClearCanvas.ImageViewer.StudyManagement.Core.Storage
{

    [DatabaseAttribute(Name = "dicom_store")]
    [ProviderAttribute(typeof(Devart.Data.MySql.Linq.Provider.MySqlDataProvider))]
    public partial class DicomStoreDataContext : Devart.Data.Linq.DataContext
    {
        public static CompiledQueryCache compiledQueryCache = CompiledQueryCache.RegisterDataContext(typeof(DicomStoreDataContext));
        private static MappingSource mappingSource = new Devart.Data.Linq.Mapping.AttributeMappingSource();

        #region Extensibility Method Definitions

        partial void OnCreated();
        partial void OnSubmitError(Devart.Data.Linq.SubmitErrorEventArgs args);
        partial void InsertConfiguration(Configuration instance);
        partial void UpdateConfiguration(Configuration instance);
        partial void DeleteConfiguration(Configuration instance);
        partial void InsertDevice(Device instance);
        partial void UpdateDevice(Device instance);
        partial void DeleteDevice(Device instance);
        partial void InsertStudy(Study instance);
        partial void UpdateStudy(Study instance);
        partial void DeleteStudy(Study instance);
        partial void InsertWorkItem(WorkItem instance);
        partial void UpdateWorkItem(WorkItem instance);
        partial void DeleteWorkItem(WorkItem instance);
        partial void InsertWorkItemUid(WorkItemUid instance);
        partial void UpdateWorkItemUid(WorkItemUid instance);
        partial void DeleteWorkItemUid(WorkItemUid instance);

        #endregion

        public DicomStoreDataContext() :
        base(GetConnectionString("DicomStoreDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        public DicomStoreDataContext(MappingSource mappingSource) :
        base(GetConnectionString("DicomStoreDataContextConnectionString"), mappingSource)
        {
            OnCreated();
        }

        private static string GetConnectionString(string connectionStringName)
        {
            System.Configuration.ConnectionStringSettings connectionStringSettings = System.Configuration.ConfigurationManager.ConnectionStrings[connectionStringName];
            if (connectionStringSettings == null)
                throw new InvalidOperationException("Connection string \"" + connectionStringName + "\" could not be found in the configuration file.");
            return connectionStringSettings.ConnectionString;
        }

        public DicomStoreDataContext(string connection) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public DicomStoreDataContext(System.Data.IDbConnection connection) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public DicomStoreDataContext(string connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public DicomStoreDataContext(System.Data.IDbConnection connection, MappingSource mappingSource) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public Devart.Data.Linq.Table<Configuration> Configurations
        {
            get
            {
                return this.GetTable<Configuration>();
            }
        }

        public Devart.Data.Linq.Table<Device> Devices
        {
            get
            {
                return this.GetTable<Device>();
            }
        }

        public Devart.Data.Linq.Table<Study> Studies
        {
            get
            {
                return this.GetTable<Study>();
            }
        }

        public Devart.Data.Linq.Table<WorkItem> WorkItems
        {
            get
            {
                return this.GetTable<WorkItem>();
            }
        }

        public Devart.Data.Linq.Table<WorkItemUid> WorkItemUids
        {
            get
            {
                return this.GetTable<WorkItemUid>();
            }
        }
    }
}

namespace ClearCanvas.ImageViewer.StudyManagement.Core.Storage
{

    /// <summary>
    /// There are no comments for DicomStoreContext.Configuration in the schema.
    /// </summary>
    [Table(Name = @"dicom_store.configuration")]
    public partial class Configuration : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
#pragma warning disable 0649

        private long _Oid;

        private System.DateTime? _Version = DateTime.Now;

        private string _Name;

        private string _Value;
#pragma warning restore 0649

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnOidChanging(long value);
        partial void OnOidChanged();
        partial void OnVersionChanging(System.DateTime? value);
        partial void OnVersionChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        partial void OnValueChanging(string value);
        partial void OnValueChanged();
        #endregion

        public Configuration()
        {
            OnCreated();
        }


        /// <summary>
        /// There are no comments for Oid in the schema.
        /// </summary>
        [Column(Storage = "_Oid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "BIGINT(20) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public long Oid
        {
            get
            {
                return this._Oid;
            }
            set
            {
                if (this._Oid != value)
                {
                    this.OnOidChanging(value);
                    this.SendPropertyChanging("Oid");
                    this._Oid = value;
                    this.SendPropertyChanged("Oid");
                    this.OnOidChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Version in the schema.
        /// </summary>
        [Column(Storage = "_Version", DbType = "TIMESTAMP NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime? Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                if (this._Version != value)
                {
                    this.OnVersionChanging(value);
                    this.SendPropertyChanging("Version");
                    this._Version = value;
                    this.SendPropertyChanged("Version");
                    this.OnVersionChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        [Column(Storage = "_Name", CanBeNull = false, DbType = "VARCHAR(100) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if (this._Name != value)
                {
                    this.OnNameChanging(value);
                    this.SendPropertyChanging("Name");
                    this._Name = value;
                    this.SendPropertyChanged("Name");
                    this.OnNameChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Value in the schema.
        /// </summary>
        [Column(Storage = "_Value", DbType = "TEXT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                if (this._Value != value)
                {
                    this.OnValueChanging(value);
                    this.SendPropertyChanging("Value");
                    this._Value = value;
                    this.SendPropertyChanged("Value");
                    this.OnValueChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName)
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for DicomStoreContext.Device in the schema.
    /// </summary>
    [Table(Name = @"dicom_store.device")]
    public partial class Device : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
#pragma warning disable 0649

        private long _Oid;

        private System.DateTime? _Version = DateTime.Now;

        private string _Name;

        private string _Description;

        private string _Location;

        private string _AETitle;

        private string _HostName;

        private int _Port;

        private int? _StreamingHeaderPort;

        private int? _StreamingImagePort;

        private bool _IsPriorsServer;

        private string _ExtensionData;
#pragma warning restore 0649

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnOidChanging(long value);
        partial void OnOidChanged();
        partial void OnVersionChanging(System.DateTime? value);
        partial void OnVersionChanged();
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        partial void OnLocationChanging(string value);
        partial void OnLocationChanged();
        partial void OnAETitleChanging(string value);
        partial void OnAETitleChanged();
        partial void OnHostNameChanging(string value);
        partial void OnHostNameChanged();
        partial void OnPortChanging(int value);
        partial void OnPortChanged();
        partial void OnStreamingHeaderPortChanging(int? value);
        partial void OnStreamingHeaderPortChanged();
        partial void OnStreamingImagePortChanging(int? value);
        partial void OnStreamingImagePortChanged();
        partial void OnIsPriorsServerChanging(bool value);
        partial void OnIsPriorsServerChanged();
        partial void OnExtensionDataChanging(string value);
        partial void OnExtensionDataChanged();
        #endregion

        public Device()
        {
            OnCreated();
        }


        /// <summary>
        /// There are no comments for Oid in the schema.
        /// </summary>
        [Column(Storage = "_Oid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "BIGINT(20) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public long Oid
        {
            get
            {
                return this._Oid;
            }
            set
            {
                if (this._Oid != value)
                {
                    this.OnOidChanging(value);
                    this.SendPropertyChanging("Oid");
                    this._Oid = value;
                    this.SendPropertyChanged("Oid");
                    this.OnOidChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Version in the schema.
        /// </summary>
        [Column(Storage = "_Version", DbType = "TIMESTAMP NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime? Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                if (this._Version != value)
                {
                    this.OnVersionChanging(value);
                    this.SendPropertyChanging("Version");
                    this._Version = value;
                    this.SendPropertyChanged("Version");
                    this.OnVersionChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        [Column(Storage = "_Name", CanBeNull = false, DbType = "VARCHAR(64) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if (this._Name != value)
                {
                    this.OnNameChanging(value);
                    this.SendPropertyChanging("Name");
                    this._Name = value;
                    this.SendPropertyChanged("Name");
                    this.OnNameChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Description in the schema.
        /// </summary>
        [Column(Storage = "_Description", DbType = "VARCHAR(64) NULL", UpdateCheck = UpdateCheck.Never)]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if (this._Description != value)
                {
                    this.OnDescriptionChanging(value);
                    this.SendPropertyChanging("Description");
                    this._Description = value;
                    this.SendPropertyChanged("Description");
                    this.OnDescriptionChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Location in the schema.
        /// </summary>
        [Column(Storage = "_Location", DbType = "VARCHAR(64) NULL", UpdateCheck = UpdateCheck.Never)]
        public string Location
        {
            get
            {
                return this._Location;
            }
            set
            {
                if (this._Location != value)
                {
                    this.OnLocationChanging(value);
                    this.SendPropertyChanging("Location");
                    this._Location = value;
                    this.SendPropertyChanged("Location");
                    this.OnLocationChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for AETitle in the schema.
        /// </summary>
        [Column(Storage = "_AETitle", CanBeNull = false, DbType = "VARCHAR(64) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string AETitle
        {
            get
            {
                return this._AETitle;
            }
            set
            {
                if (this._AETitle != value)
                {
                    this.OnAETitleChanging(value);
                    this.SendPropertyChanging("AETitle");
                    this._AETitle = value;
                    this.SendPropertyChanged("AETitle");
                    this.OnAETitleChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for HostName in the schema.
        /// </summary>
        [Column(Storage = "_HostName", CanBeNull = false, DbType = "VARCHAR(64) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string HostName
        {
            get
            {
                return this._HostName;
            }
            set
            {
                if (this._HostName != value)
                {
                    this.OnHostNameChanging(value);
                    this.SendPropertyChanging("HostName");
                    this._HostName = value;
                    this.SendPropertyChanged("HostName");
                    this.OnHostNameChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Port in the schema.
        /// </summary>
        [Column(Storage = "_Port", CanBeNull = false, DbType = "INT(11) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public int Port
        {
            get
            {
                return this._Port;
            }
            set
            {
                if (this._Port != value)
                {
                    this.OnPortChanging(value);
                    this.SendPropertyChanging("Port");
                    this._Port = value;
                    this.SendPropertyChanged("Port");
                    this.OnPortChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for StreamingHeaderPort in the schema.
        /// </summary>
        [Column(Storage = "_StreamingHeaderPort", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public int? StreamingHeaderPort
        {
            get
            {
                return this._StreamingHeaderPort;
            }
            set
            {
                if (this._StreamingHeaderPort != value)
                {
                    this.OnStreamingHeaderPortChanging(value);
                    this.SendPropertyChanging("StreamingHeaderPort");
                    this._StreamingHeaderPort = value;
                    this.SendPropertyChanged("StreamingHeaderPort");
                    this.OnStreamingHeaderPortChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for StreamingImagePort in the schema.
        /// </summary>
        [Column(Storage = "_StreamingImagePort", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public int? StreamingImagePort
        {
            get
            {
                return this._StreamingImagePort;
            }
            set
            {
                if (this._StreamingImagePort != value)
                {
                    this.OnStreamingImagePortChanging(value);
                    this.SendPropertyChanging("StreamingImagePort");
                    this._StreamingImagePort = value;
                    this.SendPropertyChanged("StreamingImagePort");
                    this.OnStreamingImagePortChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for IsPriorsServer in the schema.
        /// </summary>
        [Column(Storage = "_IsPriorsServer", CanBeNull = false, DbType = "BIT NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public bool IsPriorsServer
        {
            get
            {
                return this._IsPriorsServer;
            }
            set
            {
                if (this._IsPriorsServer != value)
                {
                    this.OnIsPriorsServerChanging(value);
                    this.SendPropertyChanging("IsPriorsServer");
                    this._IsPriorsServer = value;
                    this.SendPropertyChanged("IsPriorsServer");
                    this.OnIsPriorsServerChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for ExtensionData in the schema.
        /// </summary>
        [Column(Storage = "_ExtensionData", DbType = "TEXT NULL", UpdateCheck = UpdateCheck.Never)]
        public string ExtensionData
        {
            get
            {
                return this._ExtensionData;
            }
            set
            {
                if (this._ExtensionData != value)
                {
                    this.OnExtensionDataChanging(value);
                    this.SendPropertyChanging("ExtensionData");
                    this._ExtensionData = value;
                    this.SendPropertyChanged("ExtensionData");
                    this.OnExtensionDataChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName)
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for DicomStoreContext.Study in the schema.
    /// </summary>
    [Table(Name = @"dicom_store.study")]
    public partial class Study : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
#pragma warning disable 0649

        private long _Oid;

        private System.DateTime? _Version;

        private string _SpecificCharacterSet;

        private string _StudyId;

        private long? _StudyTimeTicks;

        private string _StudyTimeRaw;

        private System.DateTime? _StudyDate;

        private string _StudyDateRaw;

        private string _AccessionNumber;

        private string _StudyInstanceUid;

        private string _StudyDescription;

        private string _ModalitiesInStudy;

        private string _SopClassesInStudy;

        private int? _NumberOfStudyRelatedSeries;

        private int? _NumberOfStudyRelatedInstances;

        private string _ProcedureCodeSequenceCodingSchemeDesignator;

        private string _ProcedureCodeSequenceCodeValue;

        private string _PatientsName;

        private string _ReferringPhysiciansName;

        private string _PatientId;

        private string _PatientsSex;

        private System.DateTime? _PatientsBirthDate;

        private string _PatientsBirthDateRaw;

        private long? _PatientsBirthTimeTicks;

        private string _PatientsBirthTimeRaw;

        private string _PatientSpeciesDescription;

        private string _PatientSpeciesCodeSequenceCodingSchemeDesignator;

        private string _PatientSpeciesCodeSequenceCodeValue;

        private string _PatientSpeciesCodeSequenceCodeMeaning;

        private string _PatientBreedDescription;

        private string _PatientBreedCodeSequenceCodingSchemeDesignator;

        private string _PatientBreedCodeSequenceCodeValue;

        private string _PatientBreedCodeSequenceCodeMeaning;

        private string _ResponsiblePerson;

        private string _ResponsiblePersonRole;

        private string _ResponsibleOrganization;

        private string _SourceAETitlesInStudy;

        private string _StationNamesInStudy;

        private string _InstitutionNamesInStudy;

        private System.DateTime? _StoreTime;

        private System.DateTime? _DeleteTime;

        private bool _Deleted;

        private bool _Reindex;
#pragma warning restore 0649

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnOidChanging(long value);
        partial void OnOidChanged();
        partial void OnVersionChanging(System.DateTime? value);
        partial void OnVersionChanged();
        partial void OnSpecificCharacterSetChanging(string value);
        partial void OnSpecificCharacterSetChanged();
        partial void OnStudyIdChanging(string value);
        partial void OnStudyIdChanged();
        partial void OnStudyTimeTicksChanging(long? value);
        partial void OnStudyTimeTicksChanged();
        partial void OnStudyTimeRawChanging(string value);
        partial void OnStudyTimeRawChanged();
        partial void OnStudyDateChanging(System.DateTime? value);
        partial void OnStudyDateChanged();
        partial void OnStudyDateRawChanging(string value);
        partial void OnStudyDateRawChanged();
        partial void OnAccessionNumberChanging(string value);
        partial void OnAccessionNumberChanged();
        partial void OnStudyInstanceUidChanging(string value);
        partial void OnStudyInstanceUidChanged();
        partial void OnStudyDescriptionChanging(string value);
        partial void OnStudyDescriptionChanged();
        partial void OnModalitiesInStudyChanging(string value);
        partial void OnModalitiesInStudyChanged();
        partial void OnSopClassesInStudyChanging(string value);
        partial void OnSopClassesInStudyChanged();
        partial void OnNumberOfStudyRelatedSeriesChanging(int? value);
        partial void OnNumberOfStudyRelatedSeriesChanged();
        partial void OnNumberOfStudyRelatedInstancesChanging(int? value);
        partial void OnNumberOfStudyRelatedInstancesChanged();
        partial void OnProcedureCodeSequenceCodingSchemeDesignatorChanging(string value);
        partial void OnProcedureCodeSequenceCodingSchemeDesignatorChanged();
        partial void OnProcedureCodeSequenceCodeValueChanging(string value);
        partial void OnProcedureCodeSequenceCodeValueChanged();
        partial void OnPatientsNameChanging(string value);
        partial void OnPatientsNameChanged();
        partial void OnReferringPhysiciansNameChanging(string value);
        partial void OnReferringPhysiciansNameChanged();
        partial void OnPatientIdChanging(string value);
        partial void OnPatientIdChanged();
        partial void OnPatientsSexChanging(string value);
        partial void OnPatientsSexChanged();
        partial void OnPatientsBirthDateChanging(System.DateTime? value);
        partial void OnPatientsBirthDateChanged();
        partial void OnPatientsBirthDateRawChanging(string value);
        partial void OnPatientsBirthDateRawChanged();
        partial void OnPatientsBirthTimeTicksChanging(long? value);
        partial void OnPatientsBirthTimeTicksChanged();
        partial void OnPatientsBirthTimeRawChanging(string value);
        partial void OnPatientsBirthTimeRawChanged();
        partial void OnPatientSpeciesDescriptionChanging(string value);
        partial void OnPatientSpeciesDescriptionChanged();
        partial void OnPatientSpeciesCodeSequenceCodingSchemeDesignatorChanging(string value);
        partial void OnPatientSpeciesCodeSequenceCodingSchemeDesignatorChanged();
        partial void OnPatientSpeciesCodeSequenceCodeValueChanging(string value);
        partial void OnPatientSpeciesCodeSequenceCodeValueChanged();
        partial void OnPatientSpeciesCodeSequenceCodeMeaningChanging(string value);
        partial void OnPatientSpeciesCodeSequenceCodeMeaningChanged();
        partial void OnPatientBreedDescriptionChanging(string value);
        partial void OnPatientBreedDescriptionChanged();
        partial void OnPatientBreedCodeSequenceCodingSchemeDesignatorChanging(string value);
        partial void OnPatientBreedCodeSequenceCodingSchemeDesignatorChanged();
        partial void OnPatientBreedCodeSequenceCodeValueChanging(string value);
        partial void OnPatientBreedCodeSequenceCodeValueChanged();
        partial void OnPatientBreedCodeSequenceCodeMeaningChanging(string value);
        partial void OnPatientBreedCodeSequenceCodeMeaningChanged();
        partial void OnResponsiblePersonChanging(string value);
        partial void OnResponsiblePersonChanged();
        partial void OnResponsiblePersonRoleChanging(string value);
        partial void OnResponsiblePersonRoleChanged();
        partial void OnResponsibleOrganizationChanging(string value);
        partial void OnResponsibleOrganizationChanged();
        partial void OnSourceAETitlesInStudyChanging(string value);
        partial void OnSourceAETitlesInStudyChanged();
        partial void OnStationNamesInStudyChanging(string value);
        partial void OnStationNamesInStudyChanged();
        partial void OnInstitutionNamesInStudyChanging(string value);
        partial void OnInstitutionNamesInStudyChanged();
        partial void OnStoreTimeChanging(System.DateTime? value);
        partial void OnStoreTimeChanged();
        partial void OnDeleteTimeChanging(System.DateTime? value);
        partial void OnDeleteTimeChanged();
        partial void OnDeletedChanging(bool value);
        partial void OnDeletedChanged();
        partial void OnReindexChanging(bool value);
        partial void OnReindexChanged();
        #endregion

        public Study()
        {
            OnCreated();
        }


        /// <summary>
        /// There are no comments for Oid in the schema.
        /// </summary>
        [Column(Storage = "_Oid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "BIGINT(20) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public long Oid
        {
            get
            {
                return this._Oid;
            }
            set
            {
                if (this._Oid != value)
                {
                    this.OnOidChanging(value);
                    this.SendPropertyChanging("Oid");
                    this._Oid = value;
                    this.SendPropertyChanged("Oid");
                    this.OnOidChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Version in the schema.
        /// </summary>
        [Column(Storage = "_Version", DbType = "TIMESTAMP NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime? Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                if (this._Version != value)
                {
                    this.OnVersionChanging(value);
                    this.SendPropertyChanging("Version");
                    this._Version = value;
                    this.SendPropertyChanged("Version");
                    this.OnVersionChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for SpecificCharacterSet in the schema.
        /// </summary>
        [Column(Storage = "_SpecificCharacterSet", DbType = "VARCHAR(64) NULL", UpdateCheck = UpdateCheck.Never)]
        public string SpecificCharacterSet
        {
            get
            {
                return this._SpecificCharacterSet;
            }
            set
            {
                if (this._SpecificCharacterSet != value)
                {
                    this.OnSpecificCharacterSetChanging(value);
                    this.SendPropertyChanging("SpecificCharacterSet");
                    this._SpecificCharacterSet = value;
                    this.SendPropertyChanged("SpecificCharacterSet");
                    this.OnSpecificCharacterSetChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for StudyId in the schema.
        /// </summary>
        [Column(Storage = "_StudyId", DbType = "VARCHAR(16) NULL", UpdateCheck = UpdateCheck.Never)]
        public string StudyId
        {
            get
            {
                return this._StudyId;
            }
            set
            {
                if (this._StudyId != value)
                {
                    this.OnStudyIdChanging(value);
                    this.SendPropertyChanging("StudyId");
                    this._StudyId = value;
                    this.SendPropertyChanged("StudyId");
                    this.OnStudyIdChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for StudyTimeTicks in the schema.
        /// </summary>
        [Column(Storage = "_StudyTimeTicks", DbType = "BIGINT(20) NULL", UpdateCheck = UpdateCheck.Never)]
        public long? StudyTimeTicks
        {
            get
            {
                return this._StudyTimeTicks;
            }
            set
            {
                if (this._StudyTimeTicks != value)
                {
                    this.OnStudyTimeTicksChanging(value);
                    this.SendPropertyChanging("StudyTimeTicks");
                    this._StudyTimeTicks = value;
                    this.SendPropertyChanged("StudyTimeTicks");
                    this.OnStudyTimeTicksChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for StudyTimeRaw in the schema.
        /// </summary>
        [Column(Storage = "_StudyTimeRaw", DbType = "VARCHAR(16) NULL", UpdateCheck = UpdateCheck.Never)]
        public string StudyTimeRaw
        {
            get
            {
                return this._StudyTimeRaw;
            }
            set
            {
                if (this._StudyTimeRaw != value)
                {
                    this.OnStudyTimeRawChanging(value);
                    this.SendPropertyChanging("StudyTimeRaw");
                    this._StudyTimeRaw = value;
                    this.SendPropertyChanged("StudyTimeRaw");
                    this.OnStudyTimeRawChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for StudyDate in the schema.
        /// </summary>
        [Column(Storage = "_StudyDate", DbType = "DATETIME NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime? StudyDate
        {
            get
            {
                return this._StudyDate;
            }
            set
            {
                if (this._StudyDate != value)
                {
                    this.OnStudyDateChanging(value);
                    this.SendPropertyChanging("StudyDate");
                    this._StudyDate = value;
                    this.SendPropertyChanged("StudyDate");
                    this.OnStudyDateChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for StudyDateRaw in the schema.
        /// </summary>
        [Column(Storage = "_StudyDateRaw", DbType = "VARCHAR(26) NULL", UpdateCheck = UpdateCheck.Never)]
        public string StudyDateRaw
        {
            get
            {
                return this._StudyDateRaw;
            }
            set
            {
                if (this._StudyDateRaw != value)
                {
                    this.OnStudyDateRawChanging(value);
                    this.SendPropertyChanging("StudyDateRaw");
                    this._StudyDateRaw = value;
                    this.SendPropertyChanged("StudyDateRaw");
                    this.OnStudyDateRawChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for AccessionNumber in the schema.
        /// </summary>
        [Column(Storage = "_AccessionNumber", DbType = "VARCHAR(16) NULL", UpdateCheck = UpdateCheck.Never)]
        public string AccessionNumber
        {
            get
            {
                return this._AccessionNumber;
            }
            set
            {
                if (this._AccessionNumber != value)
                {
                    this.OnAccessionNumberChanging(value);
                    this.SendPropertyChanging("AccessionNumber");
                    this._AccessionNumber = value;
                    this.SendPropertyChanged("AccessionNumber");
                    this.OnAccessionNumberChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for StudyInstanceUid in the schema.
        /// </summary>
        [Column(Storage = "_StudyInstanceUid", CanBeNull = false, DbType = "VARCHAR(64) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public string StudyInstanceUid
        {
            get
            {
                return this._StudyInstanceUid;
            }
            set
            {
                if (this._StudyInstanceUid != value)
                {
                    this.OnStudyInstanceUidChanging(value);
                    this.SendPropertyChanging("StudyInstanceUid");
                    this._StudyInstanceUid = value;
                    this.SendPropertyChanged("StudyInstanceUid");
                    this.OnStudyInstanceUidChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for StudyDescription in the schema.
        /// </summary>
        [Column(Storage = "_StudyDescription", DbType = "VARCHAR(64) NULL", UpdateCheck = UpdateCheck.Never)]
        public string StudyDescription
        {
            get
            {
                return this._StudyDescription;
            }
            set
            {
                if (this._StudyDescription != value)
                {
                    this.OnStudyDescriptionChanging(value);
                    this.SendPropertyChanging("StudyDescription");
                    this._StudyDescription = value;
                    this.SendPropertyChanged("StudyDescription");
                    this.OnStudyDescriptionChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for ModalitiesInStudy in the schema.
        /// </summary>
        [Column(Storage = "_ModalitiesInStudy", DbType = "VARCHAR(4000) NULL", UpdateCheck = UpdateCheck.Never)]
        public string ModalitiesInStudy
        {
            get
            {
                return this._ModalitiesInStudy;
            }
            set
            {
                if (this._ModalitiesInStudy != value)
                {
                    this.OnModalitiesInStudyChanging(value);
                    this.SendPropertyChanging("ModalitiesInStudy");
                    this._ModalitiesInStudy = value;
                    this.SendPropertyChanged("ModalitiesInStudy");
                    this.OnModalitiesInStudyChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for SopClassesInStudy in the schema.
        /// </summary>
        [Column(Storage = "_SopClassesInStudy", DbType = "VARCHAR(4000) NULL", UpdateCheck = UpdateCheck.Never)]
        public string SopClassesInStudy
        {
            get
            {
                return this._SopClassesInStudy;
            }
            set
            {
                if (this._SopClassesInStudy != value)
                {
                    this.OnSopClassesInStudyChanging(value);
                    this.SendPropertyChanging("SopClassesInStudy");
                    this._SopClassesInStudy = value;
                    this.SendPropertyChanged("SopClassesInStudy");
                    this.OnSopClassesInStudyChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for NumberOfStudyRelatedSeries in the schema.
        /// </summary>
        [Column(Storage = "_NumberOfStudyRelatedSeries", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public int? NumberOfStudyRelatedSeries
        {
            get
            {
                return this._NumberOfStudyRelatedSeries;
            }
            set
            {
                if (this._NumberOfStudyRelatedSeries != value)
                {
                    this.OnNumberOfStudyRelatedSeriesChanging(value);
                    this.SendPropertyChanging("NumberOfStudyRelatedSeries");
                    this._NumberOfStudyRelatedSeries = value;
                    this.SendPropertyChanged("NumberOfStudyRelatedSeries");
                    this.OnNumberOfStudyRelatedSeriesChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for NumberOfStudyRelatedInstances in the schema.
        /// </summary>
        [Column(Storage = "_NumberOfStudyRelatedInstances", DbType = "INT(11) NULL", UpdateCheck = UpdateCheck.Never)]
        public int? NumberOfStudyRelatedInstances
        {
            get
            {
                return this._NumberOfStudyRelatedInstances;
            }
            set
            {
                if (this._NumberOfStudyRelatedInstances != value)
                {
                    this.OnNumberOfStudyRelatedInstancesChanging(value);
                    this.SendPropertyChanging("NumberOfStudyRelatedInstances");
                    this._NumberOfStudyRelatedInstances = value;
                    this.SendPropertyChanged("NumberOfStudyRelatedInstances");
                    this.OnNumberOfStudyRelatedInstancesChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for ProcedureCodeSequenceCodingSchemeDesignator in the schema.
        /// </summary>
        [Column(Storage = "_ProcedureCodeSequenceCodingSchemeDesignator", DbType = "VARCHAR(16) NULL", UpdateCheck = UpdateCheck.Never)]
        public string ProcedureCodeSequenceCodingSchemeDesignator
        {
            get
            {
                return this._ProcedureCodeSequenceCodingSchemeDesignator;
            }
            set
            {
                if (this._ProcedureCodeSequenceCodingSchemeDesignator != value)
                {
                    this.OnProcedureCodeSequenceCodingSchemeDesignatorChanging(value);
                    this.SendPropertyChanging("ProcedureCodeSequenceCodingSchemeDesignator");
                    this._ProcedureCodeSequenceCodingSchemeDesignator = value;
                    this.SendPropertyChanged("ProcedureCodeSequenceCodingSchemeDesignator");
                    this.OnProcedureCodeSequenceCodingSchemeDesignatorChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for ProcedureCodeSequenceCodeValue in the schema.
        /// </summary>
        [Column(Storage = "_ProcedureCodeSequenceCodeValue", DbType = "VARCHAR(16) NULL", UpdateCheck = UpdateCheck.Never)]
        public string ProcedureCodeSequenceCodeValue
        {
            get
            {
                return this._ProcedureCodeSequenceCodeValue;
            }
            set
            {
                if (this._ProcedureCodeSequenceCodeValue != value)
                {
                    this.OnProcedureCodeSequenceCodeValueChanging(value);
                    this.SendPropertyChanging("ProcedureCodeSequenceCodeValue");
                    this._ProcedureCodeSequenceCodeValue = value;
                    this.SendPropertyChanged("ProcedureCodeSequenceCodeValue");
                    this.OnProcedureCodeSequenceCodeValueChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for PatientsName in the schema.
        /// </summary>
        [Column(Storage = "_PatientsName", DbType = "VARCHAR(256) NULL", UpdateCheck = UpdateCheck.Never)]
        public string PatientsName
        {
            get
            {
                return this._PatientsName;
            }
            set
            {
                if (this._PatientsName != value)
                {
                    this.OnPatientsNameChanging(value);
                    this.SendPropertyChanging("PatientsName");
                    this._PatientsName = value;
                    this.SendPropertyChanged("PatientsName");
                    this.OnPatientsNameChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for ReferringPhysiciansName in the schema.
        /// </summary>
        [Column(Storage = "_ReferringPhysiciansName", DbType = "VARCHAR(256) NULL", UpdateCheck = UpdateCheck.Never)]
        public string ReferringPhysiciansName
        {
            get
            {
                return this._ReferringPhysiciansName;
            }
            set
            {
                if (this._ReferringPhysiciansName != value)
                {
                    this.OnReferringPhysiciansNameChanging(value);
                    this.SendPropertyChanging("ReferringPhysiciansName");
                    this._ReferringPhysiciansName = value;
                    this.SendPropertyChanged("ReferringPhysiciansName");
                    this.OnReferringPhysiciansNameChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for PatientId in the schema.
        /// </summary>
        [Column(Storage = "_PatientId", DbType = "VARCHAR(64) NULL", UpdateCheck = UpdateCheck.Never)]
        public string PatientId
        {
            get
            {
                return this._PatientId;
            }
            set
            {
                if (this._PatientId != value)
                {
                    this.OnPatientIdChanging(value);
                    this.SendPropertyChanging("PatientId");
                    this._PatientId = value;
                    this.SendPropertyChanged("PatientId");
                    this.OnPatientIdChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for PatientsSex in the schema.
        /// </summary>
        [Column(Storage = "_PatientsSex", DbType = "VARCHAR(16) NULL", UpdateCheck = UpdateCheck.Never)]
        public string PatientsSex
        {
            get
            {
                return this._PatientsSex;
            }
            set
            {
                if (this._PatientsSex != value)
                {
                    this.OnPatientsSexChanging(value);
                    this.SendPropertyChanging("PatientsSex");
                    this._PatientsSex = value;
                    this.SendPropertyChanged("PatientsSex");
                    this.OnPatientsSexChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for PatientsBirthDate in the schema.
        /// </summary>
        [Column(Storage = "_PatientsBirthDate", DbType = "DATETIME NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime? PatientsBirthDate
        {
            get
            {
                return this._PatientsBirthDate;
            }
            set
            {
                if (this._PatientsBirthDate != value)
                {
                    this.OnPatientsBirthDateChanging(value);
                    this.SendPropertyChanging("PatientsBirthDate");
                    this._PatientsBirthDate = value;
                    this.SendPropertyChanged("PatientsBirthDate");
                    this.OnPatientsBirthDateChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for PatientsBirthDateRaw in the schema.
        /// </summary>
        [Column(Storage = "_PatientsBirthDateRaw", DbType = "VARCHAR(16) NULL", UpdateCheck = UpdateCheck.Never)]
        public string PatientsBirthDateRaw
        {
            get
            {
                return this._PatientsBirthDateRaw;
            }
            set
            {
                if (this._PatientsBirthDateRaw != value)
                {
                    this.OnPatientsBirthDateRawChanging(value);
                    this.SendPropertyChanging("PatientsBirthDateRaw");
                    this._PatientsBirthDateRaw = value;
                    this.SendPropertyChanged("PatientsBirthDateRaw");
                    this.OnPatientsBirthDateRawChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for PatientsBirthTimeTicks in the schema.
        /// </summary>
        [Column(Storage = "_PatientsBirthTimeTicks", DbType = "BIGINT(20) NULL", UpdateCheck = UpdateCheck.Never)]
        public long? PatientsBirthTimeTicks
        {
            get
            {
                return this._PatientsBirthTimeTicks;
            }
            set
            {
                if (this._PatientsBirthTimeTicks != value)
                {
                    this.OnPatientsBirthTimeTicksChanging(value);
                    this.SendPropertyChanging("PatientsBirthTimeTicks");
                    this._PatientsBirthTimeTicks = value;
                    this.SendPropertyChanged("PatientsBirthTimeTicks");
                    this.OnPatientsBirthTimeTicksChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for PatientsBirthTimeRaw in the schema.
        /// </summary>
        [Column(Storage = "_PatientsBirthTimeRaw", DbType = "VARCHAR(16) NULL", UpdateCheck = UpdateCheck.Never)]
        public string PatientsBirthTimeRaw
        {
            get
            {
                return this._PatientsBirthTimeRaw;
            }
            set
            {
                if (this._PatientsBirthTimeRaw != value)
                {
                    this.OnPatientsBirthTimeRawChanging(value);
                    this.SendPropertyChanging("PatientsBirthTimeRaw");
                    this._PatientsBirthTimeRaw = value;
                    this.SendPropertyChanged("PatientsBirthTimeRaw");
                    this.OnPatientsBirthTimeRawChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for PatientSpeciesDescription in the schema.
        /// </summary>
        [Column(Storage = "_PatientSpeciesDescription", DbType = "VARCHAR(64) NULL", UpdateCheck = UpdateCheck.Never)]
        public string PatientSpeciesDescription
        {
            get
            {
                return this._PatientSpeciesDescription;
            }
            set
            {
                if (this._PatientSpeciesDescription != value)
                {
                    this.OnPatientSpeciesDescriptionChanging(value);
                    this.SendPropertyChanging("PatientSpeciesDescription");
                    this._PatientSpeciesDescription = value;
                    this.SendPropertyChanged("PatientSpeciesDescription");
                    this.OnPatientSpeciesDescriptionChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for PatientSpeciesCodeSequenceCodingSchemeDesignator in the schema.
        /// </summary>
        [Column(Storage = "_PatientSpeciesCodeSequenceCodingSchemeDesignator", DbType = "VARCHAR(16) NULL", UpdateCheck = UpdateCheck.Never)]
        public string PatientSpeciesCodeSequenceCodingSchemeDesignator
        {
            get
            {
                return this._PatientSpeciesCodeSequenceCodingSchemeDesignator;
            }
            set
            {
                if (this._PatientSpeciesCodeSequenceCodingSchemeDesignator != value)
                {
                    this.OnPatientSpeciesCodeSequenceCodingSchemeDesignatorChanging(value);
                    this.SendPropertyChanging("PatientSpeciesCodeSequenceCodingSchemeDesignator");
                    this._PatientSpeciesCodeSequenceCodingSchemeDesignator = value;
                    this.SendPropertyChanged("PatientSpeciesCodeSequenceCodingSchemeDesignator");
                    this.OnPatientSpeciesCodeSequenceCodingSchemeDesignatorChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for PatientSpeciesCodeSequenceCodeValue in the schema.
        /// </summary>
        [Column(Storage = "_PatientSpeciesCodeSequenceCodeValue", DbType = "VARCHAR(16) NULL", UpdateCheck = UpdateCheck.Never)]
        public string PatientSpeciesCodeSequenceCodeValue
        {
            get
            {
                return this._PatientSpeciesCodeSequenceCodeValue;
            }
            set
            {
                if (this._PatientSpeciesCodeSequenceCodeValue != value)
                {
                    this.OnPatientSpeciesCodeSequenceCodeValueChanging(value);
                    this.SendPropertyChanging("PatientSpeciesCodeSequenceCodeValue");
                    this._PatientSpeciesCodeSequenceCodeValue = value;
                    this.SendPropertyChanged("PatientSpeciesCodeSequenceCodeValue");
                    this.OnPatientSpeciesCodeSequenceCodeValueChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for PatientSpeciesCodeSequenceCodeMeaning in the schema.
        /// </summary>
        [Column(Storage = "_PatientSpeciesCodeSequenceCodeMeaning", DbType = "VARCHAR(64) NULL", UpdateCheck = UpdateCheck.Never)]
        public string PatientSpeciesCodeSequenceCodeMeaning
        {
            get
            {
                return this._PatientSpeciesCodeSequenceCodeMeaning;
            }
            set
            {
                if (this._PatientSpeciesCodeSequenceCodeMeaning != value)
                {
                    this.OnPatientSpeciesCodeSequenceCodeMeaningChanging(value);
                    this.SendPropertyChanging("PatientSpeciesCodeSequenceCodeMeaning");
                    this._PatientSpeciesCodeSequenceCodeMeaning = value;
                    this.SendPropertyChanged("PatientSpeciesCodeSequenceCodeMeaning");
                    this.OnPatientSpeciesCodeSequenceCodeMeaningChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for PatientBreedDescription in the schema.
        /// </summary>
        [Column(Storage = "_PatientBreedDescription", DbType = "VARCHAR(64) NULL", UpdateCheck = UpdateCheck.Never)]
        public string PatientBreedDescription
        {
            get
            {
                return this._PatientBreedDescription;
            }
            set
            {
                if (this._PatientBreedDescription != value)
                {
                    this.OnPatientBreedDescriptionChanging(value);
                    this.SendPropertyChanging("PatientBreedDescription");
                    this._PatientBreedDescription = value;
                    this.SendPropertyChanged("PatientBreedDescription");
                    this.OnPatientBreedDescriptionChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for PatientBreedCodeSequenceCodingSchemeDesignator in the schema.
        /// </summary>
        [Column(Storage = "_PatientBreedCodeSequenceCodingSchemeDesignator", DbType = "VARCHAR(16) NULL", UpdateCheck = UpdateCheck.Never)]
        public string PatientBreedCodeSequenceCodingSchemeDesignator
        {
            get
            {
                return this._PatientBreedCodeSequenceCodingSchemeDesignator;
            }
            set
            {
                if (this._PatientBreedCodeSequenceCodingSchemeDesignator != value)
                {
                    this.OnPatientBreedCodeSequenceCodingSchemeDesignatorChanging(value);
                    this.SendPropertyChanging("PatientBreedCodeSequenceCodingSchemeDesignator");
                    this._PatientBreedCodeSequenceCodingSchemeDesignator = value;
                    this.SendPropertyChanged("PatientBreedCodeSequenceCodingSchemeDesignator");
                    this.OnPatientBreedCodeSequenceCodingSchemeDesignatorChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for PatientBreedCodeSequenceCodeValue in the schema.
        /// </summary>
        [Column(Storage = "_PatientBreedCodeSequenceCodeValue", DbType = "VARCHAR(16) NULL", UpdateCheck = UpdateCheck.Never)]
        public string PatientBreedCodeSequenceCodeValue
        {
            get
            {
                return this._PatientBreedCodeSequenceCodeValue;
            }
            set
            {
                if (this._PatientBreedCodeSequenceCodeValue != value)
                {
                    this.OnPatientBreedCodeSequenceCodeValueChanging(value);
                    this.SendPropertyChanging("PatientBreedCodeSequenceCodeValue");
                    this._PatientBreedCodeSequenceCodeValue = value;
                    this.SendPropertyChanged("PatientBreedCodeSequenceCodeValue");
                    this.OnPatientBreedCodeSequenceCodeValueChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for PatientBreedCodeSequenceCodeMeaning in the schema.
        /// </summary>
        [Column(Storage = "_PatientBreedCodeSequenceCodeMeaning", DbType = "VARCHAR(64) NULL", UpdateCheck = UpdateCheck.Never)]
        public string PatientBreedCodeSequenceCodeMeaning
        {
            get
            {
                return this._PatientBreedCodeSequenceCodeMeaning;
            }
            set
            {
                if (this._PatientBreedCodeSequenceCodeMeaning != value)
                {
                    this.OnPatientBreedCodeSequenceCodeMeaningChanging(value);
                    this.SendPropertyChanging("PatientBreedCodeSequenceCodeMeaning");
                    this._PatientBreedCodeSequenceCodeMeaning = value;
                    this.SendPropertyChanged("PatientBreedCodeSequenceCodeMeaning");
                    this.OnPatientBreedCodeSequenceCodeMeaningChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for ResponsiblePerson in the schema.
        /// </summary>
        [Column(Storage = "_ResponsiblePerson", DbType = "VARCHAR(256) NULL", UpdateCheck = UpdateCheck.Never)]
        public string ResponsiblePerson
        {
            get
            {
                return this._ResponsiblePerson;
            }
            set
            {
                if (this._ResponsiblePerson != value)
                {
                    this.OnResponsiblePersonChanging(value);
                    this.SendPropertyChanging("ResponsiblePerson");
                    this._ResponsiblePerson = value;
                    this.SendPropertyChanged("ResponsiblePerson");
                    this.OnResponsiblePersonChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for ResponsiblePersonRole in the schema.
        /// </summary>
        [Column(Storage = "_ResponsiblePersonRole", DbType = "VARCHAR(16) NULL", UpdateCheck = UpdateCheck.Never)]
        public string ResponsiblePersonRole
        {
            get
            {
                return this._ResponsiblePersonRole;
            }
            set
            {
                if (this._ResponsiblePersonRole != value)
                {
                    this.OnResponsiblePersonRoleChanging(value);
                    this.SendPropertyChanging("ResponsiblePersonRole");
                    this._ResponsiblePersonRole = value;
                    this.SendPropertyChanged("ResponsiblePersonRole");
                    this.OnResponsiblePersonRoleChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for ResponsibleOrganization in the schema.
        /// </summary>
        [Column(Storage = "_ResponsibleOrganization", DbType = "VARCHAR(64) NULL", UpdateCheck = UpdateCheck.Never)]
        public string ResponsibleOrganization
        {
            get
            {
                return this._ResponsibleOrganization;
            }
            set
            {
                if (this._ResponsibleOrganization != value)
                {
                    this.OnResponsibleOrganizationChanging(value);
                    this.SendPropertyChanging("ResponsibleOrganization");
                    this._ResponsibleOrganization = value;
                    this.SendPropertyChanged("ResponsibleOrganization");
                    this.OnResponsibleOrganizationChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for SourceAETitlesInStudy in the schema.
        /// </summary>
        [Column(Storage = "_SourceAETitlesInStudy", DbType = "VARCHAR(4000) NULL", UpdateCheck = UpdateCheck.Never)]
        public string SourceAETitlesInStudy
        {
            get
            {
                return this._SourceAETitlesInStudy;
            }
            set
            {
                if (this._SourceAETitlesInStudy != value)
                {
                    this.OnSourceAETitlesInStudyChanging(value);
                    this.SendPropertyChanging("SourceAETitlesInStudy");
                    this._SourceAETitlesInStudy = value;
                    this.SendPropertyChanged("SourceAETitlesInStudy");
                    this.OnSourceAETitlesInStudyChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for StationNamesInStudy in the schema.
        /// </summary>
        [Column(Storage = "_StationNamesInStudy", DbType = "VARCHAR(4000) NULL", UpdateCheck = UpdateCheck.Never)]
        public string StationNamesInStudy
        {
            get
            {
                return this._StationNamesInStudy;
            }
            set
            {
                if (this._StationNamesInStudy != value)
                {
                    this.OnStationNamesInStudyChanging(value);
                    this.SendPropertyChanging("StationNamesInStudy");
                    this._StationNamesInStudy = value;
                    this.SendPropertyChanged("StationNamesInStudy");
                    this.OnStationNamesInStudyChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for InstitutionNamesInStudy in the schema.
        /// </summary>
        [Column(Storage = "_InstitutionNamesInStudy", DbType = "VARCHAR(4000) NULL", UpdateCheck = UpdateCheck.Never)]
        public string InstitutionNamesInStudy
        {
            get
            {
                return this._InstitutionNamesInStudy;
            }
            set
            {
                if (this._InstitutionNamesInStudy != value)
                {
                    this.OnInstitutionNamesInStudyChanging(value);
                    this.SendPropertyChanging("InstitutionNamesInStudy");
                    this._InstitutionNamesInStudy = value;
                    this.SendPropertyChanged("InstitutionNamesInStudy");
                    this.OnInstitutionNamesInStudyChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for StoreTime in the schema.
        /// </summary>
        [Column(Storage = "_StoreTime", DbType = "DATETIME NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime? StoreTime
        {
            get
            {
                return this._StoreTime;
            }
            set
            {
                if (this._StoreTime != value)
                {
                    this.OnStoreTimeChanging(value);
                    this.SendPropertyChanging("StoreTime");
                    this._StoreTime = value;
                    this.SendPropertyChanged("StoreTime");
                    this.OnStoreTimeChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for DeleteTime in the schema.
        /// </summary>
        [Column(Storage = "_DeleteTime", DbType = "DATETIME NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime? DeleteTime
        {
            get
            {
                return this._DeleteTime;
            }
            set
            {
                if (this._DeleteTime != value)
                {
                    this.OnDeleteTimeChanging(value);
                    this.SendPropertyChanging("DeleteTime");
                    this._DeleteTime = value;
                    this.SendPropertyChanged("DeleteTime");
                    this.OnDeleteTimeChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Deleted in the schema.
        /// </summary>
        [Column(Storage = "_Deleted", CanBeNull = false, DbType = "BIT NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public bool Deleted
        {
            get
            {
                return this._Deleted;
            }
            set
            {
                if (this._Deleted != value)
                {
                    this.OnDeletedChanging(value);
                    this.SendPropertyChanging("Deleted");
                    this._Deleted = value;
                    this.SendPropertyChanged("Deleted");
                    this.OnDeletedChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Reindex in the schema.
        /// </summary>
        [Column(Storage = "_Reindex", CanBeNull = false, DbType = "BIT NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public bool Reindex
        {
            get
            {
                return this._Reindex;
            }
            set
            {
                if (this._Reindex != value)
                {
                    this.OnReindexChanging(value);
                    this.SendPropertyChanging("Reindex");
                    this._Reindex = value;
                    this.SendPropertyChanged("Reindex");
                    this.OnReindexChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName)
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

    /// <summary>
    /// There are no comments for DicomStoreContext.Workitem in the schema.
    /// </summary>
    [Table(Name = @"dicom_store.workitem")]
    public partial class WorkItem : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
#pragma warning disable 0649

        private long _Oid;

        private System.DateTime? _Version = DateTime.Now;

        private System.DateTime _ScheduledTime;

        private System.DateTime _ExpirationTime;

        private System.DateTime _DeleteTime;

        private System.DateTime _ProcessTime;

        private System.DateTime _RequestedTime;

        //private short _Status;
        private global::ClearCanvas.ImageViewer.Common.WorkItem.WorkItemStatusEnum _Status;

        //private short _Priority;
        private global::ClearCanvas.ImageViewer.Common.WorkItem.WorkItemPriorityEnum _Priority;

        private string _Type;


        private short _FailureCount;

        private string _StudyInstanceUid;

        private string _SerializedRequest;

        private string _SerializedProgress;
#pragma warning restore 0649

        private EntitySet<WorkItemUid> _Workitemuids;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnOidChanging(long value);
        partial void OnOidChanged();
        partial void OnVersionChanging(System.DateTime? value);
        partial void OnVersionChanged();
        partial void OnScheduledTimeChanging(System.DateTime? value);
        partial void OnScheduledTimeChanged();
        partial void OnExpirationTimeChanging(System.DateTime? value);
        partial void OnExpirationTimeChanged();
        partial void OnDeleteTimeChanging(System.DateTime? value);
        partial void OnDeleteTimeChanged();
        partial void OnProcessTimeChanging(System.DateTime? value);
        partial void OnProcessTimeChanged();
        partial void OnRequestedTimeChanging(System.DateTime? value);
        partial void OnRequestedTimeChanged();
        partial void OnStatusChanging(short? value);
        partial void OnStatusChanged();
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        partial void OnPriorityChanging(short? value);
        partial void OnPriorityChanged();
        partial void OnFailureCountChanging(short? value);
        partial void OnFailureCountChanged();
        partial void OnStudyInstanceUidChanging(string value);
        partial void OnStudyInstanceUidChanged();
        partial void OnSerializedRequestChanging(string value);
        partial void OnSerializedRequestChanged();
        partial void OnSerializedProgressChanging(string value);
        partial void OnSerializedProgressChanged();
        #endregion

        public WorkItem()
        {
            this._Workitemuids = new EntitySet<WorkItemUid>(new Action<WorkItemUid>(this.attach_Workitemuids), new Action<WorkItemUid>(this.detach_Workitemuids));
            OnCreated();
        }


        /// <summary>
        /// There are no comments for Oid in the schema.
        /// </summary>
        [Column(Storage = "_Oid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "BIGINT(20) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public long Oid
        {
            get
            {
                return this._Oid;
            }
            set
            {
                if (this._Oid != value)
                {
                    this.OnOidChanging(value);
                    this.SendPropertyChanging("Oid");
                    this._Oid = value;
                    this.SendPropertyChanged("Oid");
                    this.OnOidChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Version in the schema.
        /// </summary>
        [Column(Storage = "_Version", DbType = "TIMESTAMP NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime? Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                if (this._Version != value)
                {
                    this.OnVersionChanging(value);
                    this.SendPropertyChanging("Version");
                    this._Version = value;
                    this.SendPropertyChanged("Version");
                    this.OnVersionChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for ScheduledTime in the schema.
        /// </summary>
        [Column(Storage = "_ScheduledTime", DbType = "DATETIME NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime ScheduledTime
        {
            get
            {
                return this._ScheduledTime;
            }
            set
            {
                if (this._ScheduledTime != value)
                {
                    this.OnScheduledTimeChanging(value);
                    this.SendPropertyChanging("ScheduledTime");
                    this._ScheduledTime = value;
                    this.SendPropertyChanged("ScheduledTime");
                    this.OnScheduledTimeChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for ExpirationTime in the schema.
        /// </summary>
        [Column(Storage = "_ExpirationTime", DbType = "DATETIME NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime ExpirationTime
        {
            get
            {
                return this._ExpirationTime;
            }
            set
            {
                if (this._ExpirationTime != value)
                {
                    this.OnExpirationTimeChanging(value);
                    this.SendPropertyChanging("ExpirationTime");
                    this._ExpirationTime = value;
                    this.SendPropertyChanged("ExpirationTime");
                    this.OnExpirationTimeChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for DeleteTime in the schema.
        /// </summary>
        [Column(Storage = "_DeleteTime", DbType = "DATETIME NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime DeleteTime
        {
            get
            {
                return this._DeleteTime;
            }
            set
            {
                if (this._DeleteTime != value)
                {
                    this.OnDeleteTimeChanging(value);
                    this.SendPropertyChanging("DeleteTime");
                    this._DeleteTime = value;
                    this.SendPropertyChanged("DeleteTime");
                    this.OnDeleteTimeChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for ProcessTime in the schema.
        /// </summary>
        [Column(Storage = "_ProcessTime", DbType = "DATETIME NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime ProcessTime
        {
            get
            {
                return this._ProcessTime;
            }
            set
            {
                if (this._ProcessTime != value)
                {
                    this.OnProcessTimeChanging(value);
                    this.SendPropertyChanging("ProcessTime");
                    this._ProcessTime = value;
                    this.SendPropertyChanged("ProcessTime");
                    this.OnProcessTimeChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for RequestedTime in the schema.
        /// </summary>
        [Column(Storage = "_RequestedTime", DbType = "DATETIME NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime RequestedTime
        {
            get
            {
                return this._RequestedTime;
            }
            set
            {
                if (this._RequestedTime != value)
                {
                    this.OnRequestedTimeChanging(value);
                    this.SendPropertyChanging("RequestedTime");
                    this._RequestedTime = value;
                    this.SendPropertyChanged("RequestedTime");
                    this.OnRequestedTimeChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Status in the schema.
        /// </summary>
        [Column(Storage = "_Status", CanBeNull = false, DbType = "SMALLINT(6) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public global::ClearCanvas.ImageViewer.Common.WorkItem.WorkItemStatusEnum Status
        {
            get
            {
                return this._Status;
            }
            set
            {
                if ((this._Status != value))
                {
                    this.OnStatusChanging(Convert.ToInt16(value));
                    this.SendPropertyChanging();
                    this._Status = value;
                    this.SendPropertyChanged("Status");
                    this.OnStatusChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Type in the schema.
        /// </summary>
        [Column(Storage = "_Type", DbType = "VARCHAR(32) NULL", UpdateCheck = UpdateCheck.Never)]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                if (this._Type != value)
                {
                    this.OnTypeChanging(value);
                    this.SendPropertyChanging("Type");
                    this._Type = value;
                    this.SendPropertyChanged("Type");
                    this.OnTypeChanged();
                }
            }
        }



        /// <summary>
        /// There are no comments for Priority in the schema.
        /// </summary>
        [Column(Storage = "_Priority", CanBeNull = false, DbType = "SMALLINT(6) NOT NULL", UpdateCheck = UpdateCheck.Never)]
        public global::ClearCanvas.ImageViewer.Common.WorkItem.WorkItemPriorityEnum Priority
        {
            get
            {
                return this._Priority;
            }
            set
            {
                if (this._Priority != value)
                {
                    this.OnPriorityChanging(Convert.ToInt16(value));
                    this.SendPropertyChanging("Priority");
                    this._Priority = value;
                    this.SendPropertyChanged("Priority");
                    this.OnPriorityChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for FailureCount in the schema.
        /// </summary>
        [Column(Storage = "_FailureCount", DbType = "SMALLINT(6) NULL", UpdateCheck = UpdateCheck.Never)]
        public short FailureCount
        {
            get
            {
                return this._FailureCount;
            }
            set
            {
                if (this._FailureCount != value)
                {
                    this.OnFailureCountChanging(value);
                    this.SendPropertyChanging("FailureCount");
                    this._FailureCount = value;
                    this.SendPropertyChanged("FailureCount");
                    this.OnFailureCountChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for StudyInstanceUid in the schema.
        /// </summary>
        [Column(Storage = "_StudyInstanceUid", DbType = "VARCHAR(64) NULL", UpdateCheck = UpdateCheck.Never)]
        public string StudyInstanceUid
        {
            get
            {
                return this._StudyInstanceUid;
            }
            set
            {
                if (this._StudyInstanceUid != value)
                {
                    this.OnStudyInstanceUidChanging(value);
                    this.SendPropertyChanging("StudyInstanceUid");
                    this._StudyInstanceUid = value;
                    this.SendPropertyChanged("StudyInstanceUid");
                    this.OnStudyInstanceUidChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for SerializedRequest in the schema.
        /// </summary>
        [Column(Storage = "_SerializedRequest", DbType = "TEXT NULL", UpdateCheck = UpdateCheck.Never)]
        public string SerializedRequest
        {
            get
            {
                return this._SerializedRequest;
            }
            set
            {
                if (this._SerializedRequest != value)
                {
                    this.OnSerializedRequestChanging(value);
                    this.SendPropertyChanging("SerializedRequest");
                    this._SerializedRequest = value;
                    this.SendPropertyChanged("SerializedRequest");
                    this.OnSerializedRequestChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for SerializedProgress in the schema.
        /// </summary>
        [Column(Storage = "_SerializedProgress", DbType = "TEXT NULL", UpdateCheck = UpdateCheck.Never)]
        public string SerializedProgress
        {
            get
            {
                return this._SerializedProgress;
            }
            set
            {
                if (this._SerializedProgress != value)
                {
                    this.OnSerializedProgressChanging(value);
                    this.SendPropertyChanging("SerializedProgress");
                    this._SerializedProgress = value;
                    this.SendPropertyChanged("SerializedProgress");
                    this.OnSerializedProgressChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Workitemuids in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name = "Workitem_Workitemuid", Storage = "_Workitemuids", ThisKey = "Oid", OtherKey = "WorkItemOid", DeleteRule = "NO ACTION")]
        public EntitySet<WorkItemUid> WorkItemUids
        {
            get
            {
                return this._Workitemuids;
            }
            set
            {
                this._Workitemuids.Assign(value);
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName)
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }

        private void attach_Workitemuids(WorkItemUid entity)
        {
            this.SendPropertyChanging("Workitemuids");
            entity.WorkItem = this;
        }

        private void detach_Workitemuids(WorkItemUid entity)
        {
            this.SendPropertyChanging("Workitemuids");
            entity.WorkItem = null;
        }
    }

    /// <summary>
    /// There are no comments for DicomStoreContext.Workitemuid in the schema.
    /// </summary>
    [Table(Name = @"dicom_store.workitemuid")]
    public partial class WorkItemUid : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(System.String.Empty);
#pragma warning disable 0649

        private long _Oid;

        private System.DateTime? _Version = DateTime.Now;

        private long _WorkItemOid;

        private string _SeriesInstanceUid;

        private string _SopInstanceUid;

        private bool _Complete;

        private sbyte? _FailureCount;

        private bool _Failed;

        private string _File;
#pragma warning restore 0649

        private EntityRef<WorkItem> _Workitem;

        #region Extensibility Method Definitions

        partial void OnLoaded();
        partial void OnValidate(ChangeAction action);
        partial void OnCreated();
        partial void OnOidChanging(long value);
        partial void OnOidChanged();
        partial void OnVersionChanging(System.DateTime? value);
        partial void OnVersionChanged();
        partial void OnWorkItemOidChanging(long? value);
        partial void OnWorkItemOidChanged();
        partial void OnSeriesInstanceUidChanging(string value);
        partial void OnSeriesInstanceUidChanged();
        partial void OnSopInstanceUidChanging(string value);
        partial void OnSopInstanceUidChanged();
        partial void OnCompleteChanging(bool? value);
        partial void OnCompleteChanged();
        partial void OnFailureCountChanging(sbyte? value);
        partial void OnFailureCountChanged();
        partial void OnFailedChanging(bool? value);
        partial void OnFailedChanged();
        partial void OnFileChanging(string value);
        partial void OnFileChanged();
        #endregion

        public WorkItemUid()
        {
            this._Workitem = default(EntityRef<WorkItem>);
            OnCreated();
        }


        /// <summary>
        /// There are no comments for Oid in the schema.
        /// </summary>
        [Column(Storage = "_Oid", AutoSync = AutoSync.OnInsert, CanBeNull = false, DbType = "BIGINT(20) NOT NULL AUTO_INCREMENT", IsDbGenerated = true, IsPrimaryKey = true)]
        public long Oid
        {
            get
            {
                return this._Oid;
            }
            set
            {
                if (this._Oid != value)
                {
                    this.OnOidChanging(value);
                    this.SendPropertyChanging("Oid");
                    this._Oid = value;
                    this.SendPropertyChanged("Oid");
                    this.OnOidChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Version in the schema.
        /// </summary>
        [Column(Storage = "_Version", DbType = "TIMESTAMP NULL", UpdateCheck = UpdateCheck.Never)]
        public System.DateTime? Version
        {
            get
            {
                return this._Version;
            }
            set
            {
                if (this._Version != value)
                {
                    this.OnVersionChanging(value);
                    this.SendPropertyChanging("Version");
                    this._Version = value;
                    this.SendPropertyChanged("Version");
                    this.OnVersionChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for WorkItemOid in the schema.
        /// </summary>
        [Column(Storage = "_WorkItemOid", DbType = "BIGINT(20) NULL", UpdateCheck = UpdateCheck.Never)]
        public long WorkItemOid
        {
            get
            {
                return this._WorkItemOid;
            }
            set
            {
                if (this._WorkItemOid != value)
                {
                    if (this._Workitem.HasLoadedOrAssignedValue)
                    {
                        throw new ForeignKeyReferenceAlreadyHasValueException();
                    }

                    this.OnWorkItemOidChanging(value);
                    this.SendPropertyChanging("WorkItemOid");
                    this._WorkItemOid = value;
                    this.SendPropertyChanged("WorkItemOid");
                    this.OnWorkItemOidChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for SeriesInstanceUid in the schema.
        /// </summary>
        [Column(Storage = "_SeriesInstanceUid", DbType = "VARCHAR(64) NULL", UpdateCheck = UpdateCheck.Never)]
        public string SeriesInstanceUid
        {
            get
            {
                return this._SeriesInstanceUid;
            }
            set
            {
                if (this._SeriesInstanceUid != value)
                {
                    this.OnSeriesInstanceUidChanging(value);
                    this.SendPropertyChanging("SeriesInstanceUid");
                    this._SeriesInstanceUid = value;
                    this.SendPropertyChanged("SeriesInstanceUid");
                    this.OnSeriesInstanceUidChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for SopInstanceUid in the schema.
        /// </summary>
        [Column(Storage = "_SopInstanceUid", DbType = "VARCHAR(64) NULL", UpdateCheck = UpdateCheck.Never)]
        public string SopInstanceUid
        {
            get
            {
                return this._SopInstanceUid;
            }
            set
            {
                if (this._SopInstanceUid != value)
                {
                    this.OnSopInstanceUidChanging(value);
                    this.SendPropertyChanging("SopInstanceUid");
                    this._SopInstanceUid = value;
                    this.SendPropertyChanged("SopInstanceUid");
                    this.OnSopInstanceUidChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Complete in the schema.
        /// </summary>
        [Column(Storage = "_Complete", DbType = "BIT NULL", UpdateCheck = UpdateCheck.Never)]
        public bool Complete
        {
            get
            {
                return this._Complete;
            }
            set
            {
                if (this._Complete != value)
                {
                    this.OnCompleteChanging(value);
                    this.SendPropertyChanging("Complete");
                    this._Complete = value;
                    this.SendPropertyChanged("Complete");
                    this.OnCompleteChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for FailureCount in the schema.
        /// </summary>
        [Column(Storage = "_FailureCount", DbType = "TINYINT NULL", UpdateCheck = UpdateCheck.Never)]
        public sbyte? FailureCount
        {
            get
            {
                return this._FailureCount;
            }
            set
            {
                if (this._FailureCount != value)
                {
                    this.OnFailureCountChanging(value);
                    this.SendPropertyChanging("FailureCount");
                    this._FailureCount = value;
                    this.SendPropertyChanged("FailureCount");
                    this.OnFailureCountChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Failed in the schema.
        /// </summary>
        [Column(Storage = "_Failed", DbType = "BIT NULL", UpdateCheck = UpdateCheck.Never)]
        public bool Failed
        {
            get
            {
                return this._Failed;
            }
            set
            {
                if (this._Failed != value)
                {
                    this.OnFailedChanging(value);
                    this.SendPropertyChanging("Failed");
                    this._Failed = value;
                    this.SendPropertyChanged("Failed");
                    this.OnFailedChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for File in the schema.
        /// </summary>
        [Column(Storage = "_File", DbType = "VARCHAR(128) NULL", UpdateCheck = UpdateCheck.Never)]
        public string File
        {
            get
            {
                return this._File;
            }
            set
            {
                if (this._File != value)
                {
                    this.OnFileChanging(value);
                    this.SendPropertyChanging("File");
                    this._File = value;
                    this.SendPropertyChanged("File");
                    this.OnFileChanged();
                }
            }
        }


        /// <summary>
        /// There are no comments for Workitem in the schema.
        /// </summary>
        [Devart.Data.Linq.Mapping.Association(Name = "Workitem_Workitemuid", Storage = "_Workitem", ThisKey = "WorkItemOid", OtherKey = "Oid", IsForeignKey = true)]
        public WorkItem WorkItem
        {
            get
            {
                return this._Workitem.Entity;
            }
            set
            {
                WorkItem previousValue = this._Workitem.Entity;
                if ((previousValue != value) || (this._Workitem.HasLoadedOrAssignedValue == false))
                {
                    this.SendPropertyChanging("Workitem");
                    if (previousValue != null)
                    {
                        this._Workitem.Entity = null;
                        previousValue.WorkItemUids.Remove(this);
                    }
                    this._Workitem.Entity = value;
                    if (value != null)
                    {
                        this._WorkItemOid = value.Oid;
                        value.WorkItemUids.Add(this);
                    }
                    else
                    {
                        this._WorkItemOid = default(long);
                    }
                    this.SendPropertyChanged("Workitem");
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, emptyChangingEventArgs);
        }

        protected virtual void SendPropertyChanging(System.String propertyName)
        {
            var handler = this.PropertyChanging;
            if (handler != null)
                handler(this, new PropertyChangingEventArgs(propertyName));
        }

        protected virtual void SendPropertyChanged(System.String propertyName)
        {
            var handler = this.PropertyChanged;
            if (handler != null)
                handler(this, new PropertyChangedEventArgs(propertyName));
        }
    }

}
