//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.Utilities.DicomEditor {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.Utilities.DicomEditor.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 组元素 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingGroupElement {
            get {
                return ResourceManager.GetString("ColumnHeadingGroupElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 长度 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingLength {
            get {
                return ResourceManager.GetString("ColumnHeadingLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签名 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingTagName {
            get {
                return ResourceManager.GetString("ColumnHeadingTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingValue {
            get {
                return ResourceManager.GetString("ColumnHeadingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VR 的本地化字符串。
        /// </summary>
        internal static string ColumnHeadingVR {
            get {
                return ResourceManager.GetString("ColumnHeadingVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者 ^ 匿名者 的本地化字符串。
        /// </summary>
        internal static string DefaultAnonymousPatientName {
            get {
                return ResourceManager.GetString("DefaultAnonymousPatientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有文件 (*. *) 的本地化字符串。
        /// </summary>
        internal static string LabelAllFiles {
            get {
                return ResourceManager.GetString("LabelAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匿名 的本地化字符串。
        /// </summary>
        internal static string MenuAnonymizeStudy {
            get {
                return ResourceManager.GetString("MenuAnonymizeStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        internal static string MenuCreate {
            get {
                return ResourceManager.GetString("MenuCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string MenuDelete {
            get {
                return ResourceManager.GetString("MenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM 转存 的本地化字符串。
        /// </summary>
        internal static string MenuDicomDump {
            get {
                return ResourceManager.GetString("MenuDicomDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM 编辑 的本地化字符串。
        /// </summary>
        internal static string MenuDicomEditor {
            get {
                return ResourceManager.GetString("MenuDicomEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以后 的本地化字符串。
        /// </summary>
        internal static string MenuNext {
            get {
                return ResourceManager.GetString("MenuNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 先前 的本地化字符串。
        /// </summary>
        internal static string MenuPrevious {
            get {
                return ResourceManager.GetString("MenuPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速匿名 的本地化字符串。
        /// </summary>
        internal static string MenuQuickAnonymize {
            get {
                return ResourceManager.GetString("MenuQuickAnonymize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string MenuReplicate {
            get {
                return ResourceManager.GetString("MenuReplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还原 的本地化字符串。
        /// </summary>
        internal static string MenuRevert {
            get {
                return ResourceManager.GetString("MenuRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string MenuSave {
            get {
                return ResourceManager.GetString("MenuSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入编号必须介于0和16个字符之间。 的本地化字符串。
        /// </summary>
        internal static string MessageAccessionNumberInvalidLength {
            get {
                return ResourceManager.GetString("MessageAccessionNumberInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试图将检查匿名时出错。 请查看日志以了解更多详细信息。 的本地化字符串。
        /// </summary>
        internal static string MessageAnonymizeStudyFailed {
            get {
                return ResourceManager.GetString("MessageAnonymizeStudyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匿名研究.. 的本地化字符串。
        /// </summary>
        internal static string MessageAnonymizingStudy {
            get {
                return ResourceManager.GetString("MessageAnonymizingStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 由于已超过最大磁盘使用率, 因此无法匿名进行研究。 的本地化字符串。
        /// </summary>
        internal static string MessageCannotAnonymizeMaxDiskUsageExceeded {
            get {
                return ResourceManager.GetString("MessageCannotAnonymizeMaxDiskUsageExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您想匿名 * 除了这个文件的所有 * 加载的文件吗？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmAnonymizeAllFiles {
            get {
                return ResourceManager.GetString("MessageConfirmAnonymizeAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个或多个匿名文件是报告和/或其他文档。这些通常包含无法通过此工具完全清除的患者信息。确实要继续匿名化吗？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmAnonymizeOneOrMoreReportsAndAttachments {
            get {
                return ResourceManager.GetString("MessageConfirmAnonymizeOneOrMoreReportsAndAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匿名文件是报告或其他文档。这些通常包含无法通过此工具完全清除的患者信息。确实要继续匿名化吗？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmAnonymizeReportOrAttachment {
            get {
                return ResourceManager.GetString("MessageConfirmAnonymizeReportOrAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选定的标记将被删除。 确实要继续吗？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmDeleteSelectedTags {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteSelectedTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 除了选定的文件外, 是否要从 * 所有 * 其他加载的文件中删除选定的标记？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmDeleteSelectedTagsFromAllFiles {
            get {
                return ResourceManager.GetString("MessageConfirmDeleteSelectedTagsFromAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dicom 检查附带的报告和其他文档通常包含无法通过此工具完全清除的患者信息。确实要保留这些文件吗？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmKeepReportsAndAttachments {
            get {
                return ResourceManager.GetString("MessageConfirmKeepReportsAndAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选定的标记及其值将复制到 * 所有 * 加载的文件中。 确实要继续吗？
        ///
        ///注: 这不会自动保存文件。您仍然必须单击 &quot;保存&quot; 工具来保存文件。 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmReplicateTagsInAllFiles {
            get {
                return ResourceManager.GetString("MessageConfirmReplicateTagsInAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑将恢复到上次保存的状态。 确实要继续吗？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmRevert {
            get {
                return ResourceManager.GetString("MessageConfirmRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否要还原 * 除此文件之外的所有 * 加载的文件？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmRevertAllFiles {
            get {
                return ResourceManager.GetString("MessageConfirmRevertAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所做的更改将保存到 * 所有 * 加载的文件, 原始文件将被覆盖。 确实要继续吗？
        ///
        ///注: 如果在 &quot;检查筛选器&quot; 中打开了任何已编辑的文件, 则应将其关闭。否则, 编辑的值可能会显示不变。 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmSaveAllFiles {
            get {
                return ResourceManager.GetString("MessageConfirmSaveAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个或多个文件已被修改。是否要立即保存这些文件？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmSaveChangesBeforeClosing {
            get {
                return ResourceManager.GetString("MessageConfirmSaveChangesBeforeClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑的文件是一个报告和/或其他文档。如果您修改了任何患者信息, 此工具将无法修改文档以匹配您的更改。确实要继续吗？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmSaveReportOrAttachment {
            get {
                return ResourceManager.GetString("MessageConfirmSaveReportOrAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个或多个编辑的文件是报告和/或其他文档。如果您修改了任何患者信息, 此工具将无法修改文档以匹配您的更改。确实要继续吗？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmSaveReportsOrAttachments {
            get {
                return ResourceManager.GetString("MessageConfirmSaveReportsOrAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所做的更改将保存到加载的文件中, 原始文件将被覆盖。确实要继续吗？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmSaveSingleFile {
            get {
                return ResourceManager.GetString("MessageConfirmSaveSingleFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所做的更改将保存到加载的文件中, 原始文件将被覆盖。确实要继续吗？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmSaveSingleRemoteFile {
            get {
                return ResourceManager.GetString("MessageConfirmSaveSingleRemoteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在处理文件.. 的本地化字符串。
        /// </summary>
        internal static string MessageDumpProgressBar {
            get {
                return ResourceManager.GetString("MessageDumpProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存一个或多个选定文件时出错。 请检查日志, 以确保指定的文件是可访问的, 然后重试。 的本地化字符串。
        /// </summary>
        internal static string MessageErrorUpdatingSomeFiles {
            get {
                return ResourceManager.GetString("MessageErrorUpdatingSomeFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dicom 转储操作失败。 所选内容中的文件可能不是Dicom。 的本地化字符串。
        /// </summary>
        internal static string MessageFailedDump {
            get {
                return ResourceManager.GetString("MessageFailedDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的目标。不能直接保存到文件存储区。请保存到另一个目录, 然后从该位置导入文件。 的本地化字符串。
        /// </summary>
        internal static string MessageFileStoreNotValidSaveLocation {
            get {
                return ResourceManager.GetString("MessageFileStoreNotValidSaveLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dicom 转储操作失败。 所选路径不包含任何文件。 的本地化字符串。
        /// </summary>
        internal static string MessageNoFilesSelected {
            get {
                return ResourceManager.GetString("MessageNoFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未删除任何标记。 这通常是因为所选内容仅包含 &quot;序列项&quot;、&quot;序列分隔符项&quot; 和 &quot;无法删除的项&quot;。 的本地化字符串。
        /// </summary>
        internal static string MessageNoTagsWereDeleted {
            get {
                return ResourceManager.GetString("MessageNoTagsWereDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所选目录不是空的。任何文件名冲突的现有文件都将被覆盖。是否要继续？ 的本地化字符串。
        /// </summary>
        internal static string MessageOutputFolderNotEmptyConfirmOverwriteFiles {
            get {
                return ResourceManager.GetString("MessageOutputFolderNotEmptyConfirmOverwriteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者 id 不能是空的。 的本地化字符串。
        /// </summary>
        internal static string MessagePatientIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("MessagePatientIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者的名字不能为空。 的本地化字符串。
        /// </summary>
        internal static string MessagePatientsNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("MessagePatientsNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此工具仅在选择了 dicom 映像时有效。 的本地化字符串。
        /// </summary>
        internal static string MessagePleaseSelectAnImage {
            get {
                return ResourceManager.GetString("MessagePleaseSelectAnImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择目标文件夹。 的本地化字符串。
        /// </summary>
        internal static string MessageSelectDestinationFolder {
            get {
                return ResourceManager.GetString("MessageSelectDestinationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持复制序列和二进制属性。 的本地化字符串。
        /// </summary>
        internal static string MessageSequenceBinaryReplicationNotSupported {
            get {
                return ResourceManager.GetString("MessageSequenceBinaryReplicationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法创建标记。 请确保正确输入的值, 并且适合正在创建的标记。 的本地化字符串。
        /// </summary>
        internal static string MessageTagCannotBeCreated {
            get {
                return ResourceManager.GetString("MessageTagCannotBeCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源数据的格式不是 Dicom 编辑器可以理解的格式。 的本地化字符串。
        /// </summary>
        internal static string MessageUnknownDataSource {
            get {
                return ResourceManager.GetString("MessageUnknownDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该值不能为空。 的本地化字符串。
        /// </summary>
        internal static string MessageValueCannotBeEmpty {
            get {
                return ResourceManager.GetString("MessageValueCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该值与原始值冲突。 的本地化字符串。
        /// </summary>
        internal static string MessageValueConflictsWithOriginal {
            get {
                return ResourceManager.GetString("MessageValueConflictsWithOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匿名检查 的本地化字符串。
        /// </summary>
        internal static string TitleAnonymizeStudy {
            get {
                return ResourceManager.GetString("TitleAnonymizeStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建标签 的本地化字符串。
        /// </summary>
        internal static string TitleCreateTag {
            get {
                return ResourceManager.GetString("TitleCreateTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM 转存 的本地化字符串。
        /// </summary>
        internal static string TitleDicomDump {
            get {
                return ResourceManager.GetString("TitleDicomDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DICOM 编辑 的本地化字符串。
        /// </summary>
        internal static string TitleDicomEditor {
            get {
                return ResourceManager.GetString("TitleDicomEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速匿名 的本地化字符串。
        /// </summary>
        internal static string TitleQuickAnonymize {
            get {
                return ResourceManager.GetString("TitleQuickAnonymize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为 的本地化字符串。
        /// </summary>
        internal static string TitleSaveAs {
            get {
                return ResourceManager.GetString("TitleSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匿名 的本地化字符串。
        /// </summary>
        internal static string ToolbarAnonymizeStudy {
            get {
                return ResourceManager.GetString("ToolbarAnonymizeStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        internal static string ToolbarCreate {
            get {
                return ResourceManager.GetString("ToolbarCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string ToolbarDelete {
            get {
                return ResourceManager.GetString("ToolbarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 以后 的本地化字符串。
        /// </summary>
        internal static string ToolbarNext {
            get {
                return ResourceManager.GetString("ToolbarNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 先前 的本地化字符串。
        /// </summary>
        internal static string ToolbarPrevious {
            get {
                return ResourceManager.GetString("ToolbarPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速匿名 的本地化字符串。
        /// </summary>
        internal static string ToolbarQuickAnonymize {
            get {
                return ResourceManager.GetString("ToolbarQuickAnonymize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string ToolbarReplicate {
            get {
                return ResourceManager.GetString("ToolbarReplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 还原 的本地化字符串。
        /// </summary>
        internal static string ToolbarRevert {
            get {
                return ResourceManager.GetString("ToolbarRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string ToolbarSave {
            get {
                return ResourceManager.GetString("ToolbarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为 的本地化字符串。
        /// </summary>
        internal static string ToolbarSaveAs {
            get {
                return ResourceManager.GetString("ToolbarSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匿名选择的检查 的本地化字符串。
        /// </summary>
        internal static string TooltipAnonymizeStudy {
            get {
                return ResourceManager.GetString("TooltipAnonymizeStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建新标签 的本地化字符串。
        /// </summary>
        internal static string TooltipCreate {
            get {
                return ResourceManager.GetString("TooltipCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除标签 的本地化字符串。
        /// </summary>
        internal static string TooltipDelete {
            get {
                return ResourceManager.GetString("TooltipDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一张图片 的本地化字符串。
        /// </summary>
        internal static string TooltipNext {
            get {
                return ResourceManager.GetString("TooltipNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一张图片 的本地化字符串。
        /// </summary>
        internal static string TooltipPrevious {
            get {
                return ResourceManager.GetString("TooltipPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匿名所有加载的文件 的本地化字符串。
        /// </summary>
        internal static string TooltipQuickAnonymize {
            get {
                return ResourceManager.GetString("TooltipQuickAnonymize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将选定的标记复制到所有加载的文件 的本地化字符串。
        /// </summary>
        internal static string TooltipReplicate {
            get {
                return ResourceManager.GetString("TooltipReplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 恢复更改 的本地化字符串。
        /// </summary>
        internal static string TooltipRevert {
            get {
                return ResourceManager.GetString("TooltipRevert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存更改, 覆盖原始文件 的本地化字符串。
        /// </summary>
        internal static string TooltipSave {
            get {
                return ResourceManager.GetString("TooltipSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存更改另存为新文件 的本地化字符串。
        /// </summary>
        internal static string TooltipSaveAs {
            get {
                return ResourceManager.GetString("TooltipSaveAs", resourceCulture);
            }
        }
    }
}
