//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyManagementCoreStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class study
    {
        public long Oid { get; set; }
        public Nullable<System.DateTime> Version { get; set; }
        public string SpecificCharacterSet { get; set; }
        public string StudyId { get; set; }
        public Nullable<long> StudyTimeTicks { get; set; }
        public string StudyTimeRaw { get; set; }
        public Nullable<System.DateTime> StudyDate { get; set; }
        public string StudyDateRaw { get; set; }
        public string AccessionNumber { get; set; }
        public string StudyInstanceUid { get; set; }
        public string StudyDescription { get; set; }
        public string ModalitiesInStudy { get; set; }
        public string SopClassesInStudy { get; set; }
        public Nullable<int> NumberOfStudyRelatedSeries { get; set; }
        public Nullable<int> NumberOfStudyRelatedInstances { get; set; }
        public string ProcedureCodeSequenceCodingSchemeDesignator { get; set; }
        public string ProcedureCodeSequenceCodeValue { get; set; }
        public string PatientsName { get; set; }
        public string ReferringPhysiciansName { get; set; }
        public string PatientId { get; set; }
        public string PatientsSex { get; set; }
        public Nullable<System.DateTime> PatientsBirthDate { get; set; }
        public string PatientsBirthDateRaw { get; set; }
        public Nullable<long> PatientsBirthTimeTicks { get; set; }
        public string PatientsBirthTimeRaw { get; set; }
        public string PatientSpeciesDescription { get; set; }
        public string PatientSpeciesCodeSequenceCodingSchemeDesignator { get; set; }
        public string PatientSpeciesCodeSequenceCodeValue { get; set; }
        public string PatientSpeciesCodeSequenceCodeMeaning { get; set; }
        public string PatientBreedDescription { get; set; }
        public string PatientBreedCodeSequenceCodingSchemeDesignator { get; set; }
        public string PatientBreedCodeSequenceCodeValue { get; set; }
        public string PatientBreedCodeSequenceCodeMeaning { get; set; }
        public string ResponsiblePerson { get; set; }
        public string ResponsiblePersonRole { get; set; }
        public string ResponsibleOrganization { get; set; }
        public string SourceAETitlesInStudy { get; set; }
        public string StationNamesInStudy { get; set; }
        public string InstitutionNamesInStudy { get; set; }
        public Nullable<System.DateTime> StoreTime { get; set; }
        public Nullable<System.DateTime> DeleteTime { get; set; }
        public bool Deleted { get; set; }
        public bool Reindex { get; set; }
    }
}
