//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyManagementCoreStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class workitemuid
    {
        public long Oid { get; set; }
        public Nullable<System.DateTime> Version { get; set; }
        public Nullable<long> WorkItemOid { get; set; }
        public string SeriesInstanceUid { get; set; }
        public string SopInstanceUid { get; set; }
        public bool Complete { get; set; }
        public Nullable<sbyte> FailureCount { get; set; }
        public bool Failed { get; set; }
        public string File { get; set; }
    
        public virtual workitem workitem { get; set; }
    }
}
