//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Clipboard {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Clipboard.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 配置导出 的本地化字符串。
        /// </summary>
        internal static string ConfigureImageExport {
            get {
                return ResourceManager.GetString("ConfigureImageExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 avi 视频文件 的本地化字符串。
        /// </summary>
        internal static string DescriptionAvi {
            get {
                return ResourceManager.GetString("DescriptionAvi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位图图像格式 (bmp) 的本地化字符串。
        /// </summary>
        internal static string DescriptionBmp {
            get {
                return ResourceManager.GetString("DescriptionBmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图形交换格式 (gif) 的本地化字符串。
        /// </summary>
        internal static string DescriptionGif {
            get {
                return ResourceManager.GetString("DescriptionGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联合摄影专家组 (jpeg) 的本地化字符串。
        /// </summary>
        internal static string DescriptionJpg {
            get {
                return ResourceManager.GetString("DescriptionJpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 便携式网络图形 (png) 的本地化字符串。
        /// </summary>
        internal static string DescriptionPng {
            get {
                return ResourceManager.GetString("DescriptionPng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子集 (自定义) 的本地化字符串。
        /// </summary>
        internal static string DescriptionSubsetCustom {
            get {
                return ResourceManager.GetString("DescriptionSubsetCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 子集 (范围) 的本地化字符串。
        /// </summary>
        internal static string DescriptionSubsetRange {
            get {
                return ResourceManager.GetString("DescriptionSubsetRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标记的图像文件格式 (tiff) 的本地化字符串。
        /// </summary>
        internal static string DescriptionTiff {
            get {
                return ResourceManager.GetString("DescriptionTiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标文件 的本地化字符串。
        /// </summary>
        internal static string LabelExportFile {
            get {
                return ResourceManager.GetString("LabelExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标文件夹 的本地化字符串。
        /// </summary>
        internal static string LabelExportPath {
            get {
                return ResourceManager.GetString("LabelExportPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭(OFF) 的本地化字符串。
        /// </summary>
        internal static string LabelOff {
            get {
                return ResourceManager.GetString("LabelOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开启(ON) 的本地化字符串。
        /// </summary>
        internal static string LabelOn {
            get {
                return ResourceManager.GetString("LabelOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪贴板 的本地化字符串。
        /// </summary>
        internal static string MenuClipboard {
            get {
                return ResourceManager.GetString("MenuClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将显示集复制到剪贴板 的本地化字符串。
        /// </summary>
        internal static string MenuCopyDisplaySetToClipboard {
            get {
                return ResourceManager.GetString("MenuCopyDisplaySetToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将图像复制到剪贴板 的本地化字符串。
        /// </summary>
        internal static string MenuCopyImageToClipboard {
            get {
                return ResourceManager.GetString("MenuCopyImageToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将图像的范围复制到剪贴板 的本地化字符串。
        /// </summary>
        internal static string MenuCopySubsetToClipboard {
            get {
                return ResourceManager.GetString("MenuCopySubsetToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部删除 的本地化字符串。
        /// </summary>
        internal static string MenuDeleteAllClipboardItems {
            get {
                return ResourceManager.GetString("MenuDeleteAllClipboardItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除所选内容 的本地化字符串。
        /// </summary>
        internal static string MenuDeleteClipboardItem {
            get {
                return ResourceManager.GetString("MenuDeleteClipboardItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出到图像 的本地化字符串。
        /// </summary>
        internal static string MenuExportToImage {
            get {
                return ResourceManager.GetString("MenuExportToImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出到视频 的本地化字符串。
        /// </summary>
        internal static string MenuExportToVideo {
            get {
                return ResourceManager.GetString("MenuExportToVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪切板 的本地化字符串。
        /// </summary>
        internal static string MenuShowClipboard {
            get {
                return ResourceManager.GetString("MenuShowClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图 的本地化字符串。
        /// </summary>
        internal static string MenuView {
            get {
                return ResourceManager.GetString("MenuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已取消。 的本地化字符串。
        /// </summary>
        internal static string MessageCancelled {
            get {
                return ResourceManager.GetString("MessageCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未能将项目添加到剪贴板 的本地化字符串。
        /// </summary>
        internal static string MessageClipboardCopyFailed {
            get {
                return ResourceManager.GetString("MessageClipboardCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者id编号: {0}
        ///患者姓名: {1}
        ///检查日期: {2}
        ///检查说明: {3}
        ///会诊编号: {4}
        ///治疗方式: {5}
        ///文本叠加: {6} 的本地化字符串。
        /// </summary>
        internal static string MessageClipboardDescription {
            get {
                return ResourceManager.GetString("MessageClipboardDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}  - 图片＃{1}，第＃{2}帧 的本地化字符串。
        /// </summary>
        internal static string MessageClipboardNameMultiframeImage {
            get {
                return ResourceManager.GetString("MessageClipboardNameMultiframeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}-图像 # {1} 的本地化字符串。
        /// </summary>
        internal static string MessageClipboardNameSingleImage {
            get {
                return ResourceManager.GetString("MessageClipboardNameSingleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在创建视频.. 的本地化字符串。
        /// </summary>
        internal static string MessageCreatingVideo {
            get {
                return ResourceManager.GetString("MessageCreatingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自定义范围无效。 的本地化字符串。
        /// </summary>
        internal static string MessageCustomRangeInvalid {
            get {
                return ResourceManager.GetString("MessageCustomRangeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的目录不存在。 的本地化字符串。
        /// </summary>
        internal static string MessageDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("MessageDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示集必须有2个或更多要导出到视频的图像。 的本地化字符串。
        /// </summary>
        internal static string MessageDisplaySetTooFewImagesForVideo {
            get {
                return ResourceManager.GetString("MessageDisplaySetTooFewImagesForVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束值必须小于或等于起始值。 的本地化字符串。
        /// </summary>
        internal static string MessageEndValueLargerThanStart {
            get {
                return ResourceManager.GetString("MessageEndValueLargerThanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束值超出范围。 的本地化字符串。
        /// </summary>
        internal static string MessageEndValueOutOfRange {
            get {
                return ResourceManager.GetString("MessageEndValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试启动配置对话框时出错。 有关详细信息, 请查看日志。 的本地化字符串。
        /// </summary>
        internal static string MessageErrorLaunchingConfigurationComponent {
            get {
                return ResourceManager.GetString("MessageErrorLaunchingConfigurationComponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成。 的本地化字符串。
        /// </summary>
        internal static string MessageExportComplete {
            get {
                return ResourceManager.GetString("MessageExportComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出失败。 有关详细信息, 请查看日志。 的本地化字符串。
        /// </summary>
        internal static string MessageExportFailed {
            get {
                return ResourceManager.GetString("MessageExportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在导出图像.. 的本地化字符串。
        /// </summary>
        internal static string MessageExportingImages {
            get {
                return ResourceManager.GetString("MessageExportingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出到视频失败。 有关详细信息, 请参阅日志。 的本地化字符串。
        /// </summary>
        internal static string MessageExportToVideoFailed {
            get {
                return ResourceManager.GetString("MessageExportToVideoFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出{1}的帧＃{0} 的本地化字符串。
        /// </summary>
        internal static string MessageFormatExportingFrame {
            get {
                return ResourceManager.GetString("MessageFormatExportingFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另一个导出作业当前正在运行。 您必须等到它完成后才能导出更多的图像。 的本地化字符串。
        /// </summary>
        internal static string MessageImageExportStillRunning {
            get {
                return ResourceManager.GetString("MessageImageExportStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的文件路径无效。 的本地化字符串。
        /// </summary>
        internal static string MessageInvalidFilePath {
            get {
                return ResourceManager.GetString("MessageInvalidFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有安装可接受的视频编解码器。 的本地化字符串。
        /// </summary>
        internal static string MessageNoAcceptableCodecsInstalled {
            get {
                return ResourceManager.GetString("MessageNoAcceptableCodecsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N/A 的本地化字符串。
        /// </summary>
        internal static string MessageNotApplicable {
            get {
                return ResourceManager.GetString("MessageNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 间隔值无效。 的本地化字符串。
        /// </summary>
        internal static string MessageRangeIntervalInvalid {
            get {
                return ResourceManager.GetString("MessageRangeIntervalInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始值超出范围。 的本地化字符串。
        /// </summary>
        internal static string MessageStartValueOutOfRange {
            get {
                return ResourceManager.GetString("MessageStartValueOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至少有一个项目无法从剪贴板中删除, 因为它正在使用中。 的本地化字符串。
        /// </summary>
        internal static string MessageUnableToClearClipboardItems {
            get {
                return ResourceManager.GetString("MessageUnableToClearClipboardItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目前正在创建另一个视频。 您必须等到它完成后再创建另一个。 的本地化字符串。
        /// </summary>
        internal static string MessageVideoExportStillRunning {
            get {
                return ResourceManager.GetString("MessageVideoExportStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级选项 的本地化字符串。
        /// </summary>
        internal static string TitleAdvancedOptions {
            get {
                return ResourceManager.GetString("TitleAdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪贴板 的本地化字符串。
        /// </summary>
        internal static string TitleClipboard {
            get {
                return ResourceManager.GetString("TitleClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将图像复制到剪贴板 的本地化字符串。
        /// </summary>
        internal static string TitleCopySubsetToClipboard {
            get {
                return ResourceManager.GetString("TitleCopySubsetToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频创建中... 的本地化字符串。
        /// </summary>
        internal static string TitleCreatingVideo {
            get {
                return ResourceManager.GetString("TitleCreatingVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出图像 的本地化字符串。
        /// </summary>
        internal static string TitleExportImages {
            get {
                return ResourceManager.GetString("TitleExportImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像导出中... 的本地化字符串。
        /// </summary>
        internal static string TitleExportingImages {
            get {
                return ResourceManager.GetString("TitleExportingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出单个映像 的本地化字符串。
        /// </summary>
        internal static string TitleExportSingleImage {
            get {
                return ResourceManager.GetString("TitleExportSingleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出到视频 的本地化字符串。
        /// </summary>
        internal static string TitleExportToVideo {
            get {
                return ResourceManager.GetString("TitleExportToVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部删除 的本地化字符串。
        /// </summary>
        internal static string ToolbalDeleteAllClipboardItems {
            get {
                return ResourceManager.GetString("ToolbalDeleteAllClipboardItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部删除 的本地化字符串。
        /// </summary>
        internal static string ToolbarDeleteClipboardItem {
            get {
                return ResourceManager.GetString("ToolbarDeleteClipboardItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出到图像 的本地化字符串。
        /// </summary>
        internal static string ToolbarExportToImage {
            get {
                return ResourceManager.GetString("ToolbarExportToImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出到视频 的本地化字符串。
        /// </summary>
        internal static string ToolbarExportToVideo {
            get {
                return ResourceManager.GetString("ToolbarExportToVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 剪贴板 的本地化字符串。
        /// </summary>
        internal static string ToolbarShowClipboard {
            get {
                return ResourceManager.GetString("ToolbarShowClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部删除 的本地化字符串。
        /// </summary>
        internal static string TooltipDeleteAllClipboardItems {
            get {
                return ResourceManager.GetString("TooltipDeleteAllClipboardItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除所选内容 的本地化字符串。
        /// </summary>
        internal static string TooltipDeleteClipboardItem {
            get {
                return ResourceManager.GetString("TooltipDeleteClipboardItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出到图像 的本地化字符串。
        /// </summary>
        internal static string TooltipExportToImage {
            get {
                return ResourceManager.GetString("TooltipExportToImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出到视频 的本地化字符串。
        /// </summary>
        internal static string TooltipExportToVideo {
            get {
                return ResourceManager.GetString("TooltipExportToVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示剪贴板 的本地化字符串。
        /// </summary>
        internal static string TooltipShowClipboard {
            get {
                return ResourceManager.GetString("TooltipShowClipboard", resourceCulture);
            }
        }
    }
}
