//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Common {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Common.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 B 的本地化字符串。
        /// </summary>
        public static string LabelBytes {
            get {
                return ResourceManager.GetString("LabelBytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GB 的本地化字符串。
        /// </summary>
        public static string LabelGigabytes {
            get {
                return ResourceManager.GetString("LabelGigabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KB 的本地化字符串。
        /// </summary>
        public static string LabelKilobytes {
            get {
                return ResourceManager.GetString("LabelKilobytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MB 的本地化字符串。
        /// </summary>
        public static string LabelMegabytes {
            get {
                return ResourceManager.GetString("LabelMegabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PB 的本地化字符串。
        /// </summary>
        public static string LabelPetabytes {
            get {
                return ResourceManager.GetString("LabelPetabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TB 的本地化字符串。
        /// </summary>
        public static string LabelTerabytes {
            get {
                return ResourceManager.GetString("LabelTerabytes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地 的本地化字符串。
        /// </summary>
        public static string LocalServerName {
            get {
                return ResourceManager.GetString("LocalServerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活动监视器服务当前不可用。 的本地化字符串。
        /// </summary>
        public static string MessageActivityMonitorServiceUnavailable {
            get {
                return ResourceManager.GetString("MessageActivityMonitorServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法发送序列。如果此问题仍然存在, 请与系统管理员联系。 的本地化字符串。
        /// </summary>
        public static string MessageFailedToSendSeries {
            get {
                return ResourceManager.GetString("MessageFailedToSendSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法发送图像。如果此问题仍然存在, 请与系统管理员联系。 的本地化字符串。
        /// </summary>
        public static string MessageFailedToSendSops {
            get {
                return ResourceManager.GetString("MessageFailedToSendSops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法发送检查。如果此问题仍然存在, 请与系统管理员联系。 的本地化字符串。
        /// </summary>
        public static string MessageFailedToSendStudy {
            get {
                return ResourceManager.GetString("MessageFailedToSendStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法启动重新索引操作, 可能是因为当前正在运行冲突的操作。 如果此问题仍然存在, 请与系统管理员联系。 的本地化字符串。
        /// </summary>
        public static string MessageFailedToStartReindex {
            get {
                return ResourceManager.GetString("MessageFailedToStartReindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新索引状态未知 的本地化字符串。
        /// </summary>
        public static string MessageReindexStatusUnknown {
            get {
                return ResourceManager.GetString("MessageReindexStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;系统配置设置&quot; 提供程序不支持用户作用域范围内的设置。 的本地化字符串。
        /// </summary>
        public static string SystemConfigurationSettingsProviderUserSetting {
            get {
                return ResourceManager.GetString("SystemConfigurationSettingsProviderUserSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查后的回执/输入 的本地化字符串。
        /// </summary>
        public static string TimeOriginReceivedDate {
            get {
                return ResourceManager.GetString("TimeOriginReceivedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查后的日期/时间 的本地化字符串。
        /// </summary>
        public static string TimeOriginStudyDate {
            get {
                return ResourceManager.GetString("TimeOriginStudyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天(s) 的本地化字符串。
        /// </summary>
        public static string TimeUnitDays {
            get {
                return ResourceManager.GetString("TimeUnitDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小时(s) 的本地化字符串。
        /// </summary>
        public static string TimeUnitHours {
            get {
                return ResourceManager.GetString("TimeUnitHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分钟(s) 的本地化字符串。
        /// </summary>
        public static string TimeUnitMinutes {
            get {
                return ResourceManager.GetString("TimeUnitMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 周(s) 的本地化字符串。
        /// </summary>
        public static string TimeUnitWeeks {
            get {
                return ResourceManager.GetString("TimeUnitWeeks", resourceCulture);
            }
        }
    }
}
