//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Externals {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Externals.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 通过命令行启动 的本地化字符串。
        /// </summary>
        internal static string DescriptionCommandLineExternal {
            get {
                return ResourceManager.GetString("DescriptionCommandLineExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外部应用 的本地化字符串。
        /// </summary>
        internal static string ExternalApplications {
            get {
                return ResourceManager.GetString("ExternalApplications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 {0} 打开显示集 的本地化字符串。
        /// </summary>
        internal static string FormatOpenDisplaySetWith {
            get {
                return ResourceManager.GetString("FormatOpenDisplaySetWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用 {0} 打开图像 的本地化字符串。
        /// </summary>
        internal static string FormatOpenImageWith {
            get {
                return ResourceManager.GetString("FormatOpenImageWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 环境变量可以包括在其周围的变量的名称中。
        ///%符号(%) 字符 (例如,%path%)。
        ///在需要文字%字符的情况下, 可以使用序列%%。
        ///
        ///当外部文件系统上包含图像时，可以使用以下参数字段：
        ///* $FILENAME $ (例如, c:\filestore\image.dcm)
        ///* $DIRECTORY $ (例如, c:\filestore)
        ///* $FILENAMEONLY $ (例如, image.dcm)
        ///* $EXTENSIONONLY $ (例如, dcm)
        ///
        ///使用 $ggggeeee$从显示集中的第一个图像插入DICOM属性的值:
        ///* $00100010$ (患者姓名, 例如, smith ^ john)
        ///* $00200000D$(检查实例UID, 例如, 1.2.276.0.7230010.3.200.12)
        ///* $00280030$ (像素纵横比, 例如, 0.5 0.5)
        ///
        ///在需要文字 $ 字符的情况下, 可以使用字段 $$。 的本地化字符串。
        /// </summary>
        internal static string HelpCommandLineExternalArgumentFields {
            get {
                return ResourceManager.GetString("HelpCommandLineExternalArgumentFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;外部对象 的本地化字符串。
        /// </summary>
        internal static string MenuExternals {
            get {
                return ResourceManager.GetString("MenuExternals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 价值不能为空 的本地化字符串。
        /// </summary>
        internal static string MessageValueCannotBeEmpty {
            get {
                return ResourceManager.GetString("MessageValueCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新外部对象 的本地化字符串。
        /// </summary>
        internal static string StringNewExternal {
            get {
                return ResourceManager.GetString("StringNewExternal", resourceCulture);
            }
        }
    }
}
