//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.Utilities.StudyFilters {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.Utilities.StudyFilters.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加/删除列 的本地化字符串。
        /// </summary>
        internal static string AddRemoveColumns {
            get {
                return ResourceManager.GetString("AddRemoveColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 光盘媒体 的本地化字符串。
        /// </summary>
        internal static string CDRomMedia {
            get {
                return ResourceManager.GetString("CDRomMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 访问日期 的本地化字符串。
        /// </summary>
        internal static string DateAccessed {
            get {
                return ResourceManager.GetString("DateAccessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建日期 的本地化字符串。
        /// </summary>
        internal static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改日期 的本地化字符串。
        /// </summary>
        internal static string DateModified {
            get {
                return ResourceManager.GetString("DateModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目录 的本地化字符串。
        /// </summary>
        internal static string Directory {
            get {
                return ResourceManager.GetString("Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动器 的本地化字符串。
        /// </summary>
        internal static string Drive {
            get {
                return ResourceManager.GetString("Drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动器格式 的本地化字符串。
        /// </summary>
        internal static string DriveFormat {
            get {
                return ResourceManager.GetString("DriveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 驱动器类型 的本地化字符串。
        /// </summary>
        internal static string DriveType {
            get {
                return ResourceManager.GetString("DriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑过滤器 的本地化字符串。
        /// </summary>
        internal static string EditFilters {
            get {
                return ResourceManager.GetString("EditFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展 的本地化字符串。
        /// </summary>
        internal static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件名 的本地化字符串。
        /// </summary>
        internal static string Filename {
            get {
                return ResourceManager.GetString("Filename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小 的本地化字符串。
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固定媒体 的本地化字符串。
        /// </summary>
        internal static string FixedMedia {
            get {
                return ResourceManager.GetString("FixedMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {2} ({0:x4},{1:x4}) 的本地化字符串。
        /// </summary>
        internal static string FormatDicomTag {
            get {
                return ResourceManager.GetString("FormatDicomTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} #{1} 的本地化字符串。
        /// </summary>
        internal static string FormatRepeatingDicomTagName {
            get {
                return ResourceManager.GetString("FormatRepeatingDicomTagName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ({0:x4},{1:x4}) 的本地化字符串。
        /// </summary>
        internal static string FormatUnknownDicomTag {
            get {
                return ResourceManager.GetString("FormatUnknownDicomTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有文件 (*. *) 的本地化字符串。
        /// </summary>
        internal static string LabelAllFiles {
            get {
                return ResourceManager.GetString("LabelAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ({0} length={1}) 的本地化字符串。
        /// </summary>
        internal static string LabelBinaryTagValue {
            get {
                return ResourceManager.GetString("LabelBinaryTagValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string LabelNonExistentValue {
            get {
                return ResourceManager.GetString("LabelNonExistentValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (null) 的本地化字符串。
        /// </summary>
        internal static string LabelNullTagValue {
            get {
                return ResourceManager.GetString("LabelNullTagValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ({0} data) 的本地化字符串。
        /// </summary>
        internal static string LabelVRIncorrect {
            get {
                return ResourceManager.GetString("LabelVRIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (UN data) 的本地化字符串。
        /// </summary>
        internal static string LabelVRUnknown {
            get {
                return ResourceManager.GetString("LabelVRUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择 &amp;文件... 的本地化字符串。
        /// </summary>
        internal static string MenuAddFiles {
            get {
                return ResourceManager.GetString("MenuAddFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择一个文件夹..。 的本地化字符串。
        /// </summary>
        internal static string MenuAddFolders {
            get {
                return ResourceManager.GetString("MenuAddFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;清理过滤器 的本地化字符串。
        /// </summary>
        internal static string MenuClearFilters {
            get {
                return ResourceManager.GetString("MenuClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 &amp;匿名为 的本地化字符串。
        /// </summary>
        internal static string MenuExportAnonymized {
            get {
                return ResourceManager.GetString("MenuExportAnonymized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 &amp;复制到... 的本地化字符串。
        /// </summary>
        internal static string MenuExportCopy {
            get {
                return ResourceManager.GetString("MenuExportCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;在查看器中打开 的本地化字符串。
        /// </summary>
        internal static string MenuLaunchInViewer {
            get {
                return ResourceManager.GetString("MenuLaunchInViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在检查中打开 &amp;过滤器.... 的本地化字符串。
        /// </summary>
        internal static string MenuOpenInStudyFilters {
            get {
                return ResourceManager.GetString("MenuOpenInStudyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;删除项目 的本地化字符串。
        /// </summary>
        internal static string MenuRemoveItems {
            get {
                return ResourceManager.GetString("MenuRemoveItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 &amp;升序 的本地化字符串。
        /// </summary>
        internal static string MenuSortAscending {
            get {
                return ResourceManager.GetString("MenuSortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 &amp;从 A 到 Z 的本地化字符串。
        /// </summary>
        internal static string MenuSortAscendingLexically {
            get {
                return ResourceManager.GetString("MenuSortAscendingLexically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 &amp;增大排序 的本地化字符串。
        /// </summary>
        internal static string MenuSortAscendingNumerically {
            get {
                return ResourceManager.GetString("MenuSortAscendingNumerically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 &amp;升序 的本地化字符串。
        /// </summary>
        internal static string MenuSortAscendingSpatially {
            get {
                return ResourceManager.GetString("MenuSortAscendingSpatially", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 &amp;从最早到最新 的本地化字符串。
        /// </summary>
        internal static string MenuSortAscendingTemporally {
            get {
                return ResourceManager.GetString("MenuSortAscendingTemporally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 &amp;降序 的本地化字符串。
        /// </summary>
        internal static string MenuSortDescending {
            get {
                return ResourceManager.GetString("MenuSortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 &amp;从 Z 到 A 的本地化字符串。
        /// </summary>
        internal static string MenuSortDescendingLexically {
            get {
                return ResourceManager.GetString("MenuSortDescendingLexically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 &amp;递减 的本地化字符串。
        /// </summary>
        internal static string MenuSortDescendingNumerically {
            get {
                return ResourceManager.GetString("MenuSortDescendingNumerically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 &amp;降序 的本地化字符串。
        /// </summary>
        internal static string MenuSortDescendingSpatially {
            get {
                return ResourceManager.GetString("MenuSortDescendingSpatially", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 &amp;从最新到最早 的本地化字符串。
        /// </summary>
        internal static string MenuSortDescendingTemporally {
            get {
                return ResourceManager.GetString("MenuSortDescendingTemporally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查 &amp;过滤 的本地化字符串。
        /// </summary>
        internal static string MenuStudyFilters {
            get {
                return ResourceManager.GetString("MenuStudyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &amp;值过滤 的本地化字符串。
        /// </summary>
        internal static string MenuValueFilters {
            get {
                return ResourceManager.GetString("MenuValueFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您确定要清除所有过滤器吗？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmClearAllFilters {
            get {
                return ResourceManager.GetString("MessageConfirmClearAllFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存在与即将保存的文件同名的文件。
        ///
        ///是否要继续并覆盖所有冲突的文件？ 的本地化字符串。
        /// </summary>
        internal static string MessageConfirmOverwriteFiles {
            get {
                return ResourceManager.GetString("MessageConfirmOverwriteFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的 DICOM 文件: {0} 的本地化字符串。
        /// </summary>
        internal static string MessageDicomException {
            get {
                return ResourceManager.GetString("MessageDicomException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定的目录不存在。 的本地化字符串。
        /// </summary>
        internal static string MessageDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("MessageDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 {1} 的文件 {0} 的本地化字符串。
        /// </summary>
        internal static string MessageFormatExportingFiles {
            get {
                return ResourceManager.GetString("MessageFormatExportingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的路径或文件名: {0} 的本地化字符串。
        /// </summary>
        internal static string MessageInvalidPath {
            get {
                return ResourceManager.GetString("MessageInvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载中.... 的本地化字符串。
        /// </summary>
        internal static string MessageLoading {
            get {
                return ResourceManager.GetString("MessageLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须指定输出路径。 的本地化字符串。
        /// </summary>
        internal static string MessageOutputPathMustBeSpecified {
            get {
                return ResourceManager.GetString("MessageOutputPathMustBeSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者ID不能为空 的本地化字符串。
        /// </summary>
        internal static string MessagePatientIdCannotBeEmpty {
            get {
                return ResourceManager.GetString("MessagePatientIdCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者的名字不能为空。 的本地化字符串。
        /// </summary>
        internal static string MessagePatientNameCannotBeEmpty {
            get {
                return ResourceManager.GetString("MessagePatientNameCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要从其中递归添加文件的文件夹。 的本地化字符串。
        /// </summary>
        internal static string MessageSelectAddFilesFolder {
            get {
                return ResourceManager.GetString("MessageSelectAddFilesFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择要过滤的文件夹。 的本地化字符串。
        /// </summary>
        internal static string MessageSelectFolderToFilter {
            get {
                return ResourceManager.GetString("MessageSelectFolderToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择输出位置: 的本地化字符串。
        /// </summary>
        internal static string MessageSelectOutputLocation {
            get {
                return ResourceManager.GetString("MessageSelectOutputLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 网络媒体 的本地化字符串。
        /// </summary>
        internal static string NetworkMedia {
            get {
                return ResourceManager.GetString("NetworkMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        internal static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内存 的本地化字符串。
        /// </summary>
        internal static string RAM {
            get {
                return ResourceManager.GetString("RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可移动媒体 的本地化字符串。
        /// </summary>
        internal static string RemovableMedia {
            get {
                return ResourceManager.GetString("RemovableMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查过滤器 的本地化字符串。
        /// </summary>
        internal static string StudyFilters {
            get {
                return ResourceManager.GetString("StudyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加项目 的本地化字符串。
        /// </summary>
        internal static string ToolbarAddItems {
            get {
                return ResourceManager.GetString("ToolbarAddItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加/删除列 的本地化字符串。
        /// </summary>
        internal static string ToolbarAddRemoveColumns {
            get {
                return ResourceManager.GetString("ToolbarAddRemoveColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除过滤器 的本地化字符串。
        /// </summary>
        internal static string ToolbarClearFilters {
            get {
                return ResourceManager.GetString("ToolbarClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑过滤器 的本地化字符串。
        /// </summary>
        internal static string ToolbarEditFilters {
            get {
                return ResourceManager.GetString("ToolbarEditFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        internal static string ToolbarExport {
            get {
                return ResourceManager.GetString("ToolbarExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤器 的本地化字符串。
        /// </summary>
        internal static string ToolbarFilter {
            get {
                return ResourceManager.GetString("ToolbarFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤器已关闭 的本地化字符串。
        /// </summary>
        internal static string ToolbarFiltersAreOff {
            get {
                return ResourceManager.GetString("ToolbarFiltersAreOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤器已开启 的本地化字符串。
        /// </summary>
        internal static string ToolbarFiltersAreOn {
            get {
                return ResourceManager.GetString("ToolbarFiltersAreOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用查看器打开 的本地化字符串。
        /// </summary>
        internal static string ToolbarLaunchInViewer {
            get {
                return ResourceManager.GetString("ToolbarLaunchInViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除项目 的本地化字符串。
        /// </summary>
        internal static string ToolbarRemoveItems {
            get {
                return ResourceManager.GetString("ToolbarRemoveItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除所有列中的所有过滤器 的本地化字符串。
        /// </summary>
        internal static string TooltipClearFilters {
            get {
                return ResourceManager.GetString("TooltipClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该列表目前尚未过滤。单击此处重新启用过滤器。 的本地化字符串。
        /// </summary>
        internal static string TooltipFiltersAreOff {
            get {
                return ResourceManager.GetString("TooltipFiltersAreOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该列表目前已过滤。单击此处暂时禁用过滤器。 的本地化字符串。
        /// </summary>
        internal static string TooltipFiltersAreOn {
            get {
                return ResourceManager.GetString("TooltipFiltersAreOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在表中打开选定的DICOM文件以进行过滤 的本地化字符串。
        /// </summary>
        internal static string TooltipOpenInStudyFilters {
            get {
                return ResourceManager.GetString("TooltipOpenInStudyFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
