//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.StudyManagement {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.StudyManagement.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 活动描述 的本地化字符串。
        /// </summary>
        public static string ColumnActivityDescription {
            get {
                return ResourceManager.GetString("ColumnActivityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者 的本地化字符串。
        /// </summary>
        public static string ColumnPatient {
            get {
                return ResourceManager.GetString("ColumnPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先 的本地化字符串。
        /// </summary>
        public static string ColumnPriority {
            get {
                return ResourceManager.GetString("ColumnPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进展 的本地化字符串。
        /// </summary>
        public static string ColumnProgress {
            get {
                return ResourceManager.GetString("ColumnProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请求的时间 的本地化字符串。
        /// </summary>
        public static string ColumnRequestedTime {
            get {
                return ResourceManager.GetString("ColumnRequestedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计划的时间 的本地化字符串。
        /// </summary>
        public static string ColumnScheduledTime {
            get {
                return ResourceManager.GetString("ColumnScheduledTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string ColumnStatus {
            get {
                return ResourceManager.GetString("ColumnStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态细节 的本地化字符串。
        /// </summary>
        public static string ColumnStatusDescription {
            get {
                return ResourceManager.GetString("ColumnStatusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查 的本地化字符串。
        /// </summary>
        public static string ColumnStudy {
            get {
                return ResourceManager.GetString("ColumnStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁盘使用率高于最大值。工作站将无法导入DICOM文件或通过网络接收它们。你应该删除旧的研究腾出空间，或增加最大用量。 的本地化字符串。
        /// </summary>
        public static string DescriptionMaximumDiskUsageExceeded {
            get {
                return ResourceManager.GetString("DescriptionMaximumDiskUsageExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} of {1} ({2}%) 的本地化字符串。
        /// </summary>
        public static string DiskspaceTemplate {
            get {
                return ResourceManager.GetString("DiskspaceTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开活动监视器 的本地化字符串。
        /// </summary>
        public static string LinkOpenActivityMonitor {
            get {
                return ResourceManager.GetString("LinkOpenActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开存储配置 的本地化字符串。
        /// </summary>
        public static string LinkOpenStorageConfiguration {
            get {
                return ResourceManager.GetString("LinkOpenStorageConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活动监视器 的本地化字符串。
        /// </summary>
        public static string MenuActivityMonitor {
            get {
                return ResourceManager.GetString("MenuActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string MenuDeleteWorkItem {
            get {
                return ResourceManager.GetString("MenuDeleteWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新索引文件存储 的本地化字符串。
        /// </summary>
        public static string MenuReindex {
            get {
                return ResourceManager.GetString("MenuReindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启 的本地化字符串。
        /// </summary>
        public static string MenuRestartWorkItem {
            get {
                return ResourceManager.GetString("MenuRestartWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制作统计 的本地化字符串。
        /// </summary>
        public static string MenuStatWorkItem {
            get {
                return ResourceManager.GetString("MenuStatWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string MenuStopWorkItem {
            get {
                return ResourceManager.GetString("MenuStopWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消选定的工作项可能会导致部分研究数据，这可能会导致患者误诊。你确定要取消？ 的本地化字符串。
        /// </summary>
        public static string MessageConfirmCancelWorkItems {
            get {
                return ResourceManager.GetString("MessageConfirmCancelWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开所选图像。 的本地化字符串。
        /// </summary>
        public static string MessageFailedToOpenImages {
            get {
                return ResourceManager.GetString("MessageFailedToOpenImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法打开所选研究。 的本地化字符串。
        /// </summary>
        public static string MessageFailedToOpenStudy {
            get {
                return ResourceManager.GetString("MessageFailedToOpenStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法启动重新索引。 的本地化字符串。
        /// </summary>
        public static string MessageFailedToStartReindex {
            get {
                return ResourceManager.GetString("MessageFailedToStartReindex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前配置的文件存储目录不存在。 的本地化字符串。
        /// </summary>
        public static string MessageFilestoreDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("MessageFilestoreDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择的一些研究正在处理中。它们可能不完整或包含过时的信息。你还想继续吗？ 的本地化字符串。
        /// </summary>
        public static string MessageLoadStudiesBeingProcessed {
            get {
                return ResourceManager.GetString("MessageLoadStudiesBeingProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您选择的研究正在处理中。它可能不完整或包含过时的信息。你还想继续吗？ 的本地化字符串。
        /// </summary>
        public static string MessageLoadStudyBeingProcessed {
            get {
                return ResourceManager.GetString("MessageLoadStudyBeingProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须运行本地服务器才能完成此操作 的本地化字符串。
        /// </summary>
        public static string MessageLocalServerNotRunning {
            get {
                return ResourceManager.GetString("MessageLocalServerNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超出最大磁盘使用量 的本地化字符串。
        /// </summary>
        public static string MessageMaximumDiskUsageExceeded {
            get {
                return ResourceManager.GetString("MessageMaximumDiskUsageExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 失败. 的本地化字符串。
        /// </summary>
        public static string MessageNonStudyWorkItemFailed {
            get {
                return ResourceManager.GetString("MessageNonStudyWorkItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有1个失败的工作项目。 的本地化字符串。
        /// </summary>
        public static string MessageOneFailedWorkItem {
            get {
                return ResourceManager.GetString("MessageOneFailedWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理 {1} 中 {0} 项.... 的本地化字符串。
        /// </summary>
        public static string MessageProcessedItemsProgress {
            get {
                return ResourceManager.GetString("MessageProcessedItemsProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新索引操作已在进行中。 的本地化字符串。
        /// </summary>
        public static string MessageReindexInProgress {
            get {
                return ResourceManager.GetString("MessageReindexInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已经安排了重新索引。 的本地化字符串。
        /// </summary>
        public static string MessageReindexScheduled {
            get {
                return ResourceManager.GetString("MessageReindexScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须运行该服务才能启动重新索引。 的本地化字符串。
        /// </summary>
        public static string MessageReindexServiceNotRunning {
            get {
                return ResourceManager.GetString("MessageReindexServiceNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有{0}个失败的工作项。 的本地化字符串。
        /// </summary>
        public static string MessageTotalFailedWorkItems {
            get {
                return ResourceManager.GetString("MessageTotalFailedWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {1} [{2}，A＃：{3}]的{0}失败。 的本地化字符串。
        /// </summary>
        public static string MessageWorkItemFailed {
            get {
                return ResourceManager.GetString("MessageWorkItemFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (all) 的本地化字符串。
        /// </summary>
        public static string NoFilterItem {
            get {
                return ResourceManager.GetString("NoFilterItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活动 的本地化字符串。
        /// </summary>
        public static string StatusFilterValueActive {
            get {
                return ResourceManager.GetString("StatusFilterValueActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完成 的本地化字符串。
        /// </summary>
        public static string StatusFilterValueComplete {
            get {
                return ResourceManager.GetString("StatusFilterValueComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        public static string StatusFilterValueFailed {
            get {
                return ResourceManager.GetString("StatusFilterValueFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已停止 的本地化字符串。
        /// </summary>
        public static string StatusFilterValueStopped {
            get {
                return ResourceManager.GetString("StatusFilterValueStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活动监视器 的本地化字符串。
        /// </summary>
        public static string TitleActivityMonitor {
            get {
                return ResourceManager.GetString("TitleActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活动监视器 的本地化字符串。
        /// </summary>
        public static string TooltipActivityMonitor {
            get {
                return ResourceManager.GetString("TooltipActivityMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除所选工作项 的本地化字符串。
        /// </summary>
        public static string TooltipDeleteWorkItem {
            get {
                return ResourceManager.GetString("TooltipDeleteWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新启动选定的工作项 的本地化字符串。
        /// </summary>
        public static string TooltipRestartWorkItem {
            get {
                return ResourceManager.GetString("TooltipRestartWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将所选工作项的优先级提高到“Stat” 的本地化字符串。
        /// </summary>
        public static string TooltipStatWorkItem {
            get {
                return ResourceManager.GetString("TooltipStatWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止选定的工作项目 的本地化字符串。
        /// </summary>
        public static string TooltipStopWorkItem {
            get {
                return ResourceManager.GetString("TooltipStopWorkItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您无权打开活动监视器。 的本地化字符串。
        /// </summary>
        public static string WarningActivityMonitorPermission {
            get {
                return ResourceManager.GetString("WarningActivityMonitorPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已超出最大磁盘使用量。其他设备将无法将研究发送到工作站。 的本地化字符串。
        /// </summary>
        public static string WarningMaximumDiskUsageExceeded {
            get {
                return ResourceManager.GetString("WarningMaximumDiskUsageExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您无权启动重新索引。 的本地化字符串。
        /// </summary>
        public static string WarningReindexPermission {
            get {
                return ResourceManager.GetString("WarningReindexPermission", resourceCulture);
            }
        }
    }
}
