//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.9035
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string BoolNo {
            get {
                return ResourceManager.GetString("BoolNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string BoolYes {
            get {
                return ResourceManager.GetString("BoolYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更改 的本地化字符串。
        /// </summary>
        public static string CommandChange {
            get {
                return ResourceManager.GetString("CommandChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建多行图形 的本地化字符串。
        /// </summary>
        public static string CommandCreateMultilineGraphic {
            get {
                return ResourceManager.GetString("CommandCreateMultilineGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建矩形图形 的本地化字符串。
        /// </summary>
        public static string CommandCreateRectangleGraphic {
            get {
                return ResourceManager.GetString("CommandCreateRectangleGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建ROI图形 的本地化字符串。
        /// </summary>
        public static string CommandCreateROIGraphic {
            get {
                return ResourceManager.GetString("CommandCreateROIGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string CommandDelete {
            get {
                return ResourceManager.GetString("CommandDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑文本 的本地化字符串。
        /// </summary>
        public static string CommandEditText {
            get {
                return ResourceManager.GetString("CommandEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动 的本地化字符串。
        /// </summary>
        public static string CommandMove {
            get {
                return ResourceManager.GetString("CommandMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动控制点 的本地化字符串。
        /// </summary>
        public static string CommandMoveControlPoint {
            get {
                return ResourceManager.GetString("CommandMoveControlPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移动图形 的本地化字符串。
        /// </summary>
        public static string CommandMoveGraphic {
            get {
                return ResourceManager.GetString("CommandMoveGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调整 的本地化字符串。
        /// </summary>
        public static string CommandResize {
            get {
                return ResourceManager.GetString("CommandResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 伸展 的本地化字符串。
        /// </summary>
        public static string CommandStretch {
            get {
                return ResourceManager.GetString("CommandStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Blue 的本地化字符串。
        /// </summary>
        public static string DescriptionBlueColorMap {
            get {
                return ResourceManager.GetString("DescriptionBlueColorMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (无) 的本地化字符串。
        /// </summary>
        public static string DescriptionGrayscaleColorMap {
            get {
                return ResourceManager.GetString("DescriptionGrayscaleColorMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Green 的本地化字符串。
        /// </summary>
        public static string DescriptionGreenColorMap {
            get {
                return ResourceManager.GetString("DescriptionGreenColorMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 调色板颜色 的本地化字符串。
        /// </summary>
        public static string DescriptionPaletteColorMap {
            get {
                return ResourceManager.GetString("DescriptionPaletteColorMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当显示设置变得可见时，在显示集中预取图像数据。 的本地化字符串。
        /// </summary>
        public static string DescriptionPrefetchingStrategyVisibleDisplaySet {
            get {
                return ResourceManager.GetString("DescriptionPrefetchingStrategyVisibleDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 演示文稿 的本地化字符串。
        /// </summary>
        public static string DescriptionPresentationLut {
            get {
                return ResourceManager.GetString("DescriptionPresentationLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Red 的本地化字符串。
        /// </summary>
        public static string DescriptionRedColorMap {
            get {
                return ResourceManager.GetString("DescriptionRedColorMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/centimetre 的本地化字符串。
        /// </summary>
        public static string DescriptionUnits1cm {
            get {
                return ResourceManager.GetString("DescriptionUnits1cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 becquerels/millilitre 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsBqml {
            get {
                return ResourceManager.GetString("DescriptionUnitsBqml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平方厘米 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsCm2 {
            get {
                return ResourceManager.GetString("DescriptionUnitsCm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平方厘米/毫升 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsCm2ml {
            get {
                return ResourceManager.GetString("DescriptionUnitsCm2ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计数 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsCnts {
            get {
                return ResourceManager.GetString("DescriptionUnitsCnts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 counts/second 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsCps {
            get {
                return ResourceManager.GetString("DescriptionUnitsCps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 grams/millilitre 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsGml {
            get {
                return ResourceManager.GetString("DescriptionUnitsGml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hounsfield units 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsHU {
            get {
                return ResourceManager.GetString("DescriptionUnitsHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 milligrams/minute/millilitre 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsMgminml {
            get {
                return ResourceManager.GetString("DescriptionUnitsMgminml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 millilitre/grams 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsMlg {
            get {
                return ResourceManager.GetString("DescriptionUnitsMlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 millilitre/minute/grams 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsMlming {
            get {
                return ResourceManager.GetString("DescriptionUnitsMlming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 millilitre/minute/millilitre 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsMlminml {
            get {
                return ResourceManager.GetString("DescriptionUnitsMlminml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 millilitre/millilitre 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsMlml {
            get {
                return ResourceManager.GetString("DescriptionUnitsMlml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/1000 光学密度 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsOD {
            get {
                return ResourceManager.GetString("DescriptionUnitsOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 百分比 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsPcnt {
            get {
                return ResourceManager.GetString("DescriptionUnitsPcnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与计数成比例 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsPropcnts {
            get {
                return ResourceManager.GetString("DescriptionUnitsPropcnts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 与计数/秒成比例 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsPropcps {
            get {
                return ResourceManager.GetString("DescriptionUnitsPropcps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准偏差 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsStddev {
            get {
                return ResourceManager.GetString("DescriptionUnitsStddev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 micromoles/minute/millilitre 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsUmolminml {
            get {
                return ResourceManager.GetString("DescriptionUnitsUmolminml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 micromoles/millilitre 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsUmolml {
            get {
                return ResourceManager.GetString("DescriptionUnitsUmolml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string DescriptionUnitsUnspecified {
            get {
                return ResourceManager.GetString("DescriptionUnitsUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须修改其他鼠标工具分配（{0}）。 的本地化字符串。
        /// </summary>
        public static string ExceptionAdditionalMouseToolAssignmentsMustBeModified {
            get {
                return ResourceManager.GetString("ExceptionAdditionalMouseToolAssignmentsMustBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注释项没有显示名称: {0}。 的本地化字符串。
        /// </summary>
        public static string ExceptionFormatAnnotationItemHasNoDisplayName {
            get {
                return ResourceManager.GetString("ExceptionFormatAnnotationItemHasNoDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 非 win32 平台不支持 imagebufferwin32。 的本地化字符串。
        /// </summary>
        public static string ExceptionImageBufferWin32NotSupported {
            get {
                return ResourceManager.GetString("ExceptionImageBufferWin32NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像不是灰度。 的本地化字符串。
        /// </summary>
        public static string ExceptionImageIsNotGrayscale {
            get {
                return ResourceManager.GetString("ExceptionImageIsNotGrayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 像素数据无效（预期大小：{0}字节，实际大小：{1}字节）。 的本地化字符串。
        /// </summary>
        public static string ExceptionIncorrectPixelDataSize {
            get {
                return ResourceManager.GetString("ExceptionIncorrectPixelDataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的注释布局XML（{0}）。 的本地化字符串。
        /// </summary>
        public static string ExceptionInvalidAnnotationLayoutXml {
            get {
                return ResourceManager.GetString("ExceptionInvalidAnnotationLayoutXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无效的过滤注释布局XML（{0}）。 的本地化字符串。
        /// </summary>
        public static string ExceptionInvalidFilteredAnnotationLayoutXml {
            get {
                return ResourceManager.GetString("ExceptionInvalidFilteredAnnotationLayoutXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ({0}、{1}、{2}、{3}) 是无效的规范化矩形。 规范化的矩形坐标必须介于0.0 和1.0 之间, 右 &gt; 左, 下 &gt; 上角 &gt; 顶部。 的本地化字符串。
        /// </summary>
        public static string ExceptionInvalidNormalizedRectangle {
            get {
                return ResourceManager.GetString("ExceptionInvalidNormalizedRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ({0}、{1}、{2}、{3}) 是无效的父矩形。 父矩形必须是这样的, 所有坐标都是正数, 右 &gt; 左, 下 &gt; 上角 &gt; &quot;顶部&quot;。 的本地化字符串。
        /// </summary>
        public static string ExceptionInvalidParentRectangle {
            get {
                return ResourceManager.GetString("ExceptionInvalidParentRectangle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者ID 不能为空。 的本地化字符串。
        /// </summary>
        public static string ExceptionInvalidPatientID {
            get {
                return ResourceManager.GetString("ExceptionInvalidPatientID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旋转值必须为0、90、180或270。 的本地化字符串。
        /// </summary>
        public static string ExceptionInvalidRotationValue {
            get {
                return ResourceManager.GetString("ExceptionInvalidRotationValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 是无效的标准路径项。 的本地化字符串。
        /// </summary>
        public static string ExceptionInvalidStandardPathItem {
            get {
                return ResourceManager.GetString("ExceptionInvalidStandardPathItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 步幅不正确（正确步幅= {0}，计算步幅= {1}）。 的本地化字符串。
        /// </summary>
        public static string ExceptionInvalidStride {
            get {
                return ResourceManager.GetString("ExceptionInvalidStride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物理工作区的布局是非矩形的, 或者尚未设置。 的本地化字符串。
        /// </summary>
        public static string ExceptionLayoutIsNotRectangular {
            get {
                return ResourceManager.GetString("ExceptionLayoutIsNotRectangular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线性Luts没有可设置的数据。 的本地化字符串。
        /// </summary>
        public static string ExceptionLinearLutDataCannotBeSet {
            get {
                return ResourceManager.GetString("ExceptionLinearLutDataCannotBeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LUT索引超出范围（index = {0}）。 的本地化字符串。
        /// </summary>
        public static string ExceptionLUTIndexOutOfRange {
            get {
                return ResourceManager.GetString("ExceptionLUTIndexOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 先前LUT的输出范围与当前LUT的输入范围不匹配。 的本地化字符串。
        /// </summary>
        public static string ExceptionLUTInputOutputRange {
            get {
                return ResourceManager.GetString("ExceptionLUTInputOutputRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后一个LUT的输出范围不是8位。 的本地化字符串。
        /// </summary>
        public static string ExceptionLUTLastOutputRange {
            get {
                return ResourceManager.GetString("ExceptionLUTLastOutputRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小输入值大于或等于最大输入值。 的本地化字符串。
        /// </summary>
        public static string ExceptionLUTMinGreaterThanEqualToMax {
            get {
                return ResourceManager.GetString("ExceptionLUTMinGreaterThanEqualToMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法生成复合LUT，因为尚未添加LUT。 的本地化字符串。
        /// </summary>
        public static string ExceptionLUTNotAdded {
            get {
                return ResourceManager.GetString("ExceptionLUTNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大输出值不可设置。 的本地化字符串。
        /// </summary>
        public static string ExceptionMaximumOutputValueIsNotSettable {
            get {
                return ResourceManager.GetString("ExceptionMaximumOutputValueIsNotSettable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小输出值不可设置。 的本地化字符串。
        /// </summary>
        public static string ExceptionMinimumOutputValueIsNotSettable {
            get {
                return ResourceManager.GetString("ExceptionMinimumOutputValueIsNotSettable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尚未设置最小和最大输入值。 的本地化字符串。
        /// </summary>
        public static string ExceptionMinMaxInputValuesNotSet {
            get {
                return ResourceManager.GetString("ExceptionMinMaxInputValuesNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您必须覆盖SetMemento才能从先前的CreateMemento调用恢复状态。 的本地化字符串。
        /// </summary>
        public static string ExceptionMustOverrideSetMemento {
            get {
                return ResourceManager.GetString("ExceptionMustOverrideSetMemento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此磁贴所属的图像框应该是空的吗？ 的本地化字符串。
        /// </summary>
        public static string ExceptionNoDisplaySetAssociatedWithImageBoxTile {
            get {
                return ResourceManager.GetString("ExceptionNoDisplaySetAssociatedWithImageBoxTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁贴应该是空的吗？ 的本地化字符串。
        /// </summary>
        public static string ExceptionNoPresentationImageAssociatedWithTile {
            get {
                return ResourceManager.GetString("ExceptionNoPresentationImageAssociatedWithTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本序列中没有SOP。无法确定序列描述 的本地化字符串。
        /// </summary>
        public static string ExceptionNoSopsExistInSeries {
            get {
                return ResourceManager.GetString("ExceptionNoSopsExistInSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对象必须是Type Single。 的本地化字符串。
        /// </summary>
        public static string ExceptionObjectMustBeSingleType {
            get {
                return ResourceManager.GetString("ExceptionObjectMustBeSingleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sop实例验证失败。 的本地化字符串。
        /// </summary>
        public static string ExceptionSopInstanceValidationFailed {
            get {
                return ResourceManager.GetString("ExceptionSopInstanceValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对于撤消支持，StatefulGraphic子类必须实现IMemorable。 的本地化字符串。
        /// </summary>
        public static string ExceptionStatefulGraphicMustBeIMemorable {
            get {
                return ResourceManager.GetString("ExceptionStatefulGraphicMustBeIMemorable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} [C:{1:F2}% B:{2:F2}%] 的本地化字符串。
        /// </summary>
        public static string FormatAdjustableDataLutDescription {
            get {
                return ResourceManager.GetString("FormatAdjustableDataLutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:F1}° 的本地化字符串。
        /// </summary>
        public static string FormatAngleDegrees {
            get {
                return ResourceManager.GetString("FormatAngleDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}: {1} 的本地化字符串。
        /// </summary>
        public static string FormatAnnotationItem {
            get {
                return ResourceManager.GetString("FormatAnnotationItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域：{0:F1} pixels 的本地化字符串。
        /// </summary>
        public static string FormatAreaPixels {
            get {
                return ResourceManager.GetString("FormatAreaPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域：{0:F3} cm² 的本地化字符串。
        /// </summary>
        public static string FormatAreaSquareCm {
            get {
                return ResourceManager.GetString("FormatAreaSquareCm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域：{0:F1} mm² 的本地化字符串。
        /// </summary>
        public static string FormatAreaSquareMm {
            get {
                return ResourceManager.GetString("FormatAreaSquareMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 覆盖平面 ({0} # {1}, fr # {2}) 的本地化字符串。
        /// </summary>
        public static string FormatDefaultMultiFrameOverlayGraphicName {
            get {
                return ResourceManager.GetString("FormatDefaultMultiFrameOverlayGraphicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 覆盖平面 ({0} # {1}) 的本地化字符串。
        /// </summary>
        public static string FormatDefaultSingleFrameOverlayGraphicName {
            get {
                return ResourceManager.GetString("FormatDefaultSingleFrameOverlayGraphicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口W:{0:0.#} 级别:{1:0.#}  的本地化字符串。
        /// </summary>
        public static string FormatDescriptionBasicLinearLut {
            get {
                return ResourceManager.GetString("FormatDescriptionBasicLinearLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口:{0:0.#} 级别:{1:0.#} (Identity) 的本地化字符串。
        /// </summary>
        public static string FormatDescriptionIdentityVoiLinearLut {
            get {
                return ResourceManager.GetString("FormatDescriptionIdentityVoiLinearLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口:{0:0.#} 级别:{1:0.#} (Min/Max) 的本地化字符串。
        /// </summary>
        public static string FormatDescriptionMinMaxCalculatedLinearLut {
            get {
                return ResourceManager.GetString("FormatDescriptionMinMaxCalculatedLinearLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] 所有图像 的本地化字符串。
        /// </summary>
        public static string FormatDescriptionModalityDisplaySet {
            get {
                return ResourceManager.GetString("FormatDescriptionModalityDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 坡度: {0:f2} int.: {1: f2} 的本地化字符串。
        /// </summary>
        public static string FormatDescriptionModalityLutLinear {
            get {
                return ResourceManager.GetString("FormatDescriptionModalityLutLinear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口W:{0:0.#} 级别:{1:0.#} ({2}) 的本地化字符串。
        /// </summary>
        public static string FormatDescriptionNamedLinearLut {
            get {
                return ResourceManager.GetString("FormatDescriptionNamedLinearLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 窗口:{0:0.#} 级别:{1:0.#} ({2}) 的本地化字符串。
        /// </summary>
        public static string FormatDescriptionPresentationStateLinearLut {
            get {
                return ResourceManager.GetString("FormatDescriptionPresentationStateLinearLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因: {0} 的本地化字符串。
        /// </summary>
        public static string FormatExceptionReason {
            get {
                return ResourceManager.GetString("FormatExceptionReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:F2} cm 的本地化字符串。
        /// </summary>
        public static string FormatLengthCm {
            get {
                return ResourceManager.GetString("FormatLengthCm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:F1} mm 的本地化字符串。
        /// </summary>
        public static string FormatLengthMm {
            get {
                return ResourceManager.GetString("FormatLengthMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0:F1} pixels 的本地化字符串。
        /// </summary>
        public static string FormatLengthPixels {
            get {
                return ResourceManager.GetString("FormatLengthPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意思是：{0} 的本地化字符串。
        /// </summary>
        public static string FormatMean {
            get {
                return ResourceManager.GetString("FormatMean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} : {1} 的本地化字符串。
        /// </summary>
        public static string FormatMouseButtonShortcutDescription {
            get {
                return ResourceManager.GetString("FormatMouseButtonShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标工具没有快捷方式分配 ({0})。 无法激活该工具。 的本地化字符串。
        /// </summary>
        public static string FormatMouseToolHasNoAssignment {
            get {
                return ResourceManager.GetString("FormatMouseToolHasNoAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鼠标工具的快捷方式分配无效 ({0})。 的本地化字符串。
        /// </summary>
        public static string FormatMouseToolInvalidAssignment {
            get {
                return ResourceManager.GetString("FormatMouseToolInvalidAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 滚轮: {0} 的本地化字符串。
        /// </summary>
        public static string FormatMouseWheelShortcutDescription {
            get {
                return ResourceManager.GetString("FormatMouseWheelShortcutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [{0}] 所有图像 的本地化字符串。
        /// </summary>
        public static string FormatNameModalityDisplaySet {
            get {
                return ResourceManager.GetString("FormatNameModalityDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原因: {0} 的本地化字符串。
        /// </summary>
        public static string FormatReason {
            get {
                return ResourceManager.GetString("FormatReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标准偏差: {0} 的本地化字符串。
        /// </summary>
        public static string FormatStdDev {
            get {
                return ResourceManager.GetString("FormatStdDev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误： 的本地化字符串。
        /// </summary>
        public static string LabelError {
            get {
                return ResourceManager.GetString("LabelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string LabelPresentationVoiDataLut {
            get {
                return ResourceManager.GetString("LabelPresentationVoiDataLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string LabelPresentationVoiLinearLut {
            get {
                return ResourceManager.GetString("LabelPresentationVoiLinearLut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/cm 的本地化字符串。
        /// </summary>
        public static string LabelUnits1cm {
            get {
                return ResourceManager.GetString("LabelUnits1cm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bq/ml 的本地化字符串。
        /// </summary>
        public static string LabelUnitsBqml {
            get {
                return ResourceManager.GetString("LabelUnitsBqml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cm² 的本地化字符串。
        /// </summary>
        public static string LabelUnitsCm2 {
            get {
                return ResourceManager.GetString("LabelUnitsCm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 cm²/ml 的本地化字符串。
        /// </summary>
        public static string LabelUnitsCm2ml {
            get {
                return ResourceManager.GetString("LabelUnitsCm2ml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计数 的本地化字符串。
        /// </summary>
        public static string LabelUnitsCnts {
            get {
                return ResourceManager.GetString("LabelUnitsCnts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 counts/s 的本地化字符串。
        /// </summary>
        public static string LabelUnitsCps {
            get {
                return ResourceManager.GetString("LabelUnitsCps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 g/ml 的本地化字符串。
        /// </summary>
        public static string LabelUnitsGml {
            get {
                return ResourceManager.GetString("LabelUnitsGml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HU 的本地化字符串。
        /// </summary>
        public static string LabelUnitsHU {
            get {
                return ResourceManager.GetString("LabelUnitsHU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mg/min/ml 的本地化字符串。
        /// </summary>
        public static string LabelUnitsMgminml {
            get {
                return ResourceManager.GetString("LabelUnitsMgminml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ml/g 的本地化字符串。
        /// </summary>
        public static string LabelUnitsMlg {
            get {
                return ResourceManager.GetString("LabelUnitsMlg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ml/min/g 的本地化字符串。
        /// </summary>
        public static string LabelUnitsMlming {
            get {
                return ResourceManager.GetString("LabelUnitsMlming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ml/min/ml 的本地化字符串。
        /// </summary>
        public static string LabelUnitsMlminml {
            get {
                return ResourceManager.GetString("LabelUnitsMlminml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ml/ml 的本地化字符串。
        /// </summary>
        public static string LabelUnitsMlml {
            get {
                return ResourceManager.GetString("LabelUnitsMlml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 mm² 的本地化字符串。
        /// </summary>
        public static string LabelUnitsMm2 {
            get {
                return ResourceManager.GetString("LabelUnitsMm2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1/1000 OD 的本地化字符串。
        /// </summary>
        public static string LabelUnitsOD {
            get {
                return ResourceManager.GetString("LabelUnitsOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 % 的本地化字符串。
        /// </summary>
        public static string LabelUnitsPcnt {
            get {
                return ResourceManager.GetString("LabelUnitsPcnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 像素 的本地化字符串。
        /// </summary>
        public static string LabelUnitsPixels {
            get {
                return ResourceManager.GetString("LabelUnitsPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 prop. to counts 的本地化字符串。
        /// </summary>
        public static string LabelUnitsPropcnts {
            get {
                return ResourceManager.GetString("LabelUnitsPropcnts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 prop. to counts/s 的本地化字符串。
        /// </summary>
        public static string LabelUnitsPropcps {
            get {
                return ResourceManager.GetString("LabelUnitsPropcps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 σ 的本地化字符串。
        /// </summary>
        public static string LabelUnitsStddev {
            get {
                return ResourceManager.GetString("LabelUnitsStddev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 µmol/min/ml 的本地化字符串。
        /// </summary>
        public static string LabelUnitsUmolminml {
            get {
                return ResourceManager.GetString("LabelUnitsUmolminml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 µmol/ml 的本地化字符串。
        /// </summary>
        public static string LabelUnitsUmolml {
            get {
                return ResourceManager.GetString("LabelUnitsUmolml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string LabelUnitsUnspecified {
            get {
                return ResourceManager.GetString("LabelUnitsUnspecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string LabelUnknown {
            get {
                return ResourceManager.GetString("LabelUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string LabelUnknownServer {
            get {
                return ResourceManager.GetString("LabelUnknownServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除顶点 的本地化字符串。
        /// </summary>
        public static string MenuDeleteVertex {
            get {
                return ResourceManager.GetString("MenuDeleteVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string MenuEditText {
            get {
                return ResourceManager.GetString("MenuEditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入顶点 的本地化字符串。
        /// </summary>
        public static string MenuInsertVertex {
            get {
                return ResourceManager.GetString("MenuInsertVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名 的本地化字符串。
        /// </summary>
        public static string MenuRename {
            get {
                return ResourceManager.GetString("MenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示分析 的本地化字符串。
        /// </summary>
        public static string MenuShowAnalysis {
            get {
                return ResourceManager.GetString("MenuShowAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请联系您的PACS管理员以获取帮助。 的本地化字符串。
        /// </summary>
        public static string MessageContactPacsAdmin {
            get {
                return ResourceManager.GetString("MessageContactPacsAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试克隆显示集时发生错误。请查看日志以获取更多详细信息。 的本地化字符串。
        /// </summary>
        public static string MessageErrorCloningDisplaySet {
            get {
                return ResourceManager.GetString("MessageErrorCloningDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试克隆图像时出错。 有关详细信息, 请查看日志。 的本地化字符串。
        /// </summary>
        public static string MessageErrorCloningPresentationImage {
            get {
                return ResourceManager.GetString("MessageErrorCloningPresentationImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一个或多个叠加层无法显示。谨慎使用图像。 的本地化字符串。
        /// </summary>
        public static string MessageErrorDisplayingOverlays {
            get {
                return ResourceManager.GetString("MessageErrorDisplayingOverlays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试加载文本叠加层时发生不可恢复的错误。有关详细信息，请参阅日志。 的本地化字符串。
        /// </summary>
        public static string MessageErrorLoadingAnnotationLayout {
            get {
                return ResourceManager.GetString("MessageErrorLoadingAnnotationLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试从图像标题添加图形时发生错误。部分或全部将不会出现。 的本地化字符串。
        /// </summary>
        public static string MessageFailedToApplyDicomHeaderGraphics {
            get {
                return ResourceManager.GetString("MessageFailedToApplyDicomHeaderGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intelligent 智能只能加载您请求的 {1} 图像的 {0}。 的本地化字符串。
        /// </summary>
        public static string MessageFormatLoadStudyIncomplete {
            get {
                return ResourceManager.GetString("MessageFormatLoadStudyIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开 {1} 图像的 {0} 的本地化字符串。
        /// </summary>
        public static string MessageFormatOpeningImages {
            get {
                return ResourceManager.GetString("MessageFormatOpeningImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}
        ///{1} 的本地化字符串。
        /// </summary>
        public static string MessageFormatStudyNotLoadable {
            get {
                return ResourceManager.GetString("MessageFormatStudyNotLoadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 检查仅部分加载。 的本地化字符串。
        /// </summary>
        public static string MessageFormatXStudiesIncomplete {
            get {
                return ResourceManager.GetString("MessageFormatXStudiesIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 检查正在使用中。 的本地化字符串。
        /// </summary>
        public static string MessageFormatXStudiesInUse {
            get {
                return ResourceManager.GetString("MessageFormatXStudiesInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} studies are nearline. 的本地化字符串。
        /// </summary>
        public static string MessageFormatXStudiesNearline {
            get {
                return ResourceManager.GetString("MessageFormatXStudiesNearline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 检查未找到。 的本地化字符串。
        /// </summary>
        public static string MessageFormatXStudiesNotFound {
            get {
                return ResourceManager.GetString("MessageFormatXStudiesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 检查无法加载。 的本地化字符串。
        /// </summary>
        public static string MessageFormatXStudiesNotLoaded {
            get {
                return ResourceManager.GetString("MessageFormatXStudiesNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} 检查已离线。 的本地化字符串。
        /// </summary>
        public static string MessageFormatXStudiesOffline {
            get {
                return ResourceManager.GetString("MessageFormatXStudiesOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该检查是在非流媒体服务器上进行的，必须检索并重新打开。 的本地化字符串。
        /// </summary>
        public static string MessageInfoNoStudyLoader {
            get {
                return ResourceManager.GetString("MessageInfoNoStudyLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该检查无法加载。 请联系您的PACS管理员。 的本地化字符串。
        /// </summary>
        public static string MessageInfoStudyCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("MessageInfoStudyCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该检查正在使用中。 请关闭当前的检查，等待几分钟，然后再次尝试加载研究。 的本地化字符串。
        /// </summary>
        public static string MessageInfoStudyInUse {
            get {
                return ResourceManager.GetString("MessageInfoStudyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 这项检查接近尾声。 如果您的PACS是Intelligent ImageServer，请尝试手动打开研究，然后等待几分钟再重试。
        ///或者，该研究可由PACS管理员重新上线。 的本地化字符串。
        /// </summary>
        public static string MessageInfoStudyNearline {
            get {
                return ResourceManager.GetString("MessageInfoStudyNearline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该检查处于离线状态，必须由PACS管理员重新联机。 的本地化字符串。
        /// </summary>
        public static string MessageInfoStudyOffline {
            get {
                return ResourceManager.GetString("MessageInfoStudyOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反序列化关键对象选择文档时发生错误。 的本地化字符串。
        /// </summary>
        public static string MessageKeyObjectDeserializeFailure {
            get {
                return ResourceManager.GetString("MessageKeyObjectDeserializeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载检查时发生以下故障： 的本地化字符串。
        /// </summary>
        public static string MessageLoadMultipleStudiesFailurePrefix {
            get {
                return ResourceManager.GetString("MessageLoadMultipleStudiesFailurePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Intelligent 智能无法加载您请求的任何图像。 的本地化字符串。
        /// </summary>
        public static string MessageLoadStudyCompleteFailure {
            get {
                return ResourceManager.GetString("MessageLoadStudyCompleteFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该检查正由服务器处理，目前无法加载。 请稍后再试。 的本地化字符串。
        /// </summary>
        public static string MessageLoadStudyFailedInUse {
            get {
                return ResourceManager.GetString("MessageLoadStudyFailedInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该检查目前正在从存档中恢复，目前无法加载。 请稍后再试。 的本地化字符串。
        /// </summary>
        public static string MessageLoadStudyFailedNearline {
            get {
                return ResourceManager.GetString("MessageLoadStudyFailedNearline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该检查近在咫尺，此时无法恢复。 请联系您的PACS管理员以恢复该研究。 的本地化字符串。
        /// </summary>
        public static string MessageLoadStudyFailedNearlineNoRestore {
            get {
                return ResourceManager.GetString("MessageLoadStudyFailedNearlineNoRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法找到该检查。 的本地化字符串。
        /// </summary>
        public static string MessageLoadStudyFailedNotFound {
            get {
                return ResourceManager.GetString("MessageLoadStudyFailedNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法加载该检查，因为它处于脱机状态。 请联系您的PACS管理员以恢复该研究。 的本地化字符串。
        /// </summary>
        public static string MessageLoadStudyFailedOffline {
            get {
                return ResourceManager.GetString("MessageLoadStudyFailedOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有渲染器插件;默认为GDI渲染器。 的本地化字符串。
        /// </summary>
        public static string MessageNoRendererPluginsExist {
            get {
                return ResourceManager.GetString("MessageNoRendererPluginsExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法加载要显示的图像。 的本地化字符串。
        /// </summary>
        public static string MessageNoVisibleDisplaySets {
            get {
                return ResourceManager.GetString("MessageNoVisibleDisplaySets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一项检查只被部分加载。 的本地化字符串。
        /// </summary>
        public static string MessageOneStudyIncomplete {
            get {
                return ResourceManager.GetString("MessageOneStudyIncomplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有一项检查正在使用中。 的本地化字符串。
        /// </summary>
        public static string MessageOneStudyInUse {
            get {
                return ResourceManager.GetString("MessageOneStudyInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 One study is nearline. 的本地化字符串。
        /// </summary>
        public static string MessageOneStudyNearline {
            get {
                return ResourceManager.GetString("MessageOneStudyNearline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有一项检查未找到。 的本地化字符串。
        /// </summary>
        public static string MessageOneStudyNotFound {
            get {
                return ResourceManager.GetString("MessageOneStudyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 一项检查无法加载。 的本地化字符串。
        /// </summary>
        public static string MessageOneStudyNotLoaded {
            get {
                return ResourceManager.GetString("MessageOneStudyNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有一项检查离线。 的本地化字符串。
        /// </summary>
        public static string MessageOneStudyOffline {
            get {
                return ResourceManager.GetString("MessageOneStudyOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 尝试加载演示文稿状态时出错。演示文稿状态可能尚未全部加载。有关详细信息, 请查看日志。 的本地化字符串。
        /// </summary>
        public static string MessagePresentationStateApplicationFailure {
            get {
                return ResourceManager.GetString("MessagePresentationStateApplicationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反序列化图像显示状态时发生错误。 的本地化字符串。
        /// </summary>
        public static string MessagePresentationStateDeserializeFailure {
            get {
                return ResourceManager.GetString("MessagePresentationStateDeserializeFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试图读取演示文稿状态文件时出错。有关详细信息, 请查看日志。 的本地化字符串。
        /// </summary>
        public static string MessagePresentationStateReadFailure {
            get {
                return ResourceManager.GetString("MessagePresentationStateReadFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 找到了引用的关键图像, 但不包含指定的帧。 的本地化字符串。
        /// </summary>
        public static string MessageReferencedKeyImageFrameNotFound {
            get {
                return ResourceManager.GetString("MessageReferencedKeyImageFrameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 引用的关键图像无法显示, 因为它不是加载的检查的一部分。 的本地化字符串。
        /// </summary>
        public static string MessageReferencedKeyImageFromOtherStudy {
            get {
                return ResourceManager.GetString("MessageReferencedKeyImageFromOtherStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 呈现管道中发生错误。 的本地化字符串。
        /// </summary>
        public static string MessageRenderingPipelineFailure {
            get {
                return ResourceManager.GetString("MessageRenderingPipelineFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分析Roi时发生错误。有关详细信息, 请查看日志。 的本地化字符串。
        /// </summary>
        public static string MessageRoiAnalysisError {
            get {
                return ResourceManager.GetString("MessageRoiAnalysisError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不支持的图像类型：{0} 的本地化字符串。
        /// </summary>
        public static string MessageUnsupportedImageType {
            get {
                return ResourceManager.GetString("MessageUnsupportedImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所选图像的类型不受支持。 MPR仅支持DICOM图像SOP。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceAreNotSupported {
            get {
                return ResourceManager.GetString("MessageVolumeSourceAreNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源数据集中的每个帧必须具有相同的解剖学侧向性。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceInconsistentImageLaterality {
            get {
                return ResourceManager.GetString("MessageVolumeSourceInconsistentImageLaterality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源数据集中的每个帧必须使用相同的像素单位。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceInconsistentRescaleUnits {
            get {
                return ResourceManager.GetString("MessageVolumeSourceInconsistentRescaleUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所选图像具有龙门架旋转。 MPR仅支持龙门倾斜。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceMayBotBeGantrySlewed {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMayBotBeGantrySlewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所选图像具有各向异性像素长宽比。 MPR仅支持1：1各向同性的纵横比。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceMayNotHaveAnisotropicPixels {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMayNotHaveAnisotropicPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源数据集必须至少包含三个帧。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceMinimumThreeImages {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMinimumThreeImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MPR仅支持16位灰度图像。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceMustBe16BitGreyscale {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBe16BitGreyscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须校准所选图像。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceMustBeCalibrated {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBeCalibrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像之间的间距不一致。MPR需要均匀间隔的图像。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceMustBeEvenlySpacedForMpr {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBeEvenlySpacedForMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源数据集中的每个帧必须具有相同的图像方向 (患者)。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceMustBeSameImageOrientationPatient {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBeSameImageOrientationPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源数据集中的每个帧必须具有相同的参考框架。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceMustBeSingleFrameOfReference {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBeSingleFrameOfReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源数据集中的每个帧必须来自同一序列。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceMustBeSingleSeries {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBeSingleSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源数据集中的每个帧必须来自同一检查。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceMustBeSingleStudy {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBeSingleStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两个图像位于相同的患者位置。 MPR需要均匀间隔的图像。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceMustBeUniquelyLocatedForMpr {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustBeUniquelyLocatedForMpr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源数据集中的每个帧必须具有已定义的图像方向（患者）。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceMustDefineImageOrientationPatient {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustDefineImageOrientationPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源数据集中的每个框架都必须指定一个参考框架。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceMustSpecifyFrameOfReference {
            get {
                return ResourceManager.GetString("MessageVolumeSourceMustSpecifyFrameOfReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建卷时遇到意外的异常。 的本地化字符串。
        /// </summary>
        public static string MessageVolumeSourceUnexpectedException {
            get {
                return ResourceManager.GetString("MessageVolumeSourceUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可见显示集 的本地化字符串。
        /// </summary>
        public static string NamePrefetchingStrategyVisibleDisplaySet {
            get {
                return ResourceManager.GetString("NamePrefetchingStrategyVisibleDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 的本地化字符串。
        /// </summary>
        public static string SeparatorPatientDescription {
            get {
                return ResourceManager.GetString("SeparatorPatientDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 :: 的本地化字符串。
        /// </summary>
        public static string SeparatorPatientsLoaded {
            get {
                return ResourceManager.GetString("SeparatorPatientsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N/A 的本地化字符串。
        /// </summary>
        public static string StringNotApplicable {
            get {
                return ResourceManager.GetString("StringNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 --- 的本地化字符串。
        /// </summary>
        public static string StringNoValue {
            get {
                return ResourceManager.GetString("StringNoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关键图像 的本地化字符串。
        /// </summary>
        public static string SuffixFormatKeyImageDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatKeyImageDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Echo #{0} 的本地化字符串。
        /// </summary>
        public static string SuffixFormatMREchoDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatMREchoDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多帧 # {0} 的本地化字符串。
        /// </summary>
        public static string SuffixFormatMultiframeDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatMultiframeDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 堆栈 {0} 的本地化字符串。
        /// </summary>
        public static string SuffixFormatMultiframeStackDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatMultiframeStackDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像/框架 #: {0}/{1} 的本地化字符串。
        /// </summary>
        public static string SuffixFormatSingleFrameDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatSingleFrameDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像 # {0} 的本地化字符串。
        /// </summary>
        public static string SuffixFormatSingleImageDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatSingleImageDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} (Image# {1}) 的本地化字符串。
        /// </summary>
        public static string SuffixFormatSingleImageDisplaySetWithLateralityViewPosition {
            get {
                return ResourceManager.GetString("SuffixFormatSingleImageDisplaySetWithLateralityViewPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列/图像/帧：{0} / {1} / {2} 的本地化字符串。
        /// </summary>
        public static string SuffixFormatSingleReferencedFrameDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatSingleReferencedFrameDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序列/图片＃：{0} / {1} 的本地化字符串。
        /// </summary>
        public static string SuffixFormatSingleReferencedImageDisplaySet {
            get {
                return ResourceManager.GetString("SuffixFormatSingleReferencedImageDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} (序列/图像 #: {1}/{2}) 的本地化字符串。
        /// </summary>
        public static string SuffixFormatSingleReferencedImageDisplaySetWithLateralityViewPosition {
            get {
                return ResourceManager.GetString("SuffixFormatSingleReferencedImageDisplaySetWithLateralityViewPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单个图像 的本地化字符串。
        /// </summary>
        public static string SuffixSingleImagesDisplaySet {
            get {
                return ResourceManager.GetString("SuffixSingleImagesDisplaySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 的本地化字符串。
        /// </summary>
        public static string ValueNil {
            get {
                return ResourceManager.GetString("ValueNil", resourceCulture);
            }
        }
    }
}
