//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClearCanvas.ImageViewer.AnnotationProviders {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClearCanvas.ImageViewer.AnnotationProviders.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Dicom（对比/推注） 的本地化字符串。
        /// </summary>
        public static string AnnotationItemProviders_Dicom_ContrastBolus_DisplayName {
            get {
                return ResourceManager.GetString("AnnotationItemProviders_Dicom_ContrastBolus_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dicom (CT 影像) 的本地化字符串。
        /// </summary>
        public static string AnnotationItemProviders_Dicom_CTImage_DisplayName {
            get {
                return ResourceManager.GetString("AnnotationItemProviders_Dicom_CTImage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dicom (DX 影像) 的本地化字符串。
        /// </summary>
        public static string AnnotationItemProviders_Dicom_DXImage_DisplayName {
            get {
                return ResourceManager.GetString("AnnotationItemProviders_Dicom_DXImage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 dicom (通用设备) 的本地化字符串。
        /// </summary>
        public static string AnnotationItemProviders_Dicom_GeneralEquipment_DisplayName {
            get {
                return ResourceManager.GetString("AnnotationItemProviders_Dicom_GeneralEquipment_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dicom（一般图像） 的本地化字符串。
        /// </summary>
        public static string AnnotationItemProviders_Dicom_GeneralImage_DisplayName {
            get {
                return ResourceManager.GetString("AnnotationItemProviders_Dicom_GeneralImage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dicom（一般序列） 的本地化字符串。
        /// </summary>
        public static string AnnotationItemProviders_Dicom_GeneralSeries_DisplayName {
            get {
                return ResourceManager.GetString("AnnotationItemProviders_Dicom_GeneralSeries_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dicom（一般检查） 的本地化字符串。
        /// </summary>
        public static string AnnotationItemProviders_Dicom_GeneralStudy_DisplayName {
            get {
                return ResourceManager.GetString("AnnotationItemProviders_Dicom_GeneralStudy_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dicom（图像平面） 的本地化字符串。
        /// </summary>
        public static string AnnotationItemProviders_Dicom_ImagePlane_DisplayName {
            get {
                return ResourceManager.GetString("AnnotationItemProviders_Dicom_ImagePlane_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dicom (MR 图像) 的本地化字符串。
        /// </summary>
        public static string AnnotationItemProviders_Dicom_MRImage_DisplayName {
            get {
                return ResourceManager.GetString("AnnotationItemProviders_Dicom_MRImage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dicom (患者) 的本地化字符串。
        /// </summary>
        public static string AnnotationItemProviders_Dicom_Patient_DisplayName {
            get {
                return ResourceManager.GetString("AnnotationItemProviders_Dicom_Patient_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dicom (患者 / 检查) 的本地化字符串。
        /// </summary>
        public static string AnnotationItemProviders_Dicom_PatientStudy_DisplayName {
            get {
                return ResourceManager.GetString("AnnotationItemProviders_Dicom_PatientStudy_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 介绍 的本地化字符串。
        /// </summary>
        public static string AnnotationItemProviders_Presentation_DisplayName {
            get {
                return ResourceManager.GetString("AnnotationItemProviders_Presentation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对比度Agent 的本地化字符串。
        /// </summary>
        public static string Dicom_ContrastBolus_Agent_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_ContrastBolus_Agent_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对比度 的本地化字符串。
        /// </summary>
        public static string Dicom_ContrastBolus_Agent_Label {
            get {
                return ResourceManager.GetString("Dicom_ContrastBolus_Agent_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表位/速度 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_Composite_TablePositionSpeed_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_CTImage_Composite_TablePositionSpeed_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_Composite_TablePositionSpeed_Label {
            get {
                return ResourceManager.GetString("Dicom_CTImage_Composite_TablePositionSpeed_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Convolution Kernel 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_ConvolutionKernel_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_CTImage_ConvolutionKernel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_ConvolutionKernel_Label {
            get {
                return ResourceManager.GetString("Dicom_CTImage_ConvolutionKernel_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曝光(CT) 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_Exposure_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_CTImage_Exposure_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exp 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_Exposure_Label {
            get {
                return ResourceManager.GetString("Dicom_CTImage_Exposure_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曝光时间 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_ExposureTime_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_CTImage_ExposureTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exp Time 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_ExposureTime_Label {
            get {
                return ResourceManager.GetString("Dicom_CTImage_ExposureTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 龙门倾斜 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_GantryDetectorTilt_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_CTImage_GantryDetectorTilt_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tilt 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_GantryDetectorTilt_Label {
            get {
                return ResourceManager.GetString("Dicom_CTImage_GantryDetectorTilt_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KVP 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_KVP_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_CTImage_KVP_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KVP 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_KVP_Label {
            get {
                return ResourceManager.GetString("Dicom_CTImage_KVP_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作台位置 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_TablePosition_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_CTImage_TablePosition_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pos 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_TablePosition_Label {
            get {
                return ResourceManager.GetString("Dicom_CTImage_TablePosition_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作台速度 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_TableSpeed_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_CTImage_TableSpeed_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Spd 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_TableSpeed_Label {
            get {
                return ResourceManager.GetString("Dicom_CTImage_TableSpeed_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tube Current 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_XRayTubeCurrent_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_CTImage_XRayTubeCurrent_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tube Current 的本地化字符串。
        /// </summary>
        public static string Dicom_CTImage_XRayTubeCurrent_Label {
            get {
                return ResourceManager.GetString("Dicom_CTImage_XRayTubeCurrent_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取设备处理说明 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_AcquisitionDeviceProcessingDescription_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_AcquisitionDeviceProcessingDescription_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 处理 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_AcquisitionDeviceProcessingDescription_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_AcquisitionDeviceProcessingDescription_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均脉冲宽度 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_AveragePulseWidth_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_AveragePulseWidth_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均脉冲宽度 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_AveragePulseWidth_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_AveragePulseWidth_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身体部位厚度 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_BodyPartThickness_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_BodyPartThickness_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身体部位厚度 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_BodyPartThickness_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_BodyPartThickness_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁带ID 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_CassetteId_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_CassetteId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁带 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_CassetteId_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_CassetteId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压缩力 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_CompressionForce_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_CompressionForce_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 压缩力 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_CompressionForce_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_CompressionForce_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contrast/Bolus Agent (X-Ray) 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_ContrastBolusAgent_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_ContrastBolusAgent_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Contrast/Bolus 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_ContrastBolusAgent_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_ContrastBolusAgent_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测器主角度 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_DetectorPrimaryAngle_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_DetectorPrimaryAngle_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测器主角度 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_DetectorPrimaryAngle_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_DetectorPrimaryAngle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曝光(DX) 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_Exposure_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_Exposure_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exp 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_Exposure_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_Exposure_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mas中曝光 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_ExposureInMas_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_ExposureInMas_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exp 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_ExposureInMas_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_ExposureInMas_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 曝光时间(DX) 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_ExposureTime_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_ExposureTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exp Time 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_ExposureTime_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_ExposureTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤材料 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_FilterMaterial_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_FilterMaterial_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤器 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_FilterMaterial_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_FilterMaterial_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像和荧光检查区域剂量产品 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_ImageAndFluoroscopyAreaDoseProduct_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_ImageAndFluoroscopyAreaDoseProduct_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DAP总计 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_ImageAndFluoroscopyAreaDoseProduct_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_ImageAndFluoroscopyAreaDoseProduct_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KVP (DX) 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_KVP_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_KVP_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 KVP 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_KVP_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_KVP_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平板ID 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_PlateId_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_PlateId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平板 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_PlateId_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_PlateId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定位器主角度 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_PositionerPrimaryAngle_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_PositionerPrimaryAngle_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定位器主角度 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_PositionerPrimaryAngle_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_PositionerPrimaryAngle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定位器二次角度 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_PositionerSecondaryAngle_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_PositionerSecondaryAngle_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 定位器二次角度 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_PositionerSecondaryAngle_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_PositionerSecondaryAngle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意图介绍 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_PresentationIntentType_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_PresentationIntentType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 意图 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_PresentationIntentType_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_PresentationIntentType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tube Current (DX) 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_XRayTubeCurrent_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_DXImage_XRayTubeCurrent_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Tube Current 的本地化字符串。
        /// </summary>
        public static string Dicom_DXImage_XRayTubeCurrent_Label {
            get {
                return ResourceManager.GetString("Dicom_DXImage_XRayTubeCurrent_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上次校准的日期 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_DateOfLastCalibration_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_DateOfLastCalibration_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校准日期 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_DateOfLastCalibration_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_DateOfLastCalibration_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备序列号 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_DeviceSerialNumber_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_DeviceSerialNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Serial 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_DeviceSerialNumber_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_DeviceSerialNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构地址 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_InstitutionAddress_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_InstitutionAddress_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inst. Addr. 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_InstitutionAddress_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_InstitutionAddress_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构部门名称 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_InstitutionalDepartmentName_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_InstitutionalDepartmentName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inst. Dept. Name 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_InstitutionalDepartmentName_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_InstitutionalDepartmentName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机构名称 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_InstitutionName_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_InstitutionName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inst. Name 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_InstitutionName_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_InstitutionName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 厂商 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_Manufacturer_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_Manufacturer_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mfr. 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_Manufacturer_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_Manufacturer_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 制造商的型号名称 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_ManufacturersModelName_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_ManufacturersModelName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Mfr.&apos;s Model 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_ManufacturersModelName_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_ManufacturersModelName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件版本 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_SoftwareVersions_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_SoftwareVersions_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件版本 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_SoftwareVersions_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_SoftwareVersions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站名 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_StationName_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_StationName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 站 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_StationName_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_StationName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后校准的时间 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_TimeOfLastCalibration_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_TimeOfLastCalibration_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Calib. Time 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralEquipment_TimeOfLastCalibration_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralEquipment_TimeOfLastCalibration_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集日期 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_AcquisitionDate_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_AcquisitionDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acq 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_AcquisitionDate_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_AcquisitionDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集日期/时间 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_AcquisitionDateTime_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_AcquisitionDateTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acq 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_AcquisitionDateTime_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_AcquisitionDateTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集编号 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_AcquisitionNumber_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_AcquisitionNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acq 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_AcquisitionNumber_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_AcquisitionNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集时间 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_AcquisitionTime_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_AcquisitionTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acq 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_AcquisitionTime_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_AcquisitionTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像横向和视图位置 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_Composite_LateralityViewPosition_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_Composite_LateralityViewPosition_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lat/Pos 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_Composite_LateralityViewPosition_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_Composite_LateralityViewPosition_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容日期 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_ContentDate_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_ContentDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容日期 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_ContentDate_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_ContentDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容时间 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_ContentTime_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_ContentTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容时间 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_ContentTime_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_ContentTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推导说明 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_DerivationDescription_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_DerivationDescription_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Deriv. Desc. 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_DerivationDescription_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_DerivationDescription_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片评论 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_ImageComments_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_ImageComments_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Img. Comm. 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_ImageComments_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_ImageComments_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像横向 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_ImageLaterality_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_ImageLaterality_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lat 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_ImageLaterality_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_ImageLaterality_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集的图像 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_ImagesInAcquisition_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_ImagesInAcquisition_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Imgs. in Acq. 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_ImagesInAcquisition_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_ImagesInAcquisition_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像类型 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_ImageType_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_ImageType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Img. Type 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_ImageType_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_ImageType_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实例编号 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_InstanceNumber_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_InstanceNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Im 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_InstanceNumber_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_InstanceNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有损图像压缩 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_LossyImageCompression_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_LossyImageCompression_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有损 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_LossyImageCompression_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_LossyImageCompression_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有损图像压缩比 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_LossyImageCompressionRatio_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_LossyImageCompressionRatio_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lossy Img. Comp. Ratio 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_LossyImageCompressionRatio_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_LossyImageCompressionRatio_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质量控制图像 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_QualityControlImage_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_QualityControlImage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 质量控制 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_QualityControlImage_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_QualityControlImage_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查看位置 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_ViewPosition_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_ViewPosition_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pos 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralImage_ViewPosition_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralImage_ViewPosition_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身体部位检查 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_BodyPartExamined_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_BodyPartExamined_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身体部分 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_BodyPartExamined_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_BodyPartExamined_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 侧向(序列) 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_Laterality_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_Laterality_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lat 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_Laterality_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_Laterality_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模态 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_Modality_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_Modality_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模态 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_Modality_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_Modality_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员姓名 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_OperatorsName_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_OperatorsName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_OperatorsName_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_OperatorsName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行过程步骤说明 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_PerformedProcedureStepDescription_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_PerformedProcedureStepDescription_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perf. Proc. 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_PerformedProcedureStepDescription_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_PerformedProcedureStepDescription_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行医生姓名 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_PerformingPhysiciansName_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_PerformingPhysiciansName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Perf. Phys. 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_PerformingPhysiciansName_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_PerformingPhysiciansName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 协议名称 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_ProtocolName_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_ProtocolName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 协议名称 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_ProtocolName_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_ProtocolName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Series Date 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_SeriesDate_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_SeriesDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Series Date 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_SeriesDate_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_SeriesDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Series Description 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_SeriesDescription_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_SeriesDescription_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desc. 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_SeriesDescription_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_SeriesDescription_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Series Number 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_SeriesNumber_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_SeriesNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Se 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_SeriesNumber_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_SeriesNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Series Time 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_SeriesTime_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_SeriesTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Series Time 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralSeries_SeriesTime_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralSeries_SeriesTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集编号 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralStudy_AccessionNumber_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralStudy_AccessionNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Acc 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralStudy_AccessionNumber_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralStudy_AccessionNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐医师 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralStudy_ReferringPhysiciansName_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralStudy_ReferringPhysiciansName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ref. Phys. 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralStudy_ReferringPhysiciansName_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralStudy_ReferringPhysiciansName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查日期 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralStudy_StudyDate_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralStudy_StudyDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查日期 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralStudy_StudyDate_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralStudy_StudyDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查说明 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralStudy_StudyDescription_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralStudy_StudyDescription_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Study Desc. 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralStudy_StudyDescription_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralStudy_StudyDescription_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查ID 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralStudy_StudyId_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralStudy_StudyId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查ID 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralStudy_StudyId_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralStudy_StudyId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查时间 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralStudy_StudyTime_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_GeneralStudy_StudyTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检查时间 的本地化字符串。
        /// </summary>
        public static string Dicom_GeneralStudy_StudyTime_Label {
            get {
                return ResourceManager.GetString("Dicom_GeneralStudy_StudyTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切片位置 的本地化字符串。
        /// </summary>
        public static string Dicom_ImagePlane_SliceLocation_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_ImagePlane_SliceLocation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loc 的本地化字符串。
        /// </summary>
        public static string Dicom_ImagePlane_SliceLocation_Label {
            get {
                return ResourceManager.GetString("Dicom_ImagePlane_SliceLocation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切片厚度 的本地化字符串。
        /// </summary>
        public static string Dicom_ImagePlane_SliceThickness_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_ImagePlane_SliceThickness_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Thk 的本地化字符串。
        /// </summary>
        public static string Dicom_ImagePlane_SliceThickness_Label {
            get {
                return ResourceManager.GetString("Dicom_ImagePlane_SliceThickness_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 采集矩阵 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_AcquisitionMatrix_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_MRImage_AcquisitionMatrix_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_AcquisitionMatrix_Label {
            get {
                return ResourceManager.GetString("Dicom_MRImage_AcquisitionMatrix_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Echo Number 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_EchoNumber_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_MRImage_EchoNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_EchoNumber_Label {
            get {
                return ResourceManager.GetString("Dicom_MRImage_EchoNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Echo Time 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_EchoTime_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_MRImage_EchoTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TE 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_EchoTime_Label {
            get {
                return ResourceManager.GetString("Dicom_MRImage_EchoTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Echo Train Length 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_EchoTrainLength_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_MRImage_EchoTrainLength_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ET 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_EchoTrainLength_Label {
            get {
                return ResourceManager.GetString("Dicom_MRImage_EchoTrainLength_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻转角度 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_FlipAngle_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_MRImage_FlipAngle_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻转 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_FlipAngle_Label {
            get {
                return ResourceManager.GetString("Dicom_MRImage_FlipAngle_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倒装时间 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_InversionTime_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_MRImage_InversionTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TI 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_InversionTime_Label {
            get {
                return ResourceManager.GetString("Dicom_MRImage_InversionTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 磁场强度 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_MagneticFieldStrength_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_MRImage_MagneticFieldStrength_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_MagneticFieldStrength_Label {
            get {
                return ResourceManager.GetString("Dicom_MRImage_MagneticFieldStrength_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 平均数值 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_NumberOfAverages_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_MRImage_NumberOfAverages_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #Avgs 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_NumberOfAverages_Label {
            get {
                return ResourceManager.GetString("Dicom_MRImage_NumberOfAverages_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 像素带宽 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_PixelBandwidth_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_MRImage_PixelBandwidth_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BW 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_PixelBandwidth_Label {
            get {
                return ResourceManager.GetString("Dicom_MRImage_PixelBandwidth_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接收线圈名称 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_ReceiveCoilName_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_MRImage_ReceiveCoilName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_ReceiveCoilName_Label {
            get {
                return ResourceManager.GetString("Dicom_MRImage_ReceiveCoilName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复时间 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_RepetitionTime_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_MRImage_RepetitionTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TR 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_RepetitionTime_Label {
            get {
                return ResourceManager.GetString("Dicom_MRImage_RepetitionTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发时间 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_TriggerTime_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_MRImage_TriggerTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 触发 的本地化字符串。
        /// </summary>
        public static string Dicom_MRImage_TriggerTime_Label {
            get {
                return ResourceManager.GetString("Dicom_MRImage_TriggerTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 族群 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_EthnicGroup_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_Patient_EthnicGroup_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 族群 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_EthnicGroup_Label {
            get {
                return ResourceManager.GetString("Dicom_Patient_EthnicGroup_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他患者ID 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_OtherPatientIds_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_Patient_OtherPatientIds_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ot. Pat. IDs 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_OtherPatientIds_Label {
            get {
                return ResourceManager.GetString("Dicom_Patient_OtherPatientIds_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者种类Breed 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientBreed_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientBreed_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品种 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientBreed_Label {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientBreed_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者意见 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientComments_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientComments_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pat. Comm. 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientComments_Label {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientComments_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者ID 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientId_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientId_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pat. ID 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientId_Label {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientId_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者的出生日期 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientsBirthDate_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientsBirthDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DOB 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientsBirthDate_Label {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientsBirthDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者的出生时间 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientsBirthTime_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientsBirthTime_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出生时间 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientsBirthTime_Label {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientsBirthTime_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者姓名 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientsName_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientsName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者姓名 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientsName_Label {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientsName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者种类Species 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientSpecies_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientSpecies_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 种类 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientSpecies_Label {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientSpecies_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者性别 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientsSex_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientsSex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 性别 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_PatientsSex_Label {
            get {
                return ResourceManager.GetString("Dicom_Patient_PatientsSex_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主管组织 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_ResponsibleOrganization_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_Patient_ResponsibleOrganization_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主管组织 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_ResponsibleOrganization_Label {
            get {
                return ResourceManager.GetString("Dicom_Patient_ResponsibleOrganization_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负责人 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_ResponsiblePerson_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_Patient_ResponsiblePerson_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 负责人 的本地化字符串。
        /// </summary>
        public static string Dicom_Patient_ResponsiblePerson_Label {
            get {
                return ResourceManager.GetString("Dicom_Patient_ResponsiblePerson_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他患者的历史记录 的本地化字符串。
        /// </summary>
        public static string Dicom_PatientStudy_AdditionalPatientsHistory_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_PatientStudy_AdditionalPatientsHistory_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史 的本地化字符串。
        /// </summary>
        public static string Dicom_PatientStudy_AdditionalPatientsHistory_Label {
            get {
                return ResourceManager.GetString("Dicom_PatientStudy_AdditionalPatientsHistory_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者的年龄和性别 的本地化字符串。
        /// </summary>
        public static string Dicom_PatientStudy_Composite_PatientsAgeSex_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_PatientStudy_Composite_PatientsAgeSex_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年龄/性别 的本地化字符串。
        /// </summary>
        public static string Dicom_PatientStudy_Composite_PatientsAgeSex_Label {
            get {
                return ResourceManager.GetString("Dicom_PatientStudy_Composite_PatientsAgeSex_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者的年龄、性别和出生日期 的本地化字符串。
        /// </summary>
        public static string Dicom_PatientStudy_Composite_PatientsAgeSexBirthDate_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_PatientStudy_Composite_PatientsAgeSexBirthDate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年龄/性别/DOB 的本地化字符串。
        /// </summary>
        public static string Dicom_PatientStudy_Composite_PatientsAgeSexBirthDate_Label {
            get {
                return ResourceManager.GetString("Dicom_PatientStudy_Composite_PatientsAgeSexBirthDate_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职业 的本地化字符串。
        /// </summary>
        public static string Dicom_PatientStudy_Occupation_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_PatientStudy_Occupation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 职业 的本地化字符串。
        /// </summary>
        public static string Dicom_PatientStudy_Occupation_Label {
            get {
                return ResourceManager.GetString("Dicom_PatientStudy_Occupation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者年龄 的本地化字符串。
        /// </summary>
        public static string Dicom_PatientStudy_PatientsAge_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_PatientStudy_PatientsAge_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年龄 的本地化字符串。
        /// </summary>
        public static string Dicom_PatientStudy_PatientsAge_Label {
            get {
                return ResourceManager.GetString("Dicom_PatientStudy_PatientsAge_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者报告大小 的本地化字符串。
        /// </summary>
        public static string Dicom_PatientStudy_PatientsSize_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_PatientStudy_PatientsSize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 大小 的本地化字符串。
        /// </summary>
        public static string Dicom_PatientStudy_PatientsSize_Label {
            get {
                return ResourceManager.GetString("Dicom_PatientStudy_PatientsSize_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 患者报告宽 的本地化字符串。
        /// </summary>
        public static string Dicom_PatientStudy_PatientsWeight_DisplayName {
            get {
                return ResourceManager.GetString("Dicom_PatientStudy_PatientsWeight_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重量 的本地化字符串。
        /// </summary>
        public static string Dicom_PatientStudy_PatientsWeight_Label {
            get {
                return ResourceManager.GetString("Dicom_PatientStudy_PatientsWeight_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 变换后的边缘没有相应的值。 的本地化字符串。
        /// </summary>
        public static string ExceptionTransformedEdgeDoesNotMatch {
            get {
                return ResourceManager.GetString("ExceptionTransformedEdgeDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} x {1} 的本地化字符串。
        /// </summary>
        public static string Format2Dimensions {
            get {
                return ResourceManager.GetString("Format2Dimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ({1}) 的本地化字符串。
        /// </summary>
        public static string FormatCalibrationDetails {
            get {
                return ResourceManager.GetString("FormatCalibrationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} cm 的本地化字符串。
        /// </summary>
        public static string FormatCentimeters {
            get {
                return ResourceManager.GetString("FormatCentimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} dGy·cm² 的本地化字符串。
        /// </summary>
        public static string FormatDecigraySquareCentimeters {
            get {
                return ResourceManager.GetString("FormatDecigraySquareCentimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}° 的本地化字符串。
        /// </summary>
        public static string FormatDegrees {
            get {
                return ResourceManager.GetString("FormatDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}/{1} 的本地化字符串。
        /// </summary>
        public static string FormatDisplaySetNumberAndCount {
            get {
                return ResourceManager.GetString("FormatDisplaySetNumberAndCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fr: {0}/{1} 的本地化字符串。
        /// </summary>
        public static string FormatFrameNumberAndCount {
            get {
                return ResourceManager.GetString("FormatFrameNumberAndCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Hz/px 的本地化字符串。
        /// </summary>
        public static string FormatHertzPerPixel {
            get {
                return ResourceManager.GetString("FormatHertzPerPixel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}/{1} 的本地化字符串。
        /// </summary>
        public static string FormatImageNumberAndCount {
            get {
                return ResourceManager.GetString("FormatImageNumberAndCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} kg 的本地化字符串。
        /// </summary>
        public static string FormatKilograms {
            get {
                return ResourceManager.GetString("FormatKilograms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} kV 的本地化字符串。
        /// </summary>
        public static string FormatKilovolts {
            get {
                return ResourceManager.GetString("FormatKilovolts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}/{1} 的本地化字符串。
        /// </summary>
        public static string FormatLateralityViewPosition {
            get {
                return ResourceManager.GetString("FormatLateralityViewPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}({1}) 的本地化字符串。
        /// </summary>
        public static string FormatLossyCompressionRatio {
            get {
                return ResourceManager.GetString("FormatLossyCompressionRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} m 的本地化字符串。
        /// </summary>
        public static string FormatMeters {
            get {
                return ResourceManager.GetString("FormatMeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} mA 的本地化字符串。
        /// </summary>
        public static string FormatMilliamps {
            get {
                return ResourceManager.GetString("FormatMilliamps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} mAs 的本地化字符串。
        /// </summary>
        public static string FormatMilliampSeconds {
            get {
                return ResourceManager.GetString("FormatMilliampSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} mm 的本地化字符串。
        /// </summary>
        public static string FormatMillimeters {
            get {
                return ResourceManager.GetString("FormatMillimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} mm/s 的本地化字符串。
        /// </summary>
        public static string FormatMillimetersPerSecond {
            get {
                return ResourceManager.GetString("FormatMillimetersPerSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ms 的本地化字符串。
        /// </summary>
        public static string FormatMilliseconds {
            get {
                return ResourceManager.GetString("FormatMilliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} N 的本地化字符串。
        /// </summary>
        public static string FormatNewtons {
            get {
                return ResourceManager.GetString("FormatNewtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}/{1} 的本地化字符串。
        /// </summary>
        public static string FormatSeriesNumberAndCount {
            get {
                return ResourceManager.GetString("FormatSeriesNumberAndCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} ({1}) 的本地化字符串。
        /// </summary>
        public static string FormatTablePositionSpeed {
            get {
                return ResourceManager.GetString("FormatTablePositionSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} T 的本地化字符串。
        /// </summary>
        public static string FormatTeslas {
            get {
                return ResourceManager.GetString("FormatTeslas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0}x 的本地化字符串。
        /// </summary>
        public static string FormatZoomFactor {
            get {
                return ResourceManager.GetString("FormatZoomFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lut (Applied) 的本地化字符串。
        /// </summary>
        public static string Presentation_AppliedLut_DisplayName {
            get {
                return ResourceManager.GetString("Presentation_AppliedLut_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Lut 的本地化字符串。
        /// </summary>
        public static string Presentation_AppliedLut_Label {
            get {
                return ResourceManager.GetString("Presentation_AppliedLut_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示领域试图 的本地化字符串。
        /// </summary>
        public static string Presentation_DFOV_DisplayName {
            get {
                return ResourceManager.GetString("Presentation_DFOV_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DFOV 的本地化字符串。
        /// </summary>
        public static string Presentation_DFOV_Label {
            get {
                return ResourceManager.GetString("Presentation_DFOV_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向标记 (底部) 的本地化字符串。
        /// </summary>
        public static string Presentation_DirectionalMarkers_Bottom_DisplayName {
            get {
                return ResourceManager.GetString("Presentation_DirectionalMarkers_Bottom_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Presentation_DirectionalMarkers_Bottom_Label {
            get {
                return ResourceManager.GetString("Presentation_DirectionalMarkers_Bottom_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向标记 (左) 的本地化字符串。
        /// </summary>
        public static string Presentation_DirectionalMarkers_Left_DisplayName {
            get {
                return ResourceManager.GetString("Presentation_DirectionalMarkers_Left_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Presentation_DirectionalMarkers_Left_Label {
            get {
                return ResourceManager.GetString("Presentation_DirectionalMarkers_Left_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向标记 (右) 的本地化字符串。
        /// </summary>
        public static string Presentation_DirectionalMarkers_Right_DisplayName {
            get {
                return ResourceManager.GetString("Presentation_DirectionalMarkers_Right_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Presentation_DirectionalMarkers_Right_Label {
            get {
                return ResourceManager.GetString("Presentation_DirectionalMarkers_Right_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向标记 (上) 的本地化字符串。
        /// </summary>
        public static string Presentation_DirectionalMarkers_Top_DisplayName {
            get {
                return ResourceManager.GetString("Presentation_DirectionalMarkers_Top_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        public static string Presentation_DirectionalMarkers_Top_Label {
            get {
                return ResourceManager.GetString("Presentation_DirectionalMarkers_Top_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示集说明 的本地化字符串。
        /// </summary>
        public static string Presentation_DisplaySetDescription_DisplayName {
            get {
                return ResourceManager.GetString("Presentation_DisplaySetDescription_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Desc. 的本地化字符串。
        /// </summary>
        public static string Presentation_DisplaySetDescription_Label {
            get {
                return ResourceManager.GetString("Presentation_DisplaySetDescription_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示集编号 的本地化字符串。
        /// </summary>
        public static string Presentation_DisplaySetNumber_DisplayName {
            get {
                return ResourceManager.GetString("Presentation_DisplaySetNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Se 的本地化字符串。
        /// </summary>
        public static string Presentation_DisplaySetNumber_Label {
            get {
                return ResourceManager.GetString("Presentation_DisplaySetNumber_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像校准 的本地化字符串。
        /// </summary>
        public static string Presentation_ImageCalibration_DisplayName {
            get {
                return ResourceManager.GetString("Presentation_ImageCalibration_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 校准 的本地化字符串。
        /// </summary>
        public static string Presentation_ImageCalibration_Label {
            get {
                return ResourceManager.GetString("Presentation_ImageCalibration_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有损图像介绍 的本地化字符串。
        /// </summary>
        public static string Presentation_Lossy_DisplayName {
            get {
                return ResourceManager.GetString("Presentation_Lossy_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有损 的本地化字符串。
        /// </summary>
        public static string Presentation_Lossy_Label {
            get {
                return ResourceManager.GetString("Presentation_Lossy_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放 的本地化字符串。
        /// </summary>
        public static string Presentation_Zoom_DisplayName {
            get {
                return ResourceManager.GetString("Presentation_Zoom_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩放 的本地化字符串。
        /// </summary>
        public static string Presentation_Zoom_Label {
            get {
                return ResourceManager.GetString("Presentation_Zoom_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 / 的本地化字符串。
        /// </summary>
        public static string SeparatorAgeSexBirthDate {
            get {
                return ResourceManager.GetString("SeparatorAgeSexBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 / 的本地化字符串。
        /// </summary>
        public static string SeparatorLossyCompressionRatio {
            get {
                return ResourceManager.GetString("SeparatorLossyCompressionRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 \ 的本地化字符串。
        /// </summary>
        public static string SeparatorSingleLine {
            get {
                return ResourceManager.GetString("SeparatorSingleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实际的 的本地化字符串。
        /// </summary>
        public static string ValueActualSpacingCalibration {
            get {
                return ResourceManager.GetString("ValueActualSpacingCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 探测仪 的本地化字符串。
        /// </summary>
        public static string ValueDetectorSpacingCalibration {
            get {
                return ResourceManager.GetString("ValueDetectorSpacingCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersAnterior {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 F 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersFoot {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersFoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 H 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersHead {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersLeft {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 P 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersPosterior {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersPosterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cd 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersQuadrupedCaudal {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersQuadrupedCaudal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cr 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersQuadrupedCranial {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersQuadrupedCranial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Di 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersQuadrupedDistal {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersQuadrupedDistal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 D 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersQuadrupedDorsal {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersQuadrupedDorsal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 L 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersQuadrupedLateral {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersQuadrupedLateral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Le 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersQuadrupedLeft {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersQuadrupedLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersQuadrupedMedial {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersQuadrupedMedial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pa 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersQuadrupedPalmar {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersQuadrupedPalmar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pl 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersQuadrupedPlantar {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersQuadrupedPlantar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Pr 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersQuadrupedProximal {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersQuadrupedProximal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Rt 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersQuadrupedRight {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersQuadrupedRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersQuadrupedRostral {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersQuadrupedRostral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersQuadrupedVentral {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersQuadrupedVentral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 R 的本地化字符串。
        /// </summary>
        public static string ValueDirectionalMarkersRight {
            get {
                return ResourceManager.GetString("ValueDirectionalMarkersRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基准 的本地化字符串。
        /// </summary>
        public static string ValueFiducialCalibration {
            get {
                return ResourceManager.GetString("ValueFiducialCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 几何 的本地化字符串。
        /// </summary>
        public static string ValueGeometricCalibration {
            get {
                return ResourceManager.GetString("ValueGeometricCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有损 的本地化字符串。
        /// </summary>
        public static string ValueLossy {
            get {
                return ResourceManager.GetString("ValueLossy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 倍率 的本地化字符串。
        /// </summary>
        public static string ValueMagnifiedCalibration {
            get {
                return ResourceManager.GetString("ValueMagnifiedCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户 的本地化字符串。
        /// </summary>
        public static string ValueManualCalibration {
            get {
                return ResourceManager.GetString("ValueManualCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 - 的本地化字符串。
        /// </summary>
        public static string ValueNil {
            get {
                return ResourceManager.GetString("ValueNil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 值校准 的本地化字符串。
        /// </summary>
        public static string ValueNoCalibration {
            get {
                return ResourceManager.GetString("ValueNoCalibration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 N/A 的本地化字符串。
        /// </summary>
        public static string ValueNotApplicable {
            get {
                return ResourceManager.GetString("ValueNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未知 的本地化字符串。
        /// </summary>
        public static string ValueUnknownCalibration {
            get {
                return ResourceManager.GetString("ValueUnknownCalibration", resourceCulture);
            }
        }
    }
}
